// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: post.proto

package nygpostprotoc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NYGPostProfile_RecieveNYGProfile_FullMethodName = "/nygpostprotoc.NYGPostProfile/RecieveNYGProfile"
	NYGPostProfile_RecieveNYGDeck_FullMethodName    = "/nygpostprotoc.NYGPostProfile/RecieveNYGDeck"
	NYGPostProfile_RecieveNYGCredits_FullMethodName = "/nygpostprotoc.NYGPostProfile/RecieveNYGCredits"
)

// NYGPostProfileClient is the client API for NYGPostProfile service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// profile
type NYGPostProfileClient interface {
	RecieveNYGProfile(ctx context.Context, in *NYGProfileParam, opts ...grpc.CallOption) (*TypeNYGProfile, error)
	RecieveNYGDeck(ctx context.Context, in *NYGDeckParam, opts ...grpc.CallOption) (*TypeNYGDeck, error)
	RecieveNYGCredits(ctx context.Context, in *NYGPlayerCreditsParam, opts ...grpc.CallOption) (*TypeNYGCredit, error)
}

type nYGPostProfileClient struct {
	cc grpc.ClientConnInterface
}

func NewNYGPostProfileClient(cc grpc.ClientConnInterface) NYGPostProfileClient {
	return &nYGPostProfileClient{cc}
}

func (c *nYGPostProfileClient) RecieveNYGProfile(ctx context.Context, in *NYGProfileParam, opts ...grpc.CallOption) (*TypeNYGProfile, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeNYGProfile)
	err := c.cc.Invoke(ctx, NYGPostProfile_RecieveNYGProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nYGPostProfileClient) RecieveNYGDeck(ctx context.Context, in *NYGDeckParam, opts ...grpc.CallOption) (*TypeNYGDeck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeNYGDeck)
	err := c.cc.Invoke(ctx, NYGPostProfile_RecieveNYGDeck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nYGPostProfileClient) RecieveNYGCredits(ctx context.Context, in *NYGPlayerCreditsParam, opts ...grpc.CallOption) (*TypeNYGCredit, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TypeNYGCredit)
	err := c.cc.Invoke(ctx, NYGPostProfile_RecieveNYGCredits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NYGPostProfileServer is the server API for NYGPostProfile service.
// All implementations must embed UnimplementedNYGPostProfileServer
// for forward compatibility.
//
// profile
type NYGPostProfileServer interface {
	RecieveNYGProfile(context.Context, *NYGProfileParam) (*TypeNYGProfile, error)
	RecieveNYGDeck(context.Context, *NYGDeckParam) (*TypeNYGDeck, error)
	RecieveNYGCredits(context.Context, *NYGPlayerCreditsParam) (*TypeNYGCredit, error)
	mustEmbedUnimplementedNYGPostProfileServer()
}

// UnimplementedNYGPostProfileServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNYGPostProfileServer struct{}

func (UnimplementedNYGPostProfileServer) RecieveNYGProfile(context.Context, *NYGProfileParam) (*TypeNYGProfile, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveNYGProfile not implemented")
}
func (UnimplementedNYGPostProfileServer) RecieveNYGDeck(context.Context, *NYGDeckParam) (*TypeNYGDeck, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveNYGDeck not implemented")
}
func (UnimplementedNYGPostProfileServer) RecieveNYGCredits(context.Context, *NYGPlayerCreditsParam) (*TypeNYGCredit, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecieveNYGCredits not implemented")
}
func (UnimplementedNYGPostProfileServer) mustEmbedUnimplementedNYGPostProfileServer() {}
func (UnimplementedNYGPostProfileServer) testEmbeddedByValue()                        {}

// UnsafeNYGPostProfileServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NYGPostProfileServer will
// result in compilation errors.
type UnsafeNYGPostProfileServer interface {
	mustEmbedUnimplementedNYGPostProfileServer()
}

func RegisterNYGPostProfileServer(s grpc.ServiceRegistrar, srv NYGPostProfileServer) {
	// If the following call pancis, it indicates UnimplementedNYGPostProfileServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NYGPostProfile_ServiceDesc, srv)
}

func _NYGPostProfile_RecieveNYGProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NYGProfileParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NYGPostProfileServer).RecieveNYGProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NYGPostProfile_RecieveNYGProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NYGPostProfileServer).RecieveNYGProfile(ctx, req.(*NYGProfileParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _NYGPostProfile_RecieveNYGDeck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NYGDeckParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NYGPostProfileServer).RecieveNYGDeck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NYGPostProfile_RecieveNYGDeck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NYGPostProfileServer).RecieveNYGDeck(ctx, req.(*NYGDeckParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _NYGPostProfile_RecieveNYGCredits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NYGPlayerCreditsParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NYGPostProfileServer).RecieveNYGCredits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NYGPostProfile_RecieveNYGCredits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NYGPostProfileServer).RecieveNYGCredits(ctx, req.(*NYGPlayerCreditsParam))
	}
	return interceptor(ctx, in, info, handler)
}

// NYGPostProfile_ServiceDesc is the grpc.ServiceDesc for NYGPostProfile service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NYGPostProfile_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nygpostprotoc.NYGPostProfile",
	HandlerType: (*NYGPostProfileServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecieveNYGProfile",
			Handler:    _NYGPostProfile_RecieveNYGProfile_Handler,
		},
		{
			MethodName: "RecieveNYGDeck",
			Handler:    _NYGPostProfile_RecieveNYGDeck_Handler,
		},
		{
			MethodName: "RecieveNYGCredits",
			Handler:    _NYGPostProfile_RecieveNYGCredits_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
