// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: post.proto

package nygpostprotoc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TypeNYGProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeNYGProfile) Reset() {
	*x = TypeNYGProfile{}
	mi := &file_post_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeNYGProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeNYGProfile) ProtoMessage() {}

func (x *TypeNYGProfile) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeNYGProfile.ProtoReflect.Descriptor instead.
func (*TypeNYGProfile) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{0}
}

func (x *TypeNYGProfile) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TypeNYGProfile) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TypeNYGProfile) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

type TypeNYGGameProfile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GamesPlayed   int32                  `protobuf:"varint,1,opt,name=gamesPlayed,proto3" json:"gamesPlayed,omitempty"`
	Tier          string                 `protobuf:"bytes,2,opt,name=tier,proto3" json:"tier,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Points        int32                  `protobuf:"varint,4,opt,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeNYGGameProfile) Reset() {
	*x = TypeNYGGameProfile{}
	mi := &file_post_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeNYGGameProfile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeNYGGameProfile) ProtoMessage() {}

func (x *TypeNYGGameProfile) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeNYGGameProfile.ProtoReflect.Descriptor instead.
func (*TypeNYGGameProfile) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{1}
}

func (x *TypeNYGGameProfile) GetGamesPlayed() int32 {
	if x != nil {
		return x.GamesPlayed
	}
	return 0
}

func (x *TypeNYGGameProfile) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *TypeNYGGameProfile) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *TypeNYGGameProfile) GetPoints() int32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type NYGProfileParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NYGProfileParam) Reset() {
	*x = NYGProfileParam{}
	mi := &file_post_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NYGProfileParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NYGProfileParam) ProtoMessage() {}

func (x *NYGProfileParam) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NYGProfileParam.ProtoReflect.Descriptor instead.
func (*NYGProfileParam) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{2}
}

func (x *NYGProfileParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TypeNYGDeck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	First         string                 `protobuf:"bytes,2,opt,name=first,proto3" json:"first,omitempty"`
	Second        string                 `protobuf:"bytes,3,opt,name=second,proto3" json:"second,omitempty"`
	IsDefault     bool                   `protobuf:"varint,4,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeNYGDeck) Reset() {
	*x = TypeNYGDeck{}
	mi := &file_post_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeNYGDeck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeNYGDeck) ProtoMessage() {}

func (x *TypeNYGDeck) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeNYGDeck.ProtoReflect.Descriptor instead.
func (*TypeNYGDeck) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{3}
}

func (x *TypeNYGDeck) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TypeNYGDeck) GetFirst() string {
	if x != nil {
		return x.First
	}
	return ""
}

func (x *TypeNYGDeck) GetSecond() string {
	if x != nil {
		return x.Second
	}
	return ""
}

func (x *TypeNYGDeck) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type NYGDeckParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NYGDeckParam) Reset() {
	*x = NYGDeckParam{}
	mi := &file_post_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NYGDeckParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NYGDeckParam) ProtoMessage() {}

func (x *NYGDeckParam) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NYGDeckParam.ProtoReflect.Descriptor instead.
func (*NYGDeckParam) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{4}
}

func (x *NYGDeckParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// playerCredits
// service NYGCredits{
// }
type TypeNYGCredit struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Coins          string                 `protobuf:"bytes,1,opt,name=coins,proto3" json:"coins,omitempty"`
	Spurs          string                 `protobuf:"bytes,2,opt,name=spurs,proto3" json:"spurs,omitempty"`
	BoardTheme     string                 `protobuf:"bytes,3,opt,name=boardTheme,proto3" json:"boardTheme,omitempty"`
	GuessTheme     string                 `protobuf:"bytes,4,opt,name=guessTheme,proto3" json:"guessTheme,omitempty"`
	Id             string                 `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	ClashProfile   *TypeNYGGameProfile    `protobuf:"bytes,6,opt,name=clashProfile,proto3" json:"clashProfile,omitempty"`
	OnevoneProfile *TypeNYGGameProfile    `protobuf:"bytes,7,opt,name=onevoneProfile,proto3" json:"onevoneProfile,omitempty"`
	TwovtwoProfile *TypeNYGGameProfile    `protobuf:"bytes,8,opt,name=twovtwoProfile,proto3" json:"twovtwoProfile,omitempty"`
	ImgURL         string                 `protobuf:"bytes,9,opt,name=imgURL,proto3" json:"imgURL,omitempty"`
	Nexus          int32                  `protobuf:"varint,10,opt,name=nexus,proto3" json:"nexus,omitempty"`
	Freeze         int32                  `protobuf:"varint,11,opt,name=freeze,proto3" json:"freeze,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TypeNYGCredit) Reset() {
	*x = TypeNYGCredit{}
	mi := &file_post_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeNYGCredit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeNYGCredit) ProtoMessage() {}

func (x *TypeNYGCredit) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeNYGCredit.ProtoReflect.Descriptor instead.
func (*TypeNYGCredit) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{5}
}

func (x *TypeNYGCredit) GetCoins() string {
	if x != nil {
		return x.Coins
	}
	return ""
}

func (x *TypeNYGCredit) GetSpurs() string {
	if x != nil {
		return x.Spurs
	}
	return ""
}

func (x *TypeNYGCredit) GetBoardTheme() string {
	if x != nil {
		return x.BoardTheme
	}
	return ""
}

func (x *TypeNYGCredit) GetGuessTheme() string {
	if x != nil {
		return x.GuessTheme
	}
	return ""
}

func (x *TypeNYGCredit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TypeNYGCredit) GetClashProfile() *TypeNYGGameProfile {
	if x != nil {
		return x.ClashProfile
	}
	return nil
}

func (x *TypeNYGCredit) GetOnevoneProfile() *TypeNYGGameProfile {
	if x != nil {
		return x.OnevoneProfile
	}
	return nil
}

func (x *TypeNYGCredit) GetTwovtwoProfile() *TypeNYGGameProfile {
	if x != nil {
		return x.TwovtwoProfile
	}
	return nil
}

func (x *TypeNYGCredit) GetImgURL() string {
	if x != nil {
		return x.ImgURL
	}
	return ""
}

func (x *TypeNYGCredit) GetNexus() int32 {
	if x != nil {
		return x.Nexus
	}
	return 0
}

func (x *TypeNYGCredit) GetFreeze() int32 {
	if x != nil {
		return x.Freeze
	}
	return 0
}

type NYGPlayerCreditsParam struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NYGPlayerCreditsParam) Reset() {
	*x = NYGPlayerCreditsParam{}
	mi := &file_post_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NYGPlayerCreditsParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NYGPlayerCreditsParam) ProtoMessage() {}

func (x *NYGPlayerCreditsParam) ProtoReflect() protoreflect.Message {
	mi := &file_post_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NYGPlayerCreditsParam.ProtoReflect.Descriptor instead.
func (*NYGPlayerCreditsParam) Descriptor() ([]byte, []int) {
	return file_post_proto_rawDescGZIP(), []int{6}
}

func (x *NYGPlayerCreditsParam) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_post_proto protoreflect.FileDescriptor

const file_post_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"post.proto\x12\rnygpostprotoc\"P\n" +
	"\x0eTypeNYGProfile\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\"z\n" +
	"\x12TypeNYGGameProfile\x12 \n" +
	"\vgamesPlayed\x18\x01 \x01(\x05R\vgamesPlayed\x12\x12\n" +
	"\x04tier\x18\x02 \x01(\tR\x04tier\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12\x16\n" +
	"\x06points\x18\x04 \x01(\x05R\x06points\"!\n" +
	"\x0fNYGProfileParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"i\n" +
	"\vTypeNYGDeck\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05first\x18\x02 \x01(\tR\x05first\x12\x16\n" +
	"\x06second\x18\x03 \x01(\tR\x06second\x12\x1c\n" +
	"\tisDefault\x18\x04 \x01(\bR\tisDefault\"\x1e\n" +
	"\fNYGDeckParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xae\x03\n" +
	"\rTypeNYGCredit\x12\x14\n" +
	"\x05coins\x18\x01 \x01(\tR\x05coins\x12\x14\n" +
	"\x05spurs\x18\x02 \x01(\tR\x05spurs\x12\x1e\n" +
	"\n" +
	"boardTheme\x18\x03 \x01(\tR\n" +
	"boardTheme\x12\x1e\n" +
	"\n" +
	"guessTheme\x18\x04 \x01(\tR\n" +
	"guessTheme\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12E\n" +
	"\fclashProfile\x18\x06 \x01(\v2!.nygpostprotoc.TypeNYGGameProfileR\fclashProfile\x12I\n" +
	"\x0eonevoneProfile\x18\a \x01(\v2!.nygpostprotoc.TypeNYGGameProfileR\x0eonevoneProfile\x12I\n" +
	"\x0etwovtwoProfile\x18\b \x01(\v2!.nygpostprotoc.TypeNYGGameProfileR\x0etwovtwoProfile\x12\x16\n" +
	"\x06imgURL\x18\t \x01(\tR\x06imgURL\x12\x14\n" +
	"\x05nexus\x18\n" +
	" \x01(\x05R\x05nexus\x12\x16\n" +
	"\x06freeze\x18\v \x01(\x05R\x06freeze\"'\n" +
	"\x15NYGPlayerCreditsParam\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2\x8e\x02\n" +
	"\x0eNYGPostProfile\x12T\n" +
	"\x11RecieveNYGProfile\x12\x1e.nygpostprotoc.NYGProfileParam\x1a\x1d.nygpostprotoc.TypeNYGProfile\"\x00\x12K\n" +
	"\x0eRecieveNYGDeck\x12\x1b.nygpostprotoc.NYGDeckParam\x1a\x1a.nygpostprotoc.TypeNYGDeck\"\x00\x12Y\n" +
	"\x11RecieveNYGCredits\x12$.nygpostprotoc.NYGPlayerCreditsParam\x1a\x1c.nygpostprotoc.TypeNYGCredit\"\x00B\x13Z\x11app/nygpostprotocb\x06proto3"

var (
	file_post_proto_rawDescOnce sync.Once
	file_post_proto_rawDescData []byte
)

func file_post_proto_rawDescGZIP() []byte {
	file_post_proto_rawDescOnce.Do(func() {
		file_post_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)))
	})
	return file_post_proto_rawDescData
}

var file_post_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_post_proto_goTypes = []any{
	(*TypeNYGProfile)(nil),        // 0: nygpostprotoc.TypeNYGProfile
	(*TypeNYGGameProfile)(nil),    // 1: nygpostprotoc.TypeNYGGameProfile
	(*NYGProfileParam)(nil),       // 2: nygpostprotoc.NYGProfileParam
	(*TypeNYGDeck)(nil),           // 3: nygpostprotoc.TypeNYGDeck
	(*NYGDeckParam)(nil),          // 4: nygpostprotoc.NYGDeckParam
	(*TypeNYGCredit)(nil),         // 5: nygpostprotoc.TypeNYGCredit
	(*NYGPlayerCreditsParam)(nil), // 6: nygpostprotoc.NYGPlayerCreditsParam
}
var file_post_proto_depIdxs = []int32{
	1, // 0: nygpostprotoc.TypeNYGCredit.clashProfile:type_name -> nygpostprotoc.TypeNYGGameProfile
	1, // 1: nygpostprotoc.TypeNYGCredit.onevoneProfile:type_name -> nygpostprotoc.TypeNYGGameProfile
	1, // 2: nygpostprotoc.TypeNYGCredit.twovtwoProfile:type_name -> nygpostprotoc.TypeNYGGameProfile
	2, // 3: nygpostprotoc.NYGPostProfile.RecieveNYGProfile:input_type -> nygpostprotoc.NYGProfileParam
	4, // 4: nygpostprotoc.NYGPostProfile.RecieveNYGDeck:input_type -> nygpostprotoc.NYGDeckParam
	6, // 5: nygpostprotoc.NYGPostProfile.RecieveNYGCredits:input_type -> nygpostprotoc.NYGPlayerCreditsParam
	0, // 6: nygpostprotoc.NYGPostProfile.RecieveNYGProfile:output_type -> nygpostprotoc.TypeNYGProfile
	3, // 7: nygpostprotoc.NYGPostProfile.RecieveNYGDeck:output_type -> nygpostprotoc.TypeNYGDeck
	5, // 8: nygpostprotoc.NYGPostProfile.RecieveNYGCredits:output_type -> nygpostprotoc.TypeNYGCredit
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_post_proto_init() }
func file_post_proto_init() {
	if File_post_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_proto_rawDesc), len(file_post_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_proto_goTypes,
		DependencyIndexes: file_post_proto_depIdxs,
		MessageInfos:      file_post_proto_msgTypes,
	}.Build()
	File_post_proto = out.File
	file_post_proto_goTypes = nil
	file_post_proto_depIdxs = nil
}
