// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type InitMessage struct {
	ID       string `json:"id"`
	Msg      string `json:"msg"`
	Roomname string `json:"roomname"`
	Name     string `json:"name"`
}

type LatestMessage struct {
	ID       string `json:"id"`
	Msg      string `json:"msg"`
	Roomname string `json:"roomname"`
	Name     string `json:"name"`
}

type Mutation struct {
}

type Put struct {
	ID       string `json:"id"`
	Msg      string `json:"msg"`
	Roomname string `json:"roomname"`
	Name     string `json:"name"`
}

type Query struct {
}

type Reply struct {
	Status int32  `json:"status"`
	Name   string `json:"name"`
	Msg    string `json:"msg"`
}

type Subscription struct {
}
