package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"app/server/graph/model"
	"context"
	"fmt"
)

// Login is the resolver for the login field.
func (r *queryResolver) Login(ctx context.Context, id string) (*model.LoginReply, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// UpdatedBooks is the resolver for the updatedBooks field.
func (r *queryResolver) UpdatedBooks(ctx context.Context) (*model.IBooks, error) {
	panic(fmt.Errorf("not implemented: UpdatedBooks - updatedBooks"))
}

// UpdatedPlayerCredits is the resolver for the updatedPlayerCredits field.
func (r *subscriptionResolver) UpdatedPlayerCredits(ctx context.Context, id string) (<-chan *model.ICredits, error) {
	panic(fmt.Errorf("not implemented: UpdatedPlayerCredits - updatedPlayerCredits"))
}

// Name is the resolver for the name field.
func (r *subscriptionResolver) Name(ctx context.Context, id string) (<-chan string, error) {
	panic(fmt.Errorf("not implemented: Name - name"))
}

// Nickname is the resolver for the nickname field.
func (r *subscriptionResolver) Nickname(ctx context.Context, id string) (<-chan string, error) {
	panic(fmt.Errorf("not implemented: Nickname - nickname"))
}

// UpdatedStore is the resolver for the updatedStore field.
func (r *subscriptionResolver) UpdatedStore(ctx context.Context, id string) (<-chan *model.Store, error) {
	panic(fmt.Errorf("not implemented: UpdatedStore - updatedStore"))
}

// UpdatedEvents is the resolver for the updatedEvents field.
func (r *subscriptionResolver) UpdatedEvents(ctx context.Context, id string) (<-chan *model.DailyEvents, error) {
	panic(fmt.Errorf("not implemented: UpdatedEvents - updatedEvents"))
}

// UpdatedDisplay is the resolver for the updatedDisplay field.
func (r *subscriptionResolver) UpdatedDisplay(ctx context.Context, id string) (<-chan *model.Display, error) {
	panic(fmt.Errorf("not implemented: UpdatedDisplay - updatedDisplay"))
}

// UpdatedPowerupUpgrades is the resolver for the updatedPowerupUpgrades field.
func (r *subscriptionResolver) UpdatedPowerupUpgrades(ctx context.Context, id string) (<-chan *model.PowerProgress, error) {
	panic(fmt.Errorf("not implemented: UpdatedPowerupUpgrades - updatedPowerupUpgrades"))
}

// CurrentDeck is the resolver for the currentDeck field.
func (r *subscriptionResolver) CurrentDeck(ctx context.Context, id string) (<-chan *model.CurrentDeck, error) {
	panic(fmt.Errorf("not implemented: CurrentDeck - currentDeck"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
