package update

import (
	"fmt"
	"maps"
	"nyg/dataset"
)

type BasketballParcel struct {
	Pack []SportsParcel
}

// keys
const (
	NBA2008OKey = "BASKETBALL 2008 OLYMPCIS"
	NBA2004OKey = "BASKETBALL 2004 OLYMPCIS"

	NBA2000OKey = "BASKETBALL 2000 OLYMPCIS"
	NBA1996OKey = "BASKETBALL 1996 OLYMPCIS"

	NBA1992Key = "NBA 1992"
	NBA1991Key = "NBA 1991"
	NBA2011Key = "NBA 2011"
	NBA2012Key = "NBA 2012"

	BasketballKey = "BASKETBALL"
)

func NBA2011() dataset.SearchSystem_ {
	n2011 := map[string][]string{}
	n2011["boston celtic"] = []string{
		"Ray Allen",
		"Carlos Arroyo",
		"Avery Bradley",
		"Marquis Daniels",
		"Glen Davis",
		"Semih Erden",
		"Kevin Garnett",
		"Jeff Green",
		"Luke Harangody",
		"Chris Johnson",
		"Troy Murphy",
		"Jermaine O'Neal",
		"Shaquille O'Neal",
		"Kendrick Perkins",
		"Paul Pierce",
		"Nate Robinson",
		"Rajon Rondo",
		"Von Wafer",
		"Delonte West",
	}
	n2011["new york knicks"] = []string{
		"Carmelo Anthony",
		"Renaldo Balkman",
		"Chauncey Billups",
		"Derrick Brown",
		"Anthony",
		"Wilson",
		"Toney Douglas",
		"Raymond Felton",
		"Landry Fields",
		"Danilo Gallinari",
		"Jared Jeffries",
		"Roger Mason",
		"Timofey Mozgov",
		"Anthony Randolph",
		"Andy Rautins",
		"Amar'e Stoudemire",
		"Ronny Turiaf",
		"Henry Walker",
		"Shawne Williams",
		"Shelden Williams",
	}
	n2011["philadelphia"] = []string{
		"Tony Battie",
		"Craig Brackins",
		"Elton Brand",
		"Antonio Daniels",
		"Spencer Hawes",
		"Jrue Holiday",
		"Andre Iguodala",
		"Jason Kapono",
		"Jodie Meeks",
		"Darius Songaila",
		"Marreese Speights",
		"Evan Turner",
		"Lou Williams",
		"Thaddeus Young",
	}
	n2011["new jersey nets"] = []string{
		"Jordan Farmar",
		"Derrick Favors",
		"Dan Gadzuric",
		"Sundiata Gaines",
		"Stephen Graham",
		"Orien Greene",
		"Devin Harris",
		"Kris Humphries",
		"Damion James",
		"Brook Lopez",
		"Anthony Morrow",
		"Troy Murphy",
		"Travis Outlaw",
		"Johan Petro",
		"Quinton Ross",
		"Joe Smith",
		"Ben Uzoh",
		"Mario West",
		"Deron Williams",
		"Terrence Williams",
		"Brandan Wright",
	}
	n2011["toronto raptors"] = []string{
		"Solomon Alabi",
		"David Andersen",
		"Marcus Banks",
		"Leandro Barbosa",
		"Andrea Bargnani",
		"Jerryd Bayless",
		"Ed Davis",
		"DeMar DeRozan",
		"Joey Dorsey",
		"Ronald Dupree",
		"Reggie Evans",
		"Sundiata Gaines",
		"Jarrett Jack",
		"Amir Johnson",
		"James Johnson",
		"Trey Johnson",
		"Linas Kleiza",
		"Sonny Weems",
		"Julian Wright",
	}
	n2011["oklahoma city thunder"] = []string{
		"Cole Aldrich",
		"Nick",
		"Daequan",
		"Kevin Durant",
		"Jeff Green",
		"James Harden",
		"Serge Ibaka",
		"Royal Ivey",
		"Eric Maynor",
		"Nazr Mohammed",
		"Byron Mullens",
		"Kendrick Perkins",
		"Morris Peterson",
		"Nate Robinson",
		"Thabo Sefolosha",
		"Russell Westbrook",
		"D.J. White",
	}
	n2011["denver nuggets"] = []string{
		"Arron Afflalo",
		"Chris Andersen",
		"Carmelo Anthony",
		"Renaldo Balkman",
		"Chauncey Billups",
		"Anthony",
		"Wilson",
		"Melvin Ely",
		"Raymond Felton",
		"Gary Forbes",
		"Danilo Gallinari",
		"Al Harrington",
		"Kosta Koufos",
		"Ty Lawson",
		"Kenyon Martin",
		"Timofey Mozgov",
		"J.R. Smith",
		"Shelden Williams",
	}
	n2011["portland trail blazers"] = []string{
		"LaMarcus Aldridge",
		"Luke Babbitt",
		"Earl Barron",
		"Nicolas Batum",
		"Marcus",
		"Jarron",
		"Dante",
		"Armon Johnson",
		"Chris Johnson",
		"Sean Marks",
		"Wesley Matthews",
		"Andre Miller",
		"Patty Mills",
		"Fabricio Oberto",
		"Joel Przybilla",
		"Brandon Roy",
		"Gerald Wallace",
	}
	n2011["utha jazz"] = []string{
		"Raja Bell",
		"Marcus",
		"Francisco Elson",
		"Jeremy Evans",
		"Derrick Favors",
		"Kyrylo Fesenko",
		"Devin Harris",
		"Gordon Hayward",
		"Al Jefferson",
		"Andrei Kirilenko",
		"C.J. Miles",
		"Paul Millsap",
		"Mehmet Okur",
		"Ronnie Price",
		"Earl Watson",
		"Kyle Weaver",
		"Deron Williams",
	}
	n2011["minnesota timberwolves"] = []string{
		"Maurice Ager",
		"Michael Beasley",
		"Corey Brewer",
		"Wayne Ellington",
		"Jonny Flynn",
		"Sundiata Gaines",
		"Lazar Hayward",
		"Wesley Johnson",
		"Kosta Koufos",
		"Kevin Love",
		"Anthony Randolph",
		"Luke Ridnour",
		"Sebastian Telfair",
		"Anthony Tolliver",
		"Martell Webster",
	}
	n2011["chicago bulls"] = []string{
		"Keith Bogans",
		"Carlos Boozer",
		"Ronnie Brewer",
		"Rasual Butler",
		"Luol Deng",
		"Taj Gibson",
		"James Johnson",
		"Kyle Korver",
		"John Lucas III",
		"Joakim Noah",
		"Derrick Rose",
		"Brian Scalabrine",
		"Kurt Thomas",
		"C.J. Watson",
	}
	n2011["indiana pacers"] = []string{
		"Darren",
		"Mike Dunleavy",
		"T.J. Ford",
		"Jeff Foster",
		"Paul George",
		"Danny Granger",
		"Tyler Hansbrough",
		"Roy Hibbert",
		"Dahntay Jones",
		"Solomon Jones",
		"Josh McRoberts",
		"James Posey",
		"A.J. Price",
		"Brandon Rush",
		"Lance Stephenson",
	}
	n2011["milwaukee bucks"] = []string{
		"Earl Barron",
		"Andrew Bogut",
		"Earl Boykins",
		"Jon Brockman",
		"Carlos Delfino",
		"Keyon Dooling",
		"Drew Gooden",
		"Brandon Jennings",
		"Corey Maggette",
		"Luc Mbah a Moute",
		"Michael Redd",
		"John Salmons",
		"Larry Sanders",
		"Brian Skinner",
		"Garrett Temple",
	}
	n2011["detroit pistons"] = []string{
		"Will Bynum",
		"Austin Daye",
		"Ben Gordon",
		"Richard Hamilton",
		"Jason Maxiell",
		"Tracy McGrady",
		"Greg Monroe",
		"Tayshaun Prince",
		"Rodney Stuckey",
		"DaJuan Summers",
		"Charlie Villanueva",
		"Ben Wallace",
		"Chris Wilcox",
	}
	n2011["clevand cavaliers"] = []string{
		"Baron Davis",
		"Semih Erden",
		"Christian Eyenga",
		"Alonzo Gee",
		"Daniel Gibson",
		"Joey Graham",
		"Luke Harangody",
		"Manny Harris",
		"J.J. Hickson",
		"Ryan Hollins",
		"Antawn Jamison",
		"Jamario Moon",
		"Anthony Parker",
		"Leon Powe",
		"Samardo Samuels",
		"Ramon Sessions",
		"Jawad Williams",
		"Mo Williams",
	}
	n2011["los angeles lakers"] = []string{
		"Matt Barnes",
		"Steve Blake",
		"Shannon Brown",
		"Kobe Bryant",
		"Andrew Bynum",
		"Derrick",
		"Devin Ebanks",
		"Derek Fisher",
		"Pau Gasol",
		"Trey Johnson",
		"Lamar Odom",
		"Theo Ratliff",
		"Joe Smith",
		"Luke Walton",
		"Metta World Peace",
	}
	n2011["pheonix suns"] = []string{
		"Earl Barron",
		"Aaron Brooks",
		"Vince",
		"Josh",
		"Earl",
		"Zabian Dowdell",
		"Jared Dudley",
		"Channing Frye",
		"Marcin Gortat",
		"Grant Hill",
		"Gani Lawal",
		"Robin Lopez",
		"Steve Nash",
		"Jason Richardson",
		"Garret Siler",
		"Hakim Warrick",
	}
	n2011["golden state warriors"] = []string{
		"Jeff Adrien",
		"Lou Amundson",
		"Charlie Bell",
		"Rodney",
		"Stephen Curry",
		"Monta Ellis",
		"Dan Gadzuric",
		"Acie Law",
		"David Lee",
		"Jeremy Lin",
		"Al Thornton",
		"Ekpe Udoh",
		"Reggie Williams",
		"Brandan Wright",
		"Dorell Wright",
	}
	n2011["los angeles clippers"] = []string{
		"Eric Bledsoe",
		"Rasual Butler",
		"Jarron",
		"Brian",
		"Baron Davis",
		"Ike Diogu",
		"Randy Foye",
		"Ryan Gomes",
		"Eric Gordon",
		"Blake Griffin",
		"DeAndre Jordan",
		"Chris Kaman",
		"Jamario Moon",
		"Craig Smith",
		"Willie Warren",
		"Mo Williams",
	}
	n2011["sacramento knigs"] = []string{
		"Omri",
		"DeMarcus",
		"Samuel Dalembert",
		"Tyreke Evans",
		"Luther Head",
		"Darnell Jackson",
		"Eugene Jeter",
		"Carl Landry",
		"Jermaine Taylor",
		"Jason Thompson",
		"Marcus Thornton",
		"Beno Udrih",
		"Hassan Whiteside",
		"Antoine Wright",
	}
	n2011["miami heat"] = []string{
		"Joel Anthony",
		"Carlos Arroyo",
		"Mike Bibby",
		"Chris Bosh",
		"Mario Chalmers",
		"Erick Dampier",
		"Udonis Haslem",
		"Eddie House",
		"Juwan Howard",
		"Zydrunas Ilgauskas",
		"LeBron James",
		"James Jones",
		"Jamaal Magloire",
		"Mike Miller",
		"Dexter Pittman",
		"Jerry Stackhouse",
		"Dwyane Wade",
	}
	n2011["orlando magic"] = []string{
		"Malik Allen",
		"Ryan Anderson",
		"Gilbert Arenas",
		"Brandon Bass",
		"Vince Carter",
		"Earl Clark",
		"Chris Duhon",
		"Marcin Gortat",
		"Dwight Howard",
		"Rashard Lewis",
		"Jameer Nelson",
		"JJ Redick",
		"Jason Richardson",
		"Quentin Richardson",
		"Jason Williams",
	}
	n2011["atlanta hawks"] = []string{
		"Hilton Armstrong",
		"Mike Bibby",
		"Jason Collins",
		"Jamal Crawford",
		"Jordan",
		"Maurice Evans",
		"Kirk Hinrich",
		"Al Horford",
		"Joe Johnson",
		"Zaza Pachulia",
		"Josh Powell",
		"Josh Smith",
		"Pape Sy",
		"Jeff Teague",
		"Etan Thomas",
		"Damien Wilkins",
		"Marvin Williams",
	}
	n2011["charlotte bobcats"] = []string{
		"D.J. Augustin",
		"Derrick Brown",
		"Kwame Brown",
		"Matt",
		"Sherron",
		"Dante",
		"Boris Diaw",
		"DeSagana Diop",
		"Gerald Henderson",
		"Stephen Jackson",
		"Shaun Livingston",
		"Dominic McGuire",
		"Nazr Mohammed",
		"Joel Przybilla",
		"Garrett Temple",
		"Tyrus Thomas",
		"Gerald Wallace",
		"D.J. White",
	}
	n2011["washington wizards"] = []string{
		"Gilbert Arenas",
		"Hilton Armstrong",
		"Mike Bibby",
		"Andray Blatche",
		"Trevor Booker",
		"Jordan",
		"Maurice Evans",
		"Alonzo Gee",
		"Kirk Hinrich",
		"Josh Howard",
		"Lester Hudson",
		"Othyus Jeffers",
		"Yi Jianlian",
		"Rashard Lewis",
		"Cartier Martin",
		"JaVale McGee",
		"Hamady N'Diaye",
		"Larry Owens",
		"Mustafa Shakur",
		"Al Thornton",
		"John Wall",
		"Nick Young",
	}
	n2011["san antonio spurs"] = []string{
		"James Anderson",
		"DeJuan Blair",
		"Matt Bonner",
		"Tim Duncan",
		"Alonzo Gee",
		"Danny Green",
		"George Hill",
		"Othyus Jeffers",
		"Richard Jefferson",
		"Antonio McDyess",
		"Gary Neal",
		"Steve Novak",
		"Larry Owens",
		"Tony Parker",
		"Chris Quinn",
		"Bobby Simmons",
		"Tiago Splitter",
		"Garrett Temple",
		"Ime Udoka",
	}
	n2011["dallas mavericks"] = []string{
		"J.J. Barea",
		"Rodrigue Beaubois",
		"Corey Brewer",
		"Caron Butler",
		"Brian",
		"Tyson",
		"Brendan Haywood",
		"Dominique Jones",
		"Jason Kidd",
		"Ian Mahinmi",
		"Shawn Marion",
		"Steve Novak",
		"Dirk Nowitzki",
		"DeShawn Stevenson",
		"Jason Terry",
	}
	n2011["new orleans hornets"] = []string{
		"David Andersen",
		"Trevor Ariza",
		"Jerryd Bayless",
		"Marco Belinelli",
		"Patrick Ewing",
		"Aaron Gray",
		"Willie Green",
		"D.J. Mbenga",
		"Jarrett Jack",
		"Carl Landry",
		"Emeka Okafor",
		"Chris Paul",
		"Quincy Pondexter",
		"Jason Smith",
		"Marcus Thornton",
		"David West",
	}
	n2011["memphis grizzlies"] = []string{
		"Tony Allen",
		"Darrell Arthur",
		"Shane Battier",
		"Rodney",
		"DeMarre",
		"Mike",
		"Marc Gasol",
		"Rudy Gay",
		"Hamed Haddadi",
		"Xavier Henry",
		"Acie Law",
		"O.J. Mayo",
		"Leon Powe",
		"Zach Randolph",
		"Ish Smith",
		"Hasheem Thabeet",
		"Jason Williams",
		"Sam Young",
	}
	n2011["houston rockets"] = []string{
		"Shane Battier",
		"Aaron Brooks",
		"Chase Budinger",
		"DeMarre",
		"Mike Harris",
		"Chuck Hayes",
		"Jordan Hill",
		"Jared Jeffries",
		"Courtney Lee",
		"Kyle Lowry",
		"Kevin Martin",
		"Brad Miller",
		"Yao Ming",
		"Patrick Patterson",
		"Luis Scola",
		"Ish Smith",
		"Jermaine Taylor",
		"Hasheem Thabeet",
		"Terrence Williams",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA2011Key, SportKey, BasketballKey, n2011, false, false, true)
	return NBA
}

func NBA2012() dataset.SearchSystem_ {
	n2012 := map[string][]string{}
	n2012["boston celtics"] = []string{
		"Ray Allen",
		"Brandon Bass",
		"Avery Bradley",
		"Marquis Daniels",
		"Keyon Dooling",
		"Kevin Garnett",
		"Ryan Hollins",
		"JaJuan Johnson",
		"E'Twaun Moore",
		"Jermaine O'Neal",
		"Paul Pierce",
		"Rajon Rondo",
		"Greg Stiemsma",
		"Chris Wilcox",
		"Sean Williams",
	}
	n2012["new york knicks"] = []string{
		"Carmelo Anthony",
		"Renaldo Balkman",
		"Mike Bibby",
		"Tyson",
		"Baron Davis",
		"Toney Douglas",
		"Landry Fields",
		"Dan Gadzuric",
		"Josh Harrellson",
		"Jared Jeffries",
		"Jerome Jordan",
		"Jeremy Lin",
		"Steve Novak",
		"Iman Shumpert",
		"J.R. Smith",
		"Amar'e Stoudemire",
		"Henry Walker",
	}
	n2012["philadelphia 76ers"] = []string{
		"Lavoy Allen",
		"Tony Battie",
		"Craig Brackins",
		"Elton Brand",
		"Francisco Elson",
		"Spencer Hawes",
		"Jrue Holiday",
		"Andre Iguodala",
		"Jodie Meeks",
		"Xavier Silas",
		"Evan Turner",
		"Lou Williams",
		"Sam Young",
		"Thaddeus Young",
	}
	n2012["toronto raptors"] = []string{
		"Solomon Alabi",
		"Alan Anderson",
		"Leandro Barbosa",
		"Andrea Bargnani",
		"Jerryd Bayless",
		"Rasual Butler",
		"Anthony",
		"Ed Davis",
		"Justin Dentmon",
		"DeMar DeRozan",
		"Gary Forbes",
		"Aaron Gray",
		"Amir Johnson",
		"James Johnson",
		"Linas Kleiza",
		"Jamaal Magloire",
		"Ben Uzoh",
	}
	n2012["new jersey nets"] = []string{
		"Keith Bogans",
		"MarShon Brooks",
		"Andre Emmett",
		"Jordan Farmar",
		"Sundiata Gaines",
		"Gerald Green",
		"Dennis Horner",
		"Kris Humphries",
		"Damion James",
		"Armon Johnson",
		"Brook Lopez",
		"Anthony Morrow",
		"Mehmet Okur",
		"Larry Owens",
		"Johan Petro",
		"Jerry Smith",
		"DeShawn Stevenson",
		"Gerald Wallace",
		"Deron Williams",
		"Jordan Williams",
		"Shawne Williams",
		"Shelden Williams",
	}
	n2012["oklahoma city thunder"] = []string{
		"Cole Aldrich",
		"Nick",
		"Daequan",
		"Kevin Durant",
		"Derek Fisher",
		"James Harden",
		"Lazar Hayward",
		"Serge Ibaka",
		"Royal Ivey",
		"Reggie Jackson",
		"Eric Maynor",
		"Nazr Mohammed",
		"Kendrick Perkins",
		"Ryan Reid",
		"Thabo Sefolosha",
		"Russell Westbrook",
	}
	n2012["denver nuggets"] = []string{
		"Chris Andersen",
		"Corey Brewer",
		"DeMarre",
		"Wilson",
		"Kenneth Faried",
		"Danilo Gallinari",
		"Jordan Hamilton",
		"Al Harrington",
		"Kosta Koufos",
		"Ty Lawson",
		"JaVale McGee",
		"Andre Miller",
		"Timofey Mozgov",
		"Julyan Stone",
	}
	n2012["utha jazz"] = []string{
		"Blake Ahearn",
		"Raja Bell",
		"Alec Burks",
		"DeMarre",
		"Jeremy Evans",
		"Derrick Favors",
		"Enes Freedom",
		"Devin Harris",
		"Gordon Hayward",
		"Josh Howard",
		"Al Jefferson",
		"C.J. Miles",
		"Paul Millsap",
		"Jamaal Tinsley",
		"Earl Watson",
	}
	n2012["porland trail blazers"] = []string{
		"LaMarcus Aldridge",
		"Luke Babbitt",
		"Nicolas Batum",
		"Marcus",
		"Jamal",
		"Raymond Felton",
		"Jonny Flynn",
		"J.J. Hickson",
		"Armon Johnson",
		"Chris Johnson",
		"Wesley Matthews",
		"Joel Przybilla",
		"Craig Smith",
		"Nolan Smith",
		"Hasheem Thabeet",
		"Kurt Thomas",
		"Gerald Wallace",
		"Elliot Williams",
	}
	n2012["minnesota timberwolves"] = []string{
		"J.J. Barea",
		"Michael Beasley",
		"Wayne Ellington",
		"Wesley Johnson",
		"Malcolm Lee",
		"Kevin Love",
		"Brad Miller",
		"Anthony Randolph",
		"Luke Ridnour",
		"Ricky Rubio",
		"Anthony Tolliver",
		"Martell Webster",
		"Derrick Williams",
	}
	n2012["chicago bulls"] = []string{
		"Carlos Boozer",
		"Ronnie Brewer",
		"Jimmy Butler",
		"Luol Deng",
		"Taj Gibson",
		"Richard Hamilton",
		"Mike James",
		"Kyle Korver",
		"John Lucas III",
		"Joakim Noah",
		"Derrick Rose",
		"Brian Scalabrine",
		"C.J. Watson",
	}
	n2012["indiana pacers"] = []string{
		"Lou Amundson",
		"Jeff Ayres",
		"Leandro Barbosa",
		"Darren",
		"Kyrylo Fesenko",
		"Jeff Foster",
		"Paul George",
		"Danny Granger",
		"Tyler Hansbrough",
		"Roy Hibbert",
		"George Hill",
		"Dahntay Jones",
		"A.J. Price",
		"Lance Stephenson",
		"David West",
	}
	n2012["milwaukee bucks"] = []string{
		"Andrew Bogut",
		"Jon Brockman",
		"Carlos Delfino",
		"Mike Dunleavy",
		"Monta Ellis",
		"Drew Gooden",
		"Tobias Harris",
		"Darington Hobson",
		"Stephen Jackson",
		"Brandon Jennings",
		"Jon Leuer",
		"Shaun Livingston",
		"Luc Mbah a Moute",
		"Larry Sanders",
		"Ekpe Udoh",
		"Beno Udrih",
	}
	n2012["detroit pistons"] = []string{
		"Will Bynum",
		"Austin Daye",
		"Ben Gordon",
		"Jonas Jerebko",
		"Brandon Knight",
		"Vernon Macklin",
		"Jason Maxiell",
		"Greg Monroe",
		"Tayshaun Prince",
		"Walker Russell",
		"Rodney Stuckey",
		"Charlie Villanueva",
		"Ben Wallace",
		"Damien Wilkins",
	}
	n2012["clevand cavaliers"] = []string{
		"Omri",
		"Semih Erden",
		"Christian Eyenga",
		"Alonzo Gee",
		"Daniel Gibson",
		"Luke Harangody",
		"Manny Harris",
		"Ryan Hollins",
		"Lester Hudson",
		"Kyrie Irving",
		"Antawn Jamison",
		"D.J. Kennedy",
		"Anthony Parker",
		"Samardo Samuels",
		"Ramon Sessions",
		"Donald Sloan",
		"Mychel Thompson",
		"Tristan Thompson",
		"Ben Uzoh",
		"Luke Walton",
	}
	n2012["los angeles lakers"] = []string{
		"Matt Barnes",
		"Steve Blake",
		"Kobe Bryant",
		"Andrew Bynum",
		"Devin Ebanks",
		"Christian Eyenga",
		"Derek Fisher",
		"Pau Gasol",
		"Andrew Goudelock",
		"Jordan Hill",
		"Jason Kapono",
		"Josh McRoberts",
		"Darius Morris",
		"Troy Murphy",
		"Ramon Sessions",
		"Luke Walton",
		"Metta World Peace",
	}
	n2012["los angeles clipers"] = []string{
		"Chauncey Billups",
		"Eric Bledsoe",
		"Caron Butler",
		"Brian",
		"Reggie Evans",
		"Courtney Fortson",
		"Randy Foye",
		"Ryan Gomes",
		"Blake Griffin",
		"Solomon Jones",
		"DeAndre Jordan",
		"Travis Leslie",
		"Kenyon Martin",
		"Chris Paul",
		"Bobby Simmons",
		"Trey Thompkins",
		"Mo Williams",
		"Nick Young",
	}
	n2012["pheonix suns"] = []string{
		"Shannon Brown",
		"Josh",
		"Jared Dudley",
		"Channing Frye",
		"Marcin Gortat",
		"Grant Hill",
		"Robin Lopez",
		"Markieff Morris",
		"Steve Nash",
		"Ronnie Price",
		"Michael Redd",
		"Sebastian Telfair",
		"Hakim Warrick",
	}
	n2012["golden state warriors"] = []string{
		"Earl Barron",
		"Keith Benson",
		"Kwame Brown",
		"Stephen",
		"Monta Ellis",
		"Mickell Gladness",
		"Richard Jefferson",
		"Charles Jenkins",
		"David Lee",
		"Dominic McGuire",
		"Mikki Moore",
		"Nate Robinson",
		"Brandon Rush",
		"Ish Smith",
		"Klay Thompson",
		"Jeremy Tyler",
		"Ekpe Udoh",
		"Chris Wright",
		"Dorell Wright",
	}
	n2012["sacramento kings"] = []string{
		"DeMarcus",
		"Tyreke Evans",
		"Jimmer Fredette",
		"Chuck Hayes",
		"J.J. Hickson",
		"Tyler Honeycutt",
		"Travis Outlaw",
		"John Salmons",
		"Isaiah Thomas",
		"Jason Thompson",
		"Marcus Thornton",
		"Hassan Whiteside",
		"Terrence Williams",
	}
	n2012["miami heat"] = []string{
		"Joel Anthony",
		"Shane Battier",
		"Chris Bosh",
		"Mario",
		"Norris",
		"Eddy",
		"Mickell Gladness",
		"Terrel Harris",
		"Udonis Haslem",
		"Juwan Howard",
		"LeBron James",
		"James Jones",
		"Mike Miller",
		"Dexter Pittman",
		"Ronny Turiaf",
		"Dwyane Wade",
	}
	n2012["atlanta hawks"] = []string{
		"Jason",
		"Erick Dampier",
		"Willie Green",
		"Kirk Hinrich",
		"Al Horford",
		"Ivan Johnson",
		"Joe Johnson",
		"Tracy McGrady",
		"Zaza Pachulia",
		"Jannero Pargo",
		"Donald Sloan",
		"Josh Smith",
		"Jerry Stackhouse",
		"Jeff Teague",
		"Marvin Williams",
	}
	n2012["orlando magic"] = []string{
		"Ryan Anderson",
		"Earl",
		"Glen Davis",
		"Chris Duhon",
		"Justin Harper",
		"Dwight Howard",
		"Larry Hughes",
		"DeAndre Liggins",
		"Jameer Nelson",
		"Daniel Orton",
		"JJ Redick",
		"Jason Richardson",
		"Quentin Richardson",
		"Ish Smith",
		"Von Wafer",
	}
	n2012["washington wizards"] = []string{
		"Morris Almond",
		"Andray Blatche",
		"Trevor Booker",
		"Brian",
		"Jordan",
		"Maurice Evans",
		"Rashard Lewis",
		"Shelvin Mack",
		"Cartier Martin",
		"Roger Mason",
		"JaVale McGee",
		"Hamady N'Diaye",
		"Chris Singleton",
		"James Singleton",
		"Ronny Turiaf",
		"Edwin Ubiles",
		"John Wall",
		"Nick Young",
	}
	n2012["charlotte bobcats"] = []string{
		"D.J. Augustin",
		"Bismack Biyombo",
		"Derrick Brown",
		"Matt",
		"Boris Diaw",
		"DeSagana Diop",
		"Gerald Henderson",
		"Cory Higgins",
		"Corey Maggette",
		"Jamario Moon",
		"Byron Mullens",
		"Tyrus Thomas",
		"Kemba Walker",
		"D.J. White",
		"Reggie Williams",
	}
	n2012["san antonio spurs"] = []string{
		"James Anderson",
		"DeJuan Blair",
		"Matt Bonner",
		"Derrick Byars",
		"Eric Dawson",
		"Justin Dentmon",
		"Boris Diaw",
		"Ike Diogu",
		"Tim Duncan",
		"T.J. Ford",
		"Danny Green",
		"Stephen Jackson",
		"Richard Jefferson",
		"Cory Joseph",
		"Kawhi Leonard",
		"Patty Mills",
		"Gary Neal",
		"Tony Parker",
		"Tiago Splitter",
		"Malcolm Thomas",
	}
	n2012["memphis grizzlies"] = []string{
		"Tony Allen",
		"Gilbert Arenas",
		"Mike",
		"Dante",
		"Josh Davis",
		"Marc Gasol",
		"Rudy Gay",
		"Hamed Haddadi",
		"Lester Hudson",
		"O.J. Mayo",
		"Jeremy Pargo",
		"Quincy Pondexter",
		"Zach Randolph",
		"Josh Selby",
		"Brian Skinner",
		"Marreese Speights",
		"Sam Young",
	}
	n2012["dallas mavericks"] = []string{
		"Kelenna Azubuike",
		"Rodrigue Beaubois",
		"Brian",
		"Vince",
		"Brendan Haywood",
		"Yi Jianlian",
		"Dominique Jones",
		"Jason Kidd",
		"Ian Mahinmi",
		"Shawn Marion",
		"Dirk Nowitzki",
		"Lamar Odom",
		"Jason Terry",
		"Delonte West",
		"Sean Williams",
		"Brandan Wright",
	}
	n2012["houston rockets"] = []string{
		"Jeff Adrien",
		"Earl Boykins",
		"Chase Budinger",
		"Marcus",
		"Samuel Dalembert",
		"Jonny Flynn",
		"Courtney Fortson",
		"Jordan Hill",
		"Courtney Lee",
		"Kyle Lowry",
		"Kevin Martin",
		"Marcus Morris",
		"Chandler Parsons",
		"Patrick Patterson",
		"Luis Scola",
		"Greg Smith",
		"Hasheem Thabeet",
		"Terrence Williams",
	}
	n2012["houston rockets"] = []string{
		"Trevor Ariza",
		"Marco Belinelli",
		"Jerome Dyson",
		"Jeff Foote",
		"Eric Gordon",
		"Xavier Henry",
		"Jarrett Jack",
		"Carldell Johnson",
		"Chris Johnson",
		"Trey Johnson",
		"Solomon Jones",
		"Chris Kaman",
		"Carl Landry",
		"Emeka Okafor",
		"Donald Sloan",
		"Jason Smith",
		"DaJuan Summers",
		"Lance Thomas",
		"Darryl Watkins",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA2012Key, SportKey, BasketballKey, n2012, false, false, true)
	return NBA
}

func NBA1991() dataset.SearchSystem_ {
	n1991 := map[string][]string{}
	n1991["boston celtics"] = []string{
		"John Bagley",
		"Kenny Battle",
		"Larry Bird",
		"Dee Brown",
		"Rick Fox",
		"Kevin Gamble",
		"Rickey Green",
		"Joe Kleine",
		"Reggie Lewis",
		"Tony Massenburg",
		"Kevin McHale",
		"Robert Parish",
		"Ed Pinckney",
		"Kevin Pritchard",
		"Larry Robinson",
		"Brian Shaw",
	}
	n1991["new york knicks"] = []string{
		"Greg Anthony",
		"James Donaldson",
		"Patrick Eddie",
		"Patrick Ewing",
		"Mark Jackson",
		"Anthony Mason",
		"Tim McCormick",
		"Xavier McDaniel",
		"Carlton McKinney",
		"Charles Oakley",
		"Brian Quinnett",
		"John Starks",
		"Kiki Vandeweghe",
		"Gerald Wilkins",
	}
	n1991["new jersey nets"] = []string{
		"Rafael Addison",
		"Kenny Anderson",
		"Mookie Blaylock",
		"Sam Bowie",
		"Jud Buechler",
		"Derrick",
		"Chris Dudley",
		"Dave Feitl",
		"Tate George",
		"Doug Lee",
		"Terry Mills",
		"Chris Morris",
	}
	n1991["miami heat"] = []string{
		"Keith Askins",
		"Winston Bennett",
		"Willie Burton",
		"Bimbo",
		"Sherman Douglas",
		"Kevin Edwards",
		"Alec Kessler",
		"Grant Long",
		"John Morton",
		"Alan Ogg",
		"Glen Rice",
		"Rony Seikaly",
		"Brian Shaw",
		"Steve Smith",
		"Jon Sundvold",
	}
	n1991["philadelphia 76ers"] = []string{
		"Ron Anderson",
		"Michael Ansley",
		"Manute Bol",
		"Johnny Dawkins",
		"Armen Gilliam",
		"Greg Grant",
		"Hersey Hawkins",
		"Dave Hoppen",
		"Tharon Mayes",
		"Brian Oliver",
		"Kenny Payne",
		"Jeff Ruland",
		"Charles Shackleford",
		"Mitchell Wiggins",
		"Jayson Williams",
	}
	n1991["washington bullets"] = []string{
		"Michael Adams",
		"Rex Chapman",
		"Ledell Eackles",
		"Pervis Ellison",
		"A.J. English",
		"Greg Foster",
		"Harvey Grant",
		"Tom Hammonds",
		"Charles Jones",
		"Albert King",
		"Ralph Sampson",
		"LaBradford Smith",
		"Larry Stewart",
		"Derek Strong",
		"Andre Turner",
		"David Wingate",
	}
	n1991["orlando magic"] = []string{
		"Mark Acres",
		"Nick Anderson",
		"Anthony Bowie",
		"Terry",
		"Chris",
		"Bison Dele",
		"Sean Higgins",
		"Greg Kite",
		"Jerry Reynolds",
		"Stanley Roberts",
		"Dennis Scott",
		"Scott Skiles",
		"Otis Smith",
		"Stephen Thompson",
		"Jeff Turner",
		"Sam Vincent",
		"Morlon Wiley",
	}
	n1991["utha jazz"] = []string{
		"Isaac Austin",
		"Thurl Bailey",
		"David Benoit",
		"Mike Brown",
		"Tyrone",
		"Corey",
		"Mark Eaton",
		"Blue Edwards",
		"Jeff Malone",
		"Karl Malone",
		"Eric Murdock",
		"Delaney Rudd",
		"John Stockton",
		"Bob Thornton",
	}
	n1991["san antonio spurs"] = []string{
		"Willie Anderson",
		"Steve Bardo",
		"Jud Buechler",
		"Antoine",
		"Tom",
		"Terry",
		"Sean Elliott",
		"Tom Garrick",
		"Sidney Green",
		"Sean Higgins",
		"Avery Johnson",
		"Tony Massenburg",
		"Paul Pressey",
		"David Robinson",
		"Donald Royal",
		"Rod Strickland",
		"Greg Sutton",
		"Trent Tucker",
		"Morlon Wiley",
	}
	n1991["houston rockets"] = []string{
		"Matt Bullard",
		"Sleepy Floyd",
		"Dan Godfread",
		"Gerald Henderson",
		"Carl Herrera",
		"Dave Jamerson",
		"Avery Johnson",
		"Buck Johnson",
		"Vernon Maxwell",
		"Hakeem Olajuwon",
		"Tree Rollins",
		"Kenny Smith",
		"Larry Smith",
		"Otis Thorpe",
		"John Turner",
		"Kennard Winchester",
	}
	n1991["denver nuggets"] = []string{
		"Greg Anderson",
		"Kevin Brooks",
		"Anthony",
		"Walter Davis",
		"Winston Garland",
		"Scott Hastings",
		"Jerome Lane",
		"Marcus Liberty",
		"Todd Lichti",
		"Mark Macon",
		"Dikembe Mutombo",
		"Steve Scheffler",
		"Reggie Williams",
		"Joe Wolf",
	}
	n1991["dallas mavericks"] = []string{
		"Rolando Blackman",
		"Brad Davis",
		"Terry Davis",
		"James Donaldson",
		"Tom Garrick",
		"Derek Harper",
		"Donald Hodge",
		"Brian Howard",
		"Mike Iuzzolino",
		"Fat Lever",
		"Rodney McCray",
		"Tracy Moore",
		"Brian Quinnett",
		"Doug Smith",
		"Randy White",
		"Herb Williams",
	}
	n1991["minnesota timberwolves"] = []string{
		"Randy Breuer",
		"Scott Brooks",
		"Myron Brown",
		"Tony",
		"Tyrone",
		"Tellis Frank",
		"Tom Garrick",
		"Gerald Glass",
		"Luc Longley",
		"Sam Mitchell",
		"Tod Murphy",
		"Mark Randall",
		"Pooh Richardson",
		"Felton Spencer",
		"Doug West",
	}
	n1991["chicago bulls"] = []string{
		"B.J. Armstrong",
		"Bill",
		"Horace Grant",
		"Bob Hansen",
		"Craig Hodges",
		"Dennis Hopson",
		"Michael Jordan",
		"Stacey King",
		"Cliff Levingston",
		"Chuck Nevitt",
		"John Paxson",
		"Will Perdue",
		"Scottie Pippen",
		"Mark Randall",
		"Rory Sparrow",
		"Scott Williams",
	}
	n1991["clevand cavaliers"] = []string{
		"John Battle",
		"Winston Bennett",
		"Terrell Brandon",
		"Chucky Brown",
		"Brad Daugherty",
		"Craig Ehlo",
		"Danny Ferry",
		"Henry James",
		"Steve Kerr",
		"John Morton",
		"Larry Nance",
		"Jimmy Oliver",
		"Bobby Phills",
		"Mark Price",
		"Mike Sanders",
		"Hot Rod Williams",
	}
	n1991["detroit pistons"] = []string{
		"Mark Aguirre",
		"William Bedford",
		"Lance Blanks",
		"Joe Dumars",
		"Gerald Henderson",
		"Bill Laimbeer",
		"Bob McCann",
		"Dennis Rodman",
		"John Salley",
		"Brad Sellers",
		"Charles Thomas",
		"Isiah Thomas",
		"Darrell Walker",
	}
	n1991["indiana pacers"] = []string{
		"Dale Davis",
		"Greg Dreiling",
		"Vern Fleming",
		"Sean Green",
		"Jerome Lane",
		"George McCloud",
		"Reggie Miller",
		"Chuck Person",
		"Mike Sanders",
		"Detlef Schrempf",
		"Rik Smits",
		"LaSalle Thompson",
		"Kenny Williams",
		"Micheal Williams",
		"Randy Wittman",
	}
	n1991["atlanta hawks"] = []string{
		"Maurice",
		"Duane Ferrell",
		"Paul Graham",
		"Jon Koncak",
		"Gary Leonard",
		"Travis Mays",
		"Rodney Monroe",
		"Blair Rasmussen",
		"Rumeal Robinson",
		"Jeff Sanders",
		"Alexander Volkov",
		"Morlon Wiley",
		"Dominique Wilkins",
		"Kevin Willis",
	}
	n1991["milwaukee bucks"] = []string{
		"Frank Brickowski",
		"Lester",
		"Dale Ellis",
		"Jeff Grayer",
		"Steve Henson",
		"Jay Humphries",
		"Larry Krystkowiak",
		"Jerome Lane",
		"Brad Lohaus",
		"Moses Malone",
		"Dave Popson",
		"Fred Roberts",
		"Alvin Robertson",
		"Danny Schayes",
	}
	n1991["charlotte hornets"] = []string{
		"Michael Ansley",
		"Muggsy Bogues",
		"Rex",
		"Dell",
		"Anthony Frederick",
		"Kenny Gattison",
		"Kendall Gill",
		"Mike Gminski",
		"Ron Grandison",
		"Greg Grant",
		"Cedric Hunter",
		"Larry Johnson",
		"Eric Leckner",
		"Kevin Lynch",
		"Tony Massenburg",
		"Johnny Newman",
		"Elliot Perry",
		"J.R. Reid",
	}
	n1991["portland trail blazers"] = []string{
		"Alaa Abdelnaby",
		"Danny Ainge",
		"Mark Bryant",
		"Wayne",
		"Clyde Drexler",
		"Kevin Duckworth",
		"Jerome Kersey",
		"Robert Pack",
		"Terry Porter",
		"Clifford Robinson",
		"Lamont Strothers",
		"Ennis Whatley",
		"Buck Williams",
		"Danny Young",
	}
	n1991["golden state warriors"] = []string{
		"Victor Alexander",
		"Vincent Askew",
		"Kenny Battle",
		"Jud Buechler",
		"Mario Elie",
		"Chris Gatling",
		"Tim Hardaway",
		"Rod Higgins",
		"Tyrone Hill",
		"Jaren Jackson",
		"Alton Lister",
		"Tony Massenburg",
		"Chris Mullin",
		"Billy Owens",
		"Jim Petersen",
		"Mike Smrek",
		"Billy Thompson",
		"Tom Tolbert",
	}
	n1991["phoenix suns"] = []string{
		"Steve Burtt",
		"Cedric",
		"Tom",
		"Jeff Hornacek",
		"Kevin Johnson",
		"Negele Knight",
		"Andrew Lang",
		"Dan Majerle",
		"Jerrod Mustaf",
		"Ed Nealy",
		"Tim Perry",
		"Kurt Rambis",
		"Mark West",
	}
	n1991["seattle supersonics"] = []string{
		"Dana Barros",
		"Benoit Benjamin",
		"Tony Brown",
		"Michael",
		"Marty",
		"Quintin Dailey",
		"Eddie Johnson",
		"Shawn Kemp",
		"Rich King",
		"Bart Kofoed",
		"Derrick McKey",
		"Nate McMillan",
		"Gary Payton",
		"Ricky Pierce",
	}
	n1991["los angeles clippers"] = []string{
		"Lanard",
		"James Edwards",
		"LeRon Ellis",
		"Gary Grant",
		"Ron Harper",
		"Bo Kimble",
		"Danny Manning",
		"Tharon Mayes",
		"Ken Norman",
		"Elliot Perry",
		"Olden Polynice",
		"David Rivers",
		"Doc Rivers",
		"Charles Smith",
		"Loy Vaught",
		"Danny Young",
	}
	n1991["los angeles lakers"] = []string{
		"Chucky Brown",
		"Demetrius",
		"Elden",
		"Vlade Divac",
		"A.C. Green",
		"Jack Haley",
		"Keith Owens",
		"Sam Perkins",
		"Cliff Robinson",
		"Byron Scott",
		"Tony Smith",
		"Rory Sparrow",
		"Terry Teagle",
		"Sedale Threatt",
		"James Worthy",
	}
	n1991["sacramento kings"] = []string{
		"Anthony Bonner",
		"Randy Brown",
		"Duane",
		"Pete",
		"Bob Hansen",
		"Dennis Hopson",
		"Les Jepsen",
		"Jim Les",
		"Mitch Richmond",
		"Steve Scheffler",
		"Dwayne Schintzius",
		"Lionel Simmons",
		"Carl Thomas",
		"Stephen Thompson",
		"Wayman Tisdale",
		"Spud Webb",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA1991Key, SportKey, BasketballKey, n1991, false, false, true)
	return NBA
}

func NBA1992() dataset.SearchSystem_ {
	n1992 := map[string][]string{}
	n1992["new york knicks"] = []string{
		"Eric Anderson",
		"Greg Anthony",
		"Rolando Blackman",
		"Tony",
		"Hubert Davis",
		"Patrick Ewing",
		"Bo Kimble",
		"Anthony Mason",
		"Charles Oakley",
		"Doc Rivers",
		"Charles Smith",
		"John Starks",
		"Herb Williams",
	}
	n1992["boston celtics"] = []string{
		"Alaa Abdelnaby",
		"John Bagley",
		"Kenny Battle",
		"Dee Brown",
		"Sherman Douglas",
		"Rick Fox",
		"Kevin Gamble",
		"Joe Kleine",
		"Bart Kofoed",
		"Reggie Lewis",
		"Xavier McDaniel",
		"Kevin McHale",
		"Robert Parish",
		"Ed Pinckney",
		"Marcus Webb",
		"Lorenzo Williams",
		"Joe Wolf",
	}
	n1992["new jersey nets"] = []string{
		"Rafael Addison",
		"Kenny Anderson",
		"Sam Bowie",
		"Chucky Brown",
		"Maurice",
		"Derrick",
		"Chris Dudley",
		"Tate George",
		"Dave Hoppen",
		"Bernard King",
		"Doug Lee",
		"Rick Mahorn",
		"Chris Morris",
		"Dan O'Sullivan",
		"Rumeal Robinson",
		"Dwayne Schintzius",
		"Jayson Williams",
	}
	n1992["orlando magic"] = []string{
		"Nick Anderson",
		"Anthony Bowie",
		"Terry",
		"Chris",
		"Bison Dele",
		"Litterial Green",
		"Steve Kerr",
		"Greg Kite",
		"Shaquille O'Neal",
		"Donald Royal",
		"Dennis Scott",
		"Scott Skiles",
		"Tom Tolbert",
		"Jeff Turner",
		"Lorenzo Williams",
		"Howard Wright",
	}
	n1992["miami heat"] = []string{
		"Keith Askins",
		"Willie Burton",
		"Bimbo",
		"Kevin Edwards",
		"Matt Geiger",
		"Alec Kessler",
		"Grant Long",
		"Harold Miner",
		"Glen Rice",
		"John Salley",
		"Rony Seikaly",
		"Brian Shaw",
		"Steve Smith",
	}
	n1992["philadelphia 76ers"] = []string{
		"Ron Anderson",
		"Manute Bol",
		"Johnny Dawkins",
		"Armen Gilliam",
		"Greg Grant",
		"Hersey Hawkins",
		"Jeff Hornacek",
		"Thomas Jordan",
		"Andrew Lang",
		"Kenny Payne",
		"Tim Perry",
		"Charles Shackleford",
		"Clarence Weatherspoon",
		"Eddie Lee Wilkins",
	}
	n1992["washington bullets"] = []string{
		"Mark Acres",
		"Michael Adams",
		"Steve Burtt",
		"Rex",
		"Chris",
		"Pervis Ellison",
		"Greg Foster",
		"Harvey Grant",
		"Tom Gugliotta",
		"Byron Irvin",
		"Buck Johnson",
		"Charles Jones",
		"Don MacLean",
		"Alan Ogg",
		"Doug Overton",
		"Brent Price",
		"Larry Robinson",
		"LaBradford Smith",
		"Larry Stewart",
	}
	n1992["chicago bulls"] = []string{
		"B.J. Armstrong",
		"Ricky Blanton",
		"Bill",
		"Joe",
		"Jo Jo English",
		"Horace Grant",
		"Michael Jordan",
		"Stacey King",
		"Rodney McCray",
		"Ed Nealy",
		"John Paxson",
		"Will Perdue",
		"Scottie Pippen",
		"Trent Tucker",
		"Darrell Walker",
		"Corey Williams",
		"Scott Williams",
	}
	n1992["clevand cavaliers"] = []string{
		"John Battle",
		"Terrell Brandon",
		"Brad Daugherty",
		"Craig Ehlo",
		"Danny Ferry",
		"Jay Guidinger",
		"Steve Kerr",
		"Jerome Lane",
		"Larry Nance",
		"Bobby Phills",
		"Mark Price",
		"Mike Sanders",
		"Gerald Wilkins",
		"Hot Rod Williams",
	}
	n1992["charlotte hornets"] = []string{
		"Tony Bennett",
		"Muggsy Bogues",
		"Dell",
		"Kenny Gattison",
		"Kendall Gill",
		"Mike Gminski",
		"Sidney Green",
		"Tom Hammonds",
		"Larry Johnson",
		"Kevin Lynch",
		"Alonzo Mourning",
		"Johnny Newman",
		"J.R. Reid",
		"Lorenzo Williams",
		"David Wingate",
	}
	n1992["atlanta hawks"] = []string{
		"Stacey Augmon",
		"Mookie Blaylock",
		"Randy Breuer",
		"Duane Ferrell",
		"Greg Foster",
		"Paul Graham",
		"Steve Henson",
		"Adam Keefe",
		"Jon Koncak",
		"Travis Mays",
		"Blair Rasmussen",
		"Jeff Sanders",
		"Andre Spencer",
		"Alex Stivrins",
		"Morlon Wiley",
		"Dominique Wilkins",
		"Kevin Willis",
	}
	n1992["indiana pacers"] = []string{
		"Dale Davis",
		"Greg Dreiling",
		"Vern Fleming",
		"Sean Green",
		"George McCloud",
		"Reggie Miller",
		"Sam Mitchell",
		"Pooh Richardson",
		"Detlef Schrempf",
		"Malik Sealy",
		"Rik Smits",
		"LaSalle Thompson",
		"Kenny Williams",
	}
	n1992["detroit pistons"] = []string{
		"Mark Aguirre",
		"Joe Dumars",
		"Gerald Glass",
		"Bill Laimbeer",
		"Terry Mills",
		"Isaiah Morris",
		"Melvin Newbern",
		"Olden Polynice",
		"Mark Randall",
		"Alvin Robertson",
		"Dennis Rodman",
		"Jeff Ruland",
		"Isiah Thomas",
		"Darrell Walker",
		"Orlando Woolridge",
		"Danny Young",
	}
	n1992["milwaukee bucks"] = []string{
		"Alaa Abdelnaby",
		"Anthony Avent",
		"Jon Barry",
		"Frank Brickowski",
		"Todd Day",
		"Blue Edwards",
		"Brad Lohaus",
		"Moses Malone",
		"Lee Mayberry",
		"Eric Murdock",
		"Dan O'Sullivan",
		"Alan Ogg",
		"Anthony Pullard",
		"Fred Roberts",
		"Alvin Robertson",
		"Danny Schayes",
		"Alex Stivrins",
		"Derek Strong",
		"Orlando Woolridge",
	}
	n1992["houston rockets"] = []string{
		"Mark Acres",
		"Scott Brooks",
		"Matt Bullard",
		"Sleepy Floyd",
		"Winston Garland",
		"Carl Herrera",
		"Robert Horry",
		"Vernon Maxwell",
		"Hakeem Olajuwon",
		"Tree Rollins",
		"Kenny Smith",
		"Terry Teagle",
		"Otis Thorpe",
		"Kennard Winchester",
	}
	n1992["san antonio spurs"] = []string{
		"Willie Anderson",
		"William Bedford",
		"Antoine",
		"Terry",
		"Lloyd Daniels",
		"Vinny Del Negro",
		"Sean Elliott",
		"Dale Ellis",
		"Sidney Green",
		"Avery Johnson",
		"Sam Mack",
		"Matt Othick",
		"J.R. Reid",
		"David Robinson",
		"Larry Smith",
		"David Wood",
	}
	n1992["utha jazz"] = []string{
		"Isaac Austin",
		"David Benoit",
		"Mike Brown",
		"Tyrone",
		"John",
		"James Donaldson",
		"Mark Eaton",
		"Stephen Howard",
		"Jay Humphries",
		"Henry James",
		"Larry Krystkowiak",
		"Tim Legler",
		"Jeff Malone",
		"Karl Malone",
		"John Stockton",
	}
	n1992["denver nuggets"] = []string{
		"Kevin Brooks",
		"LaPhonso Ellis",
		"Tom Hammonds",
		"Scott Hastings",
		"Marcus Liberty",
		"Mark Macon",
		"Dikembe Mutombo",
		"Robert Pack",
		"Gary Plummer",
		"Bryant Stith",
		"Robert Werdann",
		"Reggie Williams",
	}
	n1992["minnesota timberwolves"] = []string{
		"Thurl Bailey",
		"Lance Blanks",
		"Gerald Glass",
		"Christian Laettner",
		"Luc Longley",
		"Marlon Maxey",
		"Bob McCann",
		"Chuck Person",
		"Mark Randall",
		"Brad Sellers",
		"Chris Smith",
		"Felton Spencer",
		"Doug West",
		"Micheal Williams",
	}
	n1992["dallas mavericks"] = []string{
		"Steve Bardo",
		"Walter Bond",
		"Dexter",
		"Terry Davis",
		"Derek Harper",
		"Donald Hodge",
		"Brian Howard",
		"Mike Iuzzolino",
		"Jim Jackson",
		"Tim Legler",
		"Tracy Moore",
		"Walter Palmer",
		"Sean Rooks",
		"Doug Smith",
		"Lamont Strothers",
		"Randy White",
		"Morlon Wiley",
	}
	n1992["phoenix suns"] = []string{
		"Danny Ainge",
		"Charles Barkley",
		"Cedric",
		"Tom",
		"Richard Dumas",
		"Frank Johnson",
		"Kevin Johnson",
		"Tim Kempton",
		"Negele Knight",
		"Dan Majerle",
		"Oliver Miller",
		"Jerrod Mustaf",
		"Kurt Rambis",
		"Alex Stivrins",
		"Mark West",
	}
	n1992["seattle supersonics"] = []string{
		"Vincent Askew",
		"Dana Barros",
		"Benoit Benjamin",
		"Michael",
		"Eddie Johnson",
		"Shawn Kemp",
		"Rich King",
		"Derrick McKey",
		"Nate McMillan",
		"Gerald Paddio",
		"Gary Payton",
		"Sam Perkins",
		"Ricky Pierce",
		"Steve Scheffler",
	}
	n1992["portland trail blazers"] = []string{
		"Mark Bryant",
		"Clyde Drexler",
		"Kevin Duckworth",
		"Mario Elie",
		"Dave Johnson",
		"Jerome Kersey",
		"Tracy Murray",
		"Terry Porter",
		"Clifford Robinson",
		"Delaney Rudd",
		"Reggie Smith",
		"Rod Strickland",
		"Buck Williams",
		"Joe Wolf",
	}
	n1992["los angeles clippers"] = []string{
		"Gary Grant",
		"Ron Harper",
		"Jaren Jackson",
		"Mark Jackson",
		"Danny Manning",
		"Ken Norman",
		"Stanley Roberts",
		"Elmore Spencer",
		"Alex Stivrins",
		"Kiki Vandeweghe",
		"Loy Vaught",
		"Duane Washington",
		"John Williams",
		"Randy Woods",
	}
	n1992["los angeles lakers"] = []string{
		"Benoit Benjamin",
		"Alex Blackwell",
		"Elden",
		"Doug",
		"Duane",
		"Vlade Divac",
		"James Edwards",
		"A.C. Green",
		"Anthony Peeler",
		"Byron Scott",
		"Tony Smith",
		"Sedale Threatt",
		"James Worthy",
	}
	n1992["golden state warriors"] = []string{
		"Victor Alexander",
		"Jud Buechler",
		"Joe",
		"Pat Durham",
		"Chris Gatling",
		"Jeff Grayer",
		"Tim Hardaway",
		"Sean Higgins",
		"Tyrone Hill",
		"Byron Houston",
		"Keith Jennings",
		"Alton Lister",
		"Chris Mullin",
		"Ed Nealy",
		"Billy Owens",
		"Paul Pressey",
		"Andre Spencer",
		"Latrell Sprewell",
		"Barry Stevens",
	}
	n1992["sacramento kings"] = []string{
		"Vincent Askew",
		"Anthony Bonner",
		"Randy Brown",
		"Duane",
		"Pete",
		"Marty",
		"Rod Higgins",
		"Henry James",
		"Stan Kimbrough",
		"Jim Les",
		"Kurt Rambis",
		"Mitch Richmond",
		"Lionel Simmons",
		"Wayman Tisdale",
		"Spud Webb",
		"Walt Williams",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA1992Key, SportKey, BasketballKey, n1992, false, false, true)
	return NBA
}

func NBA1996Olympics() dataset.SearchSystem_ {
	n := map[string][]string{}
	n["united states"] = []string{
		"Charles Barkley",
		"David Robinson",
		"Gary Payton",
		"Hakeem Olajuwon",
		"John Stockton",
		"Karl Malone",
		"Mitch Richmond",
		"Penny Hardaway",
		"Reggie Miller",
		"Scottie Pippen",
		"Shaquille O'Neal",
		"Grant Hill",
	}
	n["serbia and montenegro"] = []string{
		"Aleksander Djordjevic",
		"Dejan Bodiroga",
		"Dejan Tomasevic",
		"Milenko Topic",
		"Nikola Loncar",
		"Predrag Danilovic",
		"Sasa Obradovic",
		"Vlade Divac",
		"Zarko Paspalj",
		"Zeljko Rebraca",
		"Miroslav Beric",
		"Zoran Savic",
	}
	n["australia"] = []string{
		"Andrew Gaze",
		"Andrew Vlahov",
		"John Dorge",
		"Mark Bradtke",
		"Scott Fisher",
		"Shane Heal",
		"Tony Ronaldson",
		"Brett Maher",
		"Pat Reidy",
		"Ray Borner",
		"Sam MacKinnon",
		"Tonny Jensen",
	}
	n["greece"] = []string{
		"Dimitrios Papanikolaou",
		"Dinos Agelidis",
		"Efthimios Rentzias",
		"Efthymios Bakatsias",
		"Fanis Khristodoulou",
		"Fragiskos Alvertis",
		"Giorgos Sigalas",
		"Kostas Patavoukas",
		"Lefteris Kakiousis",
		"Nikolaos Oikonomou",
		"Panagiotis Fasoulas",
		"Panagiotis Giannakis",
	}
	n["lithuania"] = []string{
		"Arturas Karnisovas",
		"Arvydas Sabonis",
		"Darius Lukminas",
		"Gintaras Einikis",
		"Mindaugas Zukauskas",
		"Rimas Kurtinaitis",
		"Sarunas Marciulionis",
		"Saulius Stombergas",
		"Eurelijus Zukauskas",
		"Rytis Vaisvila",
		"Tomas Pacesas",
	}
	n["argentina"] = []string{
		"Daniel Farabello",
		"Diego Osella",
		"Ernesto Michel",
		"Esteban Perez",
		"Fabricio Oberto",
		"Juan Espil",
		"Luis Villar",
		"Marcelo Milanesio",
		"Jorge Racca",
		"Esteban de la Fuente",
		"Marcelo Nicola",
		"Ruben Wolkowyski",
	}
	n["croatia"] = []string{
		"Damir Mulaomerovic",
		"Davor Marcelic",
		"Dino Radja",
		"Josip Jerko Vrankovic",
		"Slaven Rimac",
		"Stojan Vrankovic",
		"Toni Kukoc",
		"Vladan Alanovic",
		"Zan Tabak",
		"Velimir Perasovic",
		"Arijan Komazec",
		"Veljko Mrsic",
	}
	n["brazil"] = []string{
		"Caio",
		"Demétrius Conrado Ferraciú",
		"Janjao",
		"Josuel dos Santos",
		"Olívia",
		"Oscar Schmidt",
		"Pipoka",
		"Ratto",
		"Rogério",
		"Wilson Minucci",
		"Caio da Silveira",
		"Tonico",
	}
	n["puetro rico"] = []string{
		"Carmelo Travieso",
		"Daniel Santiago",
		"Eddie Rivera",
		"Edgar Padilla",
		"Eugenio Soto",
		"Georgie Torres",
		"Jerome Mincy",
		"Joel Curbelo",
		"Pablo Alicea",
		"Piculin Ortiz",
		"Ramon Rivas",
		"Richard Soto",
	}
	n["china"] = []string{
		"Bateer Mengke",
		"Gong Xiaobin",
		"Hu Weidong",
		"Li Xiaoyong",
		"Liu Yudong",
		"Sun Jun",
		"Wu Naiqun",
		"Wu Qinglong",
		"Zheng Wu",
		"Wang Zhizhi",
		"Li Nan",
		"Shan Tao",
	}
	n["angola"] = []string{
		"Angelo Victoriano",
		"Anibal Moreira",
		"Benjamim Ucuahamba",
		"David Dias",
		"Herlander Coimbra",
		"Honorato Trosso",
		"Jose Carlos Guimaraes",
		"Justino Victoriano",
		"Victor de Carvalho",
		"Benjamim Joao Romano",
		"Edmar Victoriano",
	}
	n["south korea"] = []string{
		"Gang Dong-Hui",
		"Hyeon Ju-Yeop",
		"Hee-Chul Chun",
		"Jeong Jae-Geun",
		"Jo Dong-Gi",
		"Lee Sang-Min",
		"Mun Gyeong-Eun",
		"Yang Hui-Seung",
		"Hur Jae",
		"Kyung-Ho Chung",
		"O Seong-Sik",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA1996OKey, SportKey, BasketballKey, n, false, false, true)
	return NBA
}

func NBA2000Olympics() dataset.SearchSystem_ {
	n := map[string][]string{}
	n["united states"] = []string{
		"Allan Houston",
		"Alonzo Mourning",
		"Antonio McDyess",
		"Gary Payton",
		"Jason Kidd",
		"Kevin Garnett",
		"Ray Allen",
		"Shareef Abdur-Rahim",
		"Steve Smith",
		"Tim Hardaway",
		"Vin Baker",
		"Vince Carter",
	}
	n["canada"] = []string{
		"Andrew Mavis",
		"David Daniels",
		"Eric Hinrichsen",
		"Greg Francis",
		"Greg Newton",
		"Michael Meeks",
		"Peter Guarasci",
		"Shawn Swords",
		"Sherman Hamilton",
		"Steve Nash",
		"Todd MacCulloch",
		"Rowan Barrett",
	}
	n["lithuania"] = []string{
		"Darius Maskoliunas",
		"Darius Songaila",
		"Eurelijus Zukauskas",
		"Gintaras Einikis",
		"Mindaugas Timinskas",
		"Ramunas Siskauskas",
		"Sarunas Jasikevicius",
		"Saulius Stombergas",
		"Tomas Masiulis",
		"Andrius Giedraitis",
		"Dainius Adomaitis",
		"Kestutis Marciulonis",
	}
	n["itlay"] = []string{
		"Alessandro Abbio",
		"Andrea Meneghin",
		"Denis Marconato",
		"German Scarone",
		"Giacomo Galanda",
		"Gianluca Basile",
		"Gregor Fucka",
		"Marcelo Damiao",
		"Michele Mian",
		"Roberto Chiacig",
		"Agostino Li Vecchi",
		"Carlton Myers",
	}
	n["serbia and montenegro"] = []string{
		"Dejan Bodiroga",
		"Dejan Tomasevic",
		"Dragan Lukovski",
		"Dragan Tarlac",
		"Igor Rakocevic",
		"Nikola Jestratijevic",
		"Peja Stojakovic",
		"Predrag Drobnjak",
		"Sasa Obradovic",
		"Zeljko Rebraca",
		"Predrag Danilovic",
		"Vlado Scepanovic",
	}
	n["australia"] = []string{
		"Andrew Gaze",
		"Andrew Vlahov",
		"Chris Anstey",
		"Jason Smith",
		"Mark Bradtke",
		"Paul Rogers",
		"Ricky Grace",
		"Sam MacKinnon",
		"Shane Heal",
		"Luc Longley",
		"Brett Maher",
		"Martin Cattalini",
	}
	n["france"] = []string{
		"Antoine Rigaudeau",
		"Crawford Palmer",
		"Cyril Julian",
		"Frederic Weis",
		"Jim Bilba",
		"Laurent Foirest",
		"Laurent Sciarra",
		"Makan Dioumassi",
		"Moustapha Sonko",
		"Stephane Risacher",
		"Thierry Gadou",
		"Yann Bonato",
	}
	n["russia"] = []string{
		"Alexandr Bashminov",
		"Andrei Fetisov",
		"Andrei Kirilenko",
		"Evgeny Pashutin",
		"Nikita Morgunov",
		"Ruslan Avleev",
		"Sergei Chikalkin",
		"Sergey Bazarevitch",
		"Sergey Panov",
		"Zakhar Pashutin",
		"Eugeny Kisurin",
		"Valentin Kubrakov",
	}
	n["china"] = []string{
		"Bateer Mengke",
		"Guo Shiqiang",
		"Hu Weidong",
		"Li Nan",
		"Li Qun",
		"Li Xiaoyong",
		"Liu Yudong",
		"Sun Jun",
		"Yao Ming",
		"Zhang Jinsong",
		"Zheng Wu",
		"Wang Zhizhi",
	}
	n["spain"] = []string{
		"Alberto Angulo",
		"Alberto Herreros",
		"Alfonso Reyes",
		"Carlos Jimenez",
		"Ignacio De Miguel",
		"Ignacio Rodriguez",
		"Johnny Rogers",
		"Jorge Garbajosa",
		"Juan Carlos Navarro",
		"Raul Lopez",
		"Roberto Duenas",
		"Rodrigo De La Fuente",
	}
	n["new zealand"] = []string{
		"Brad Riley",
		"Kirk Penney",
		"Mark Dickel",
		"Nenad Vucinic",
		"Paul Henare",
		"Pero Cameron",
		"Peter Pokai",
		"Phill Jones",
		"Ralph Lattimore",
		"Rob Hickey",
		"Sean Marks",
		"Tony Rampton",
	}
	n["angola"] = []string{
		"Angelo Victoriano",
		"Anibal Moreira",
		"Belarmino Chipongue",
		"Carlos Almeida",
		"David Dias",
		"Edmar Victoriano",
		"Garcia Domingos",
		"Miguel Lutonda",
		"Victor de Carvalho",
		"Victor Muzadi",
		"Buila Katiavala",
		"Herlander Coimbra",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA2000OKey, SportKey, BasketballKey, n, false, false, true)
	return NBA
}

func NBA2004Olympics() dataset.SearchSystem_ {
	n := map[string][]string{}
	n["spain"] = []string{
		"Carlos Jimenez",
		"Felipe Reyes",
		"Iker Iturbe",
		"Jaume Comas",
		"Jorge Garbajosa",
		"Jose Calderon",
		"Juan Carlos Navarro",
		"Oscar Yebra",
		"Pau Gasol",
		"Roberto Duenas",
		"Rodrigo De La Fuente",
		"Rudy Fernández",
	}
	n["argentina"] = []string{
		"Alejandro Montecchia",
		"Andres Nocioni",
		"Carlos Delfino",
		"Gabriel Fernandez",
		"Hugo Sconochini",
		"Luis Scola",
		"Manu Ginobili",
		"Pepe Sanchez",
		"Ruben Wolkowyski",
		"Fabricio Oberto",
		"Leo Gutierrez",
		"Walter Herrmann",
	}
	n["lithuania"] = []string{
		"Arvydas Macijauskas",
		"Darius Songaila",
		"Eurelijus Zukauskas",
		"Ksistof Lavrinovic",
		"Mindaugas Zukauskas",
		"Ramunas Siskauskas",
		"Robertas Javtokas",
		"Sarunas Jasikevicius",
		"Saulius Stombergas",
		"Vidas Ginevicius",
		"Dainius Salenga",
		"Donatas Slanina",
	}
	n["itlay"] = []string{
		"Alex Righetti",
		"Denis Marconato",
		"Giacomo Galanda",
		"Gianluca Basile",
		"Gianmarco Pozzecco",
		"Luca Garri",
		"Massimo Bulleri",
		"Matteo Soragna",
		"Nikola Radulovic",
		"Roberto Chiacig",
		"Rodolfo Rombaldoni",
		"Michele Mian",
	}
	n["united states"] = []string{
		"Allen Iverson",
		"Amare Stoudemire",
		"Carlos Boozer",
		"Carmelo Anthony",
		"Dwyane Wade",
		"Lamar Odom",
		"LeBron James",
		"Richard Jefferson",
		"Shawn Marion",
		"Stephon Marbury",
		"Tim Duncan",
		"Emeka Okafor",
	}
	n["greece"] = []string{
		"Dimitrios Papanikolaou",
		"Dimitris Diamantidis",
		"Fragiskos Alvertis",
		"Kostas Tsartsaris",
		"Lazaros Papadopoulos",
		"Michalis Kakiouzis",
		"Nikos Hatzivrettas",
		"Nikos Zisis",
		"Theodoros Papaloukas",
		"Vassilis Spanoulis",
		"Antonis Fotsis",
		"Dimos Dikoudis",
	}
	n["puetro rico"] = []string{
		"Bobby Joe Hatton",
		"Carlos Arroyo",
		"Daniel Santiago",
		"Eddie Casiano",
		"Larry Ayuso",
		"Piculin Ortiz",
		"Rolando Hourruitiner",
		"Sharif Fajardo",
		"Christian Dalmau",
		"Jorge Rivera",
		"Rick Apodaca",
	}
	n["australia"] = []string{
		"Andrew Bogut",
		"Brett Maher",
		"CJ Bruton",
		"David Andersen",
		"Glen Saville",
		"Jason Smith",
		"John Rillie",
		"Martin Cattalini",
		"Matt Nielsen",
		"Paul Rogers",
		"Shane Heal",
		"Tony Ronaldson",
	}
	n["serbia and montenegro"] = []string{
		"Dejan Bodiroga",
		"Djuro Ostojic",
		"Igor Rakocevic",
		"Milos Vujanic",
		"Nenad Krstic",
		"Petar Popovic",
		"Predrag Drobnjak",
		"Sasha Pavlovic",
		"Vlado Scepanovic",
		"Vule Avdalovic",
		"Dejan Tomasevic",
		"Vladimir Radmanovic",
	}
	n["china"] = []string{
		"Bateer Mengke",
		"Chen Ke",
		"Du Feng",
		"Zhu Fangyu",
		"Guo Shiqiang",
		"Yi Jianlian",
		"Mo Ke",
		"Li Nan",
		"Wei Liu",
		"Yao Ming",
		"Zhang Jinsong",
		"Zhang Yunsong",
	}
	n["new zealand"] = []string{
		"Aaron Olson",
		"Craig Bradshaw",
		"Dillon Boucher",
		"Ed Book",
		"Kirk Penney",
		"Mark Dickel",
		"Paul Henare",
		"Paul Winitana",
		"Pero Cameron",
		"Phill Jones",
		"Sean Marks",
		"Tony Rampton",
	}
	n["angola"] = []string{
		"Abdel Moussa",
		"Angelo Victoriano",
		"Carlos Almeida",
		"Eduardo Mingas",
		"Joaquim Gomes",
		"Olimpio Cipriano",
		"Valter Monteiro",
		"Victor Muzadi",
		"Walter Costa",
		"Edmar Victoriano",
		"Miguel Lutonda",
		"Victor de Carvalho",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA2004OKey, SportKey, BasketballKey, n, false, false, true)
	return NBA
}

func NBA2008Olympics() dataset.SearchSystem_ {
	n := map[string][]string{}
	n["united states"] = []string{
		"Carlos Boozer",
		"Carmelo Anthony",
		"Chris Bosh",
		"Chris Paul",
		"Deron Williams",
		"Dwight Howard",
		"Dwyane Wade",
		"Jason Kidd",
		"Kobe Bryant",
		"LeBron James",
		"Michael Redd",
		"Tayshaun Prince",
	}
	n["argentina"] = []string{
		"Andres Nocioni",
		"Antonio Porta",
		"Carlos Delfino",
		"Fabricio Oberto",
		"Juan Gutierrez",
		"Leo Gutierrez",
		"Luis Scola",
		"Pablo Prigioni",
		"Paulo Quinteros",
		"Roman Gonzalez",
		"Federico Kammerichs",
		"Manu Ginobili",
	}
	n["spain"] = []string{
		"Alex Mumbru",
		"Berni Rodriguez",
		"Carlos Jimenez",
		"Felipe Reyes",
		"Jorge Garbajosa",
		"Juan Carlos Navarro",
		"Marc Gasol",
		"Pau Gasol",
		"Raul Lopez",
		"Ricky Rubio",
		"Rudy Fernández",
		"Jose Calderon",
	}
	n["lithuania"] = []string{
		"Jonas Maciulis",
		"Ksistof Lavrinovic",
		"Linas Kleiza",
		"Marijonas Petravicius",
		"Mindaugas Lukauskis",
		"Ramunas Siskauskas",
		"Rimantas Kaukenas",
		"Robertas Javtokas",
		"Sarunas Jasikevicius",
		"Simas Jasaitis",
		"Darjus Lavrinovic",
		"Marius Prekevicius",
	}
	n["australia"] = []string{
		"Andrew Bogut",
		"Brad Newley",
		"Chris Anstey",
		"CJ Bruton",
		"David Andersen",
		"David Barlow",
		"Glen Saville",
		"Joe Ingles",
		"Mark Worthington",
		"Matt Nielsen",
		"Patty Mills",
		"Shawn Redhage",
	}
	n["croatia"] = []string{
		"Damjan Rudez",
		"Davor Kus",
		"Kresimir Loncar",
		"Marin Rozic",
		"Marko Banic",
		"Marko Popovic",
		"Marko Tomas",
		"Nikola Prkacin",
		"Roko Ukic",
		"Sandro Nicevic",
		"Stanko Barac",
		"Zoran Planinic",
	}
	n["greece"] = []string{
		"Andreas Glyniadakis",
		"Antonis Fotsis",
		"Dimitris Diamantidis",
		"Giorgos Printezis",
		"Kostas Tsartsaris",
		"Michalis Pelekanos",
		"Nikos Zisis",
		"Panagiotis Vasilopoulos",
		"Sofoklis Schortsanitis",
		"Theodoros Papaloukas",
		"Vassilis Spanoulis",
		"Ioannis Bourousis",
	}
	n["china"] = []string{
		"Du Feng",
		"Zhu Fangyu",
		"Chen Jianghua",
		"Yi Jianlian",
		"Wang Lei",
		"Li Nan",
		"Zhang Qingpeng",
		"Wang Shipeng",
		"Sun Yue",
		"Wei Liu",
		"Yao Ming",
		"Wang Zhizhi",
	}
	n["russia"] = []string{
		"Alexey Savrasenko",
		"Andrei Kirilenko",
		"Andrey Vorontsevich",
		"JR Holden",
		"Nikita Morgunov",
		"Petr Samoylenko",
		"Sergei Monia",
		"Sergey Bykov",
		"Viktor Keirou",
		"Viktor Khryapa",
		"Vitaly Fridzon",
		"Zakhar Pashutin",
	}
	n["germany"] = []string{
		"Chris Kaman",
		"Demond Greene",
		"Dirk Nowitzki",
		"Jan Jagla",
		"Konrad Wysocki",
		"Pascal Roller",
		"Patrick Femerling",
		"Phillip Zwiener",
		"Robert Garrett",
		"Steffen Hamann",
		"Sven Schultze",
		"Tim Ohlbrecht",
	}
	n["iran"] = []string{
		"Ali Doraghi",
		"Amir Amini",
		"Hamed Afagh",
		"Hamed Haddadi",
		"Hamed Sohrabnejad",
		"Iman Zandi",
		"Javad Davari",
		"Mahdi Kamrany",
		"Moosa Nabipoor",
		"Oshin Sahakian",
		"Saeid Davarpanah",
		"Samad Nik Bahrami",
	}
	n["angola"] = []string{
		"Abdel Moussa",
		"Armando Costa",
		"Carlos Almeida",
		"Carlos Morais",
		"Eduardo Mingas",
		"Felizardo Ambrosio",
		"Joaquim Gomes",
		"Leonel Paulo",
		"Luis Costa",
		"Milton Barros",
		"Olimpio Cipriano",
		"Vladimir Jeronimo",
	}
	NBA := dataset.SearchSystem_{}
	NBA.Constructor()
	NBA.Include(NBA2008OKey, SportKey, BasketballKey, n, false, false, true)
	return NBA
}

func BuildBasketball() BasketballParcel {
	n1991, n1992, n1996, n2000, n2004, n2008, n2011, n2012 := NBA1991(), NBA1992(), NBA1996Olympics(), NBA2000Olympics(), NBA2004Olympics(), NBA2008Olympics(), NBA2011(), NBA2011()

	ne1991, nc1991, nf1991, nb1991, ni1991 := n1991.Manager(NBA1991Key)
	ne1992, nc1992, nf1992, nb1992, ni1992 := n1992.Manager(NBA1992Key)
	ne1996, nc1996, nf1996, nb1996, ni1996 := n1996.Manager(NBA1996OKey)
	ne2000, nc2000, nf2000, nb2000, ni2000 := n2000.Manager(NBA2000OKey)
	ne2004, nc2004, nf2004, nb2004, ni2004 := n2004.Manager(NBA2004OKey)
	ne2008, nc2008, nf2008, nb2008, ni2008 := n2008.Manager(NBA2008OKey)
	ne2011, nc2011, nf2011, nb2011, ni2011 := n2011.Manager(NBA2011Key)
	ne2012, nc2012, nf2012, nb2012, ni2012 := n2012.Manager(NBA2012Key)

	parcel1 := SportsParcel{Event: ne1991, Category: nc1991, Field: nf1991, Book: nb1991, MappedItems: ni1991}
	parcel2 := SportsParcel{Event: ne1992, Category: nc1992, Field: nf1992, Book: nb1992, MappedItems: ni1992}
	parcel3 := SportsParcel{Event: ne1996, Category: nc1996, Field: nf1996, Book: nb1996, MappedItems: ni1996}
	parcel4 := SportsParcel{Event: ne2000, Category: nc2000, Field: nf2000, Book: nb2000, MappedItems: ni2000}
	parcel5 := SportsParcel{Event: ne2004, Category: nc2004, Field: nf2004, Book: nb2004, MappedItems: ni2004}
	parcel6 := SportsParcel{Event: ne2008, Category: nc2008, Field: nf2008, Book: nb2008, MappedItems: ni2008}
	parcel7 := SportsParcel{Event: ne2011, Category: nc2011, Field: nf2011, Book: nb2011, MappedItems: ni2011}
	parcel8 := SportsParcel{Event: ne2012, Category: nc2012, Field: nf2012, Book: nb2012, MappedItems: ni2012}

	ready := []SportsParcel{parcel1, parcel2, parcel3, parcel4, parcel5, parcel6, parcel7, parcel8}
	pack := BasketballParcel{Pack: ready}
	return pack
}

func BasketballEvents() []string {
	events := []string{}
	openBuild := BuildBasketball()
	for _, event := range openBuild.Pack {
		events = append(events, event.Event)
	}
	return events
}

func BasketballCategory() string {
	category := []string{}
	token := BuildBasketball().Pack
	for _, cat := range token {
		category = append(category, cat.Category)
	}
	category = dataset.EraseDuplicate(category)
	cat := category[0]
	fmt.Println(category)
	return cat
}

func BasketballBook() string {
	fi := ""
	token := BuildBasketball().Pack
	for _, cat := range token {
		fi = cat.Book
	}
	return fi
}

func BasketballLists() []string {
	ma := []string{}
	token := BuildBasketball().Pack
	for _, t := range token {
		for items := range t.MappedItems {
			ma = append(ma, items)
		}
	}
	return ma
}

func BasketballSheet() map[string][]string {
	sheet := map[string][]string{}
	token := BuildBasketball().Pack
	for _, t := range token {
		maps.Copy(sheet, t.MappedItems)
	}
	return sheet
}
