package update

import (
	"maps"
	"nyg/dataset"
)

type FootballParcel struct {
	Pack []SportsParcel
}

// keys
const (
	FIFAWC2002Key = "FIFA WORLD CUP 2002"
	FIFAWC2006Key = "FIFA WORLD CUP 2006"

	FIFAWC2010Key = "FIFA WORLD CUP 2010"
	FIFAWC2014Key = "FIFA WORLD CUP 2014"

	Laliga2009Key        = "LALIGA 2009"
	PremierLeague2012Key = "PREMIER LEAGUE 2012"
	SeriaA2014Key        = "SERIA-A 2014"

	FootballKey = "FOOTBALL"
)

func FIFAWC2002() dataset.SearchSystem_ {
	f := map[string][]string{}
	f["denmark"] = []string{
		"Thomas Sorensen",
		"Stig Tofting",
		"Rene Henriksen",
		"Martin Laursen",
		"Heintze",
		"Thomas Helveg",
		"Thomas Gravesen",
		"Jesper Gronkjaer",
		"Jon Dahl Tomasson",
		"Martin Jorgensen",
		"Ebbe Sand",
		"Niclas Jensen",
		"Steven Lüstü",
		"Claus Jensen",
		"Michaelsen",
		"Peter Kjaer",
		"Christian Poulsen",
		"Peter Lovenkrands",
		"Dennis Rommedahl",
		"Kasper Bogelund",
		"Peter Madsen",
		"Jesper Christiansen",
		"Brian Steen Nielsen",
	}
	f["senegal"] = []string{
		"Tony Sylva",
		"Omar Daf",
		"Papa Sarr",
		"Papa Malick",
		"Alassane N'Dour",
		"Aliou Cisse",
		"Henri Camara",
		"Amara Traore",
		"Souleymane Camara",
		"Khalilou Fadiga",
		"El Hadji",
		"Ay Faye",
		"Lamine Diatta",
		"Moussa N'Diaye",
		"Salif Diao",
		"Omar Diallo",
		"Ferdinand Coly",
		"Pape Thiaw",
		"Papa Bouba",
		"Sylvain N'Diaye",
		"Habib Beye",
		"Kalidou Cissokho",
		"Makthar N'Diaye",
	}
	f["uruguay"] = []string{
		"Fabian Carini ",
		"Gustavo Mendez",
		"Alejandro Lembo",
		"Paolo Montero",
		"Pablo Garcia",
		"Dario Rodriguez",
		"Gianni Guigou",
		"Gustavo Varela",
		"Dario Silva",
		"Fabian O'Neil",
		"Federico Magallanes ",
		"Gustavo Munua",
		"Sebastian Abreu ",
		"Gonzalo Sorondo ",
		"Nicolas Olivera ",
		"Marcelo Romero",
		"Mario Regueiro ",
		"Richard Morales",
		"Joe Bizera ",
		"Alvaro Recoba ",
		"Diego Forlan",
		"Gonzalo de los Santos ",
		"Federico Elduayen Peñarol",
	}
	f["france"] = []string{
		"Ulrich Rame",
		"Vincent Candela",
		"Bixente Lizarazu",
		"Patrick Vieira",
		"Philippe Christanval",
		"Youri Djorkaeff",
		"Claude Makelele",
		"Marcel Desailly",
		"Djibril Cisse",
		"Zinedine Zidane",
		"Sylvain Wiltord",
		"Thierry Henry",
		"Mikael Silvestre",
		"Alain Boghossian",
		"Lilian Thuram",
		"Fabien Barthez",
		"Emmanuel Petit",
		"Frank Leboeuf",
		"Willy Sagnol",
		"David Trezeguet",
		"Christophe Dugarry ",
		"Johan Micoud Parma",
		"Gregory Coupet Lyon",
	}
	f["spanish"] = []string{
		"Iker CASILLAS",
		"Cristobal CURRO TORRES",
		"JUAN FRANcisco Garcia",
		"Ivan HELGUERA",
		"Carles PUYOL",
		"Fernando HIERRO",
		"RAUL Gonzalez Blanco",
		"Ruben BARAJA",
		"Fernando MORIENTES",
		"Diego TRISTAN",
		"Francisco DE PEDRO",
		"Alberto LUQUE",
		"RICARDO Lopez Felipe",
		"David ALBELDA Aliques",
		"Enrique ROMERO",
		"Gaizka MENDIETA",
		"Juan Carlos VALERON",
		"SERGIO Gonzalez Soriano",
		"XAVI Hernandez",
		"Miguel Angel NADAL",
		"LUIS ENRIQUE",
		"JOAQUIN Sanchez",
		"Pedro CONTRERAS",
	}
	f["paraguay"] = []string{
		"Jose Luis Chilavert",
		"Francisco Arce",
		"Pedro Sarabia",
		"Carlos Gamarra",
		"Celso Ayala",
		"Estanislao Struway",
		"Richart Baez",
		"Guido Alvarenga",
		"Roque Santa Cruz",
		"Roberto Acuña",
		"Jorge Campos",
		"Justo Villar",
		"Carlos Paredes",
		"Diego Gavilan",
		"Carlos Bonet",
		"Gustavo Morinigo",
		"Juan Carlos Franco",
		"Julio Cesar Caceres",
		"Daniel Sanabria",
		"Jose Cardozo",
		"Denis Caniza",
		"Ricardo Tavarelli",
		"Nelson Cuevas",
	}
	f["south africa"] = []string{
		"Hans Vonk",
		"Cyril Nzama",
		"Bradley Carnell",
		"Aaron Mokoena",
		"Jacob Lekgetho",
		"MacBeth Sibaya",
		"Quinton Fortune",
		"Thabo Mngomeni",
		"MacDonald Mukasi",
		"Bennett Mnguni",
		"Jabu Pule",
		"Teboho Mokoena",
		"Pierre Issa",
		"Siyabonga Nomvethe",
		"Sibusiso Zuma",
		"Andre Arendse",
		"Benedict McCarthy",
		"Delron Buckley",
		"Lucas Radebe",
		"Calvin Marlin",
		"Steven Pienaar",
		"Thabang Molefe",
		"George Koumantarakis",
	}
	f["slovenia"] = []string{
		"Marko Simeunovic",
		"Goran Sankovic",
		"Zeljko Milinovic",
		"Muamer Vugdalic",
		"Marinko Galic",
		"Aleksander Knavs",
		"Doni Novak",
		"Ales Ceh",
		"Milan Osterc",
		"Zlatko Zahovic",
		"Miran Pavlin",
		"Mladen Dabanovic",
		"Mladen Rudonja",
		"Sasa Gajser",
		"Rajko Tavcar",
		"Senad Tiganj",
		"Zoran Pavlovic",
		"Milenko Acimovic",
		"Amir Karic",
		"Nastja Ceh",
		"Sebastjan Cimirotic",
		"Dejan Nemec",
		"Spasoje Bulajic",
	}
	f["brazil"] = []string{
		"MARCOS Silveira Reis",
		"Marcos de Moraes CAFU",
		"LUCIO da Silva Ferreira",
		"Jose Vitor ROQUE JUNIOR",
		"EDMILSON Gomes de Moraes",
		"ROBERTO CARLOS da Silva",
		"RICARDINHO Rodrigues",
		"GILBERTO SILVA",
		"RONALDO Nazario de Lima",
		"RIVALDO Barbosa Ferreira",
		"RONALDINHO Moreira",
		"Nelson DIDA",
		"Juliano Haus BELLETTI",
		"ANDERSON POLGA",
		"Jose KLEBERSON Pereira",
		"JUNIOR Angelo de Souza",
		"DENILSON de Oliveira",
		"Marcos dos Santos VAMPETA",
		"Oswaldo JUNINHO PAULISTA",
		"EDILSON da Silva Ferreira",
		"LUIZAO Carlos Goulart",
		"ROGERIO CENI",
		"KAKA dos Santos Leite",
	}
	f["south korea"] = []string{
		"Won-Jae Lee",
		"Young-Min Hyun",
		"Sung-Yong Choi",
		"Jin-Cheul Choi",
		"Nam-Il Kim",
		"Sang-Chul Yoo",
		"Tae-Young Kim",
		"Tae-Uk Choi",
		"Ki-Hyeon Seol",
		"Young-Pyo Lee",
		"Yong-Soo Choi",
		"Byung-Ji Kim",
		"Eul-Yong Lee",
		"Chun-Soo Lee",
		"Min-Sung Lee",
		"Du-Ri Cha",
		"Jong-Hwan Yoon",
		"Seon-Hong Hwang",
		"Jung-Hwan Ahn",
		"Myung-Bo Hong",
		"Ji-Sung Park",
		"Chong-Gug Song",
		"Eun-Sung Choi",
	}
	f["united states"] = []string{
		"Brad Friedel",
		"Frank Hejduk",
		"Gregg Berhalter",
		"Pablo Mastroeni",
		"John O'Brien",
		"David Regis",
		"Eddie Lewis",
		"Earnie Stewart",
		"Joe-Max Moore",
		"Claudio Reyna",
		"Clint Mathis",
		"Jeff Agoos",
		"Cobi Jones",
		"Steve Cherundolo",
		"Josh Wolff",
		"Carlos Llamosa",
		"DaMarcus Beasley",
		"Kasey Keller",
		"Tony Meola",
		"Brian McBride",
		"Landon Donovan",
		"Tony Sanneh",
		"Eddie Pope",
	}
	f["portugal"] = []string{
		"Manuel VITOR BAIA",
		"JORGE COSTA",
		"ABEL XAVIER",
		"Marco Antonio CANEIRA",
		"Silva FERNANDO COUTO",
		"PAULO SOUSA",
		"LUIS FIGO",
		"Manuel JOAO PINTO",
		"Pedro PAULETA",
		"Manuel RUI COSTA",
		"SERGIO CONCEICAO",
		"HUGO VIANA",
		"JORGE ANDRADE",
		"PEDRO BARBOSA",
		"Alexandre NELSON",
		"RICARDO Pereira",
		"Jorge PAULO BENTO",
		"Nuno FRECHAUT",
		"Nuno Fernando CAPUCHO",
		"Armando Teixeira PETIT",
		"Ribeiro NUNO GOMES",
		"Roberto Luis BETO",
		"RUI JORGE de Sousa",
	}
	f["poland"] = []string{
		"Jerzy Dudek",
		"Tomasz Klos",
		"Jacek Zielinski",
		"Michal Zewlakow",
		"Tomasz Rzasa",
		"Tomasz Hajto",
		"Piotr Swierczewski",
		"Cezary Kucharski",
		"Pawel Kryszalowicz",
		"Radoslaw Kaluzny",
		"Emmanuel Olisadebe",
		"Radoslaw Majdan",
		"Arkadiusz Glowacki",
		"Marcin Zewlakow",
		"Tomasz Waldoch",
		"Maciej Murawski",
		"Arkadiusz Bak",
		"Jacek Krzynowek",
		"Maciej Zurawski",
		"Jacek Bak",
		"Marek Kozminski",
		"Adam Matysek",
		"Pawel Sibik",
	}
	f["germany"] = []string{
		"Oliver Kahn",
		"Thomas Linke",
		"Marko Rehmer",
		"Frank Baumann",
		"Carsten Ramelow",
		"Christian Ziege",
		"Oliver Neuville",
		"Dietmar Hamann",
		"Carsten Jancker",
		"Lars Ricken",
		"Miroslav Klose",
		"Jens Lehmann",
		"Michael Ballack",
		"Gerald Asamoah",
		"Sebastian Kehl",
		"Jens Jeremies",
		"Marco Bode",
		"Jörg Böhme",
		"Bernd Schneider",
		"Oliver Bierhoff",
		"Christoph Metzelder",
		"Torsten Frings",
		"Hans-Jörg Butt",
	}
	f["republic of ireland"] = []string{
		"Shay Given",
		"Steve Finnan",
		"Ian Harte",
		"Kenny Cunningham",
		"Steve Staunton",
		"Roy Keane",
		"Jason McAteer",
		"Matt Holland",
		"Damien Duff",
		"Robbie Keane",
		"Kevin Kilbane",
		"Mark Kinsella",
		"David Connolly",
		"Gary Breen",
		"Richard Dunne",
		"Dean Kiely",
		"Niall Quinn",
		"Gary Kelly",
		"Clinton Morrison",
		"Andy O'Brien",
		"Steven Reid",
		"Lee Carsley",
		"Alan Kelly",
	}
	f["cameroon"] = []string{
		"Alioum Boukar",
		"Bill Tchato",
		"Pierre Wome",
		"Rigobert Song",
		"Raymond Kalla N'Kongo",
		"Pierre Njanka",
		"Joseph N'Do",
		"GEREMI",
		"Samuel Eto'o",
		"Patrick M'Boma",
		"Pius N'Diefi",
		"Lauren Etame-Mayer",
		"Lucien Mettomo",
		"Joel Epalle",
		"Nicolas Alnoudji",
		"Jacques Songo'o",
		"Marc-Vivien Foe",
		"Patrick Suffo",
		"Eric Djemba-Djemba",
		"Salomon Olembe",
		"Joseph-Desire Job",
		"Idriss Kameni",
		"Daniel N'Gom Kome",
	}
	f["saudi arabia"] = []string{
		"Mohammed Al-Deayea",
		"Mohammed Al-Jahani",
		"Redha Tukar",
		"Abdullah Zebermawi",
		"Mohsin Harthi",
		"Fouzi Al-Shehri",
		"Ibrahim Al-Shahrani",
		"Mohammed Noor",
		"Sami Al-Jaber",
		"Mohammad Al-Shlhoub",
		"Obeid Al-Dosari",
		"Ahmed Al-Dosari",
		"Hussain Sulimani",
		"Abdulaziz Khathran",
		"Abdullah Al-Dosary",
		"Khamis Al-Owairan",
		"Abdullah Al-Shahrani",
		"Nawaf Al-Temiyat",
		"Omar Al-Ghamdi",
		"Al Hasan Al-Yami",
		"Mabrouk Zaid",
		"Mohammed Babkr",
		"Mansour Al-Thagafi",
	}
	f["sweaden"] = []string{
		"Magnus Hedman",
		"Olof Mellberg",
		"Patrik Andersson",
		"Johan Mjällby",
		"Michael Svensson",
		"Tobias Linderoth",
		"Niclas Alexandersson",
		"Anders Svensson",
		"Fredrik Ljungberg",
		"Marcus Allbäck",
		"Henrik Larsson",
		"Magnus Kihlstedt",
		"Tomas Antonelius",
		"Erik Edman",
		"Andreas Jakobsson",
		"Teddy Lucic",
		"Magnus Svensson",
		"Mattias Jonson",
		"Pontus Farnerud",
		"Daniel Andersson",
		"Zlatan Ibrahimovic",
		"Andreas Andersson",
		"Andreas Isaksson",
	}
	f["england"] = []string{
		"David Seaman",
		"Danny Mills",
		"Ashley Cole",
		"Trevor Sinclair",
		"Rio Ferdinand",
		"Sol Campbell",
		"David Beckham",
		"Paul Scholes",
		"Robbie Fowler",
		"Michael Owen",
		"Emile Heskey",
		"Wes Brown",
		"Nigel Martyn",
		"Wayne Bridge",
		"Martin Keown",
		"Gareth Southgate",
		"Teddy Sheringham",
		"Owen Hargreaves",
		"Joe Cole",
		"Darius Vassell",
		"Nicky Butt",
		"David James",
		"Kieron Dyer",
	}
	f["argentina"] = []string{
		"German Burgos",
		"Roberto Ayala",
		"Juan Sorin",
		"Mauricio Pochettino",
		"Matias Almeyda",
		"Walter Samuel",
		"Claudio Lopez",
		"Javier Zanetti",
		"Gabriel Batistuta",
		"Ariel Ortega",
		"Juan Veron",
		"Pablo Cavallero",
		"Diego Placente",
		"Diego Simeone",
		"Claudio Husain",
		"Pablo Aimar",
		"Gustavo Lopez",
		"Kily Gonzalez",
		"Hernan Crespo",
		"Marcelo Gallardo",
		"Claudio Caniggia",
		"Jose Chamot",
		"Roberto Bonano",
	}
	f["nigeria"] = []string{
		"Ike Shorunmu",
		"Joseph Yobo",
		"Celestine Babayaro",
		"Nwankwo Kanu",
		"Isaac Okoronkwo",
		"Taribo West",
		"Pius Ikedia",
		"Mutiu Adepoju",
		"Bartholomew Ogbeche",
		"Augustine Okocha",
		"Garba Lawal",
		"Austin Ejide",
		"Rabiu Afolabi",
		"Ifeanyi Udeze",
		"Justice Christopher",
		"Efetobore Sodje",
		"Julius Aghahowa",
		"Benedict Akwuegbu",
		"Eric Ejiofor",
		"James Obiorah",
		"John Utaka",
		"Vincent Enyeama",
		"Femi Opabunmi",
	}
	f["mexico"] = []string{
		"Oscar Perez",
		"Francisco Gabriel De Anda",
		"Rafael Garcia",
		"Rafael Marquez",
		"Manuel Vidrio",
		"Gerardo Torrado",
		"Ramon Morales",
		"Alberto Garcia Aspe",
		"Jared Borgetti",
		"Cuauhtemoc Blanco",
		"Braulio Luna",
		"Oswaldo Sanchez",
		"Sigifredo Mercado",
		"German Villa",
		"Luis Hernandez",
		"Salvador Carmona",
		"Francisco Palencia",
		"Joahan Rodriguez",
		"Gabriel Caballero",
		"Melvin Brown",
		"Jesus Arellano",
		"Alberto Rodriguez",
		"Jorge Campos",
	}
	f["itlay"] = []string{
		"Gianluigi Buffon",
		"Christian Panucci",
		"Paolo Maldini",
		"Francesco Coco",
		"Fabio Cannavaro",
		"Cristiano Zanetti",
		"Alessandro Del Piero",
		"Gennaro Gattuso",
		"Filippo Inzaghi",
		"Francesco Totti",
		"Cristiano Doni",
		"Christian Abbiati",
		"Alessandro Nesta",
		"Luigi Di Biagio",
		"Mark Iuliano",
		"Angelo Di Livio",
		"Damiano Tommasi",
		"Marco Delvecchio",
		"Gianluca Zambrotta",
		"Vincenzo Montella",
		"Christian Vieri",
		"Francesco Toldo",
		"Marco Materazzi",
	}
	f["croatia"] = []string{
		"Stipe Pletikosa",
		"Anthony Seric",
		"Josip Simunic",
		"Stjepan Tomas",
		"Milan Rapaic",
		"Boris Zivkovic",
		"Davor Vugrinec",
		"Robert Prosinecki",
		"Davor Suker",
		"Niko Kovac",
		"Alen Boksic",
		"Tomislav Butina",
		"Mario Stanic",
		"Zvonimir Soldo",
		"Daniel Saric",
		"Jurica Vranjes",
		"Robert Jarni",
		"Ivica Olic",
		"Goran Vlaovic",
		"Dario Simic",
		"Robert Kovac",
		"Bosko Balaban",
		"Vladimir Vasilj",
	}
	f["ecuador"] = []string{
		"Jose Cevallos",
		"Augusto Poroso",
		"Ivan Hurtado",
		"Ulises de la Cruz",
		"Alfonso Obregon",
		"Raul Guerron",
		"Nicolas Asencio",
		"Luis Gomez",
		"Ivan Kaviedes",
		"Alex Aguinaga",
		"Agustin Delgado",
		"Oswaldo Ibarra",
		"Angel Fernandez",
		"Juan Carlos Burbano",
		"Marlon Ayovi",
		"Clever Chala",
		"Giovanny Espinoza",
		"Carlos Tenorio",
		"Edison Mendez",
		"Edwin Tenorio",
		"Wellington Sanchez",
		"Daniel Viteri",
		"Walter Ayovi",
	}
	f["japan"] = []string{
		"Yoshikatsu Kawaguchi",
		"Yutaka Akita",
		"Naoki Matsuda",
		"Ryuzo Morioka",
		"Junichi Inamoto",
		"Toshihiro Hattori",
		"Hidetoshi Nakata",
		"Hiroaki Morishima",
		"Akinori Nishizawa",
		"Masashi Nakayama",
		"Takayuki Suzuki",
		"Seigo Narazaki",
		"Atsushi Yanagisawa",
		"Alessandro Santos",
		"Takashi Fukunishi",
		"Koji Nakata",
		"Tsuneyasu Miyamoto",
		"Shinji Ono",
		"Mitsuo Ogasawara",
		"Tomokazu Myojin",
		"Kazuyuki Toda",
		"Daisuke Ichikawa",
		"Hitoshi Sogahata",
	}
	f["belgium"] = []string{
		"Geert de Vlieger",
		"Eric Deflandre",
		"Glen de Boeck",
		"Eric van Meir",
		"Nico van Kerckhoven",
		"Timmy Simons",
		"Marc Wilmots",
		"Bart Goor",
		"Wesley Sonck",
		"Johan Walem",
		"Gert Verheyen",
		"Peter van der Heyden",
		"Franky Vandendriessche",
		"Sven Vermant",
		"Jacky Peeters",
		"Daniel van Buyten",
		"Gaetan Englebert",
		"Yves Vanderhaeghe",
		"Bernd Thijs",
		"Branko Strupar",
		"Danny Boffin",
		"Mbo Mpenza",
		"Frederic Herpoel",
	}
	f["russia"] = []string{
		"Ruslan Nigmatullin",
		"Yuri Kovtun",
		"Yuri Nikiforov",
		"Alexei Smertin",
		"Andrei Solomatin",
		"Igor Semshov",
		"Viktor Onopko",
		"Valeri Karpin",
		"Egor Titov",
		"Alexandre Mostovoi",
		"Vladimir Bestchastnykh",
		"Stanislav Cherchesov",
		"Viatcheslav Daev",
		"Igor Chugainov",
		"Dmitry Alenichev",
		"Alexander Kerzhakov",
		"Sergey Semak",
		"Dmitry Sennikov",
		"Ruslan Pimenov",
		"Marat Izmailov",
		"Dmitry Khokhlov",
		"Dmitry Sychev",
		"Alexander Filimonov",
	}
	f["tunisia"] = []string{
		"Ali Boumnijel",
		"Khaled Badra",
		"Zoubele Baya",
		"Mohamed Mkacher",
		"Ziad Jaziri",
		"Hatem Trabelsi",
		"Imed Mhadhbi",
		"Hassen Gabsi",
		"Riyadh Jelassi",
		"Kaies Ghodhbane",
		"Adel Sellimi",
		"Raouf Bouzaiene",
		"Riyadh Bouazizi",
		"Hamdi Marzouki",
		"Radhi Jaidi",
		"Hassen Bejaoui",
		"Tarek Thabet",
		"Slim Ben Achour",
		"Emir Mkademi",
		"Ali Zitouni",
		"Mourad Melki",
		"Ahmed Jaouachi",
		"Jose Clayton",
	}
	F := dataset.SearchSystem_{}
	F.Constructor() // important
	F.Include(FIFAWC2002Key, SportKey, FootballKey, f, true, false, false)
	return F
}

func FIFAWC2006() dataset.SearchSystem_ {
	f := map[string][]string{}
	f["germany"] = []string{
		"Jens Lehmann",
		"Marcell Jansen",
		"Arne Friedrich",
		"Robert Huth",
		"Sebastian Kehl",
		"Jens Nowotny",
		"Bastian Schweinsteiger",
		"Torsten Frings",
		"Mike Hanke",
		"Oliver Neuville",
		"Miroslav Klose",
		"Oliver Kahn",
		"Michael Ballack",
		"Gerald Asamoah",
		"Thomas Hitzlsperger",
		"Philipp Lahm",
		"Per Mertesacker",
		"Tim Borowski",
		"Bernd Schneider",
		"Lukas Podolski",
		"Christoph Metzelder",
		"David Odonkor",
		"Timo Hildebrand",
	}
	f["poland"] = []string{
		"Artur Boruc",
		"Mariusz Jop",
		"Seweryn Gancarczyk",
		"Marcin Baszczynski",
		"Kamil Kosowski",
		"Jacek Bak",
		"Radoslaw Sobolewski",
		"Jacek Krzynowek",
		"Maciej Zurawski",
		"Miroslav Szymkowiak",
		"Grzegorz Rasiak",
		"Tomasz Kuszczak",
		"Sebastian Mila",
		"Michal Zewlakow",
		"Euzebiusz Smolarek",
		"Arkadiusz Radomski",
		"Dariusz Dudka",
		"Mariusz Lewandowski",
		"Bartosz Bosacki",
		"Piotr Giza",
		"Ireneusz Jelen",
		"Lukasz Fabianski",
		"Pawel Brozek",
	}
	f["ecuador"] = []string{
		"Edwin Villafuerte",
		"Jorge Guagua",
		"Ivan Hurtado",
		"Ulises de la Cruz",
		"Jose Perlaza",
		"Patricio Urrutia",
		"Christian Lara",
		"Edison Mendez",
		"Felix Borja",
		"Ivan Kaviedes",
		"Agustin Delgado",
		"Cristian Mora",
		"Paul Ambrossi",
		"Segundo Castillo",
		"Marlon Ayovi",
		"Luis Valencia",
		"Giovanny Espinoza",
		"Neicer Reasco",
		"Luis Saritama",
		"Edwin Tenorio",
		"Carlos Tenorio",
		"Damian Lanza",
		"Christian Benitez",
	}
	f["costa rica"] = []string{
		"Alvaro Mesen",
		"Jervis Drummond",
		"Luis Marin",
		"Michael Umana",
		"Gilberto Martinez",
		"Danny Fonseca",
		"Christian Bolanos",
		"Mauricio Solis",
		"Paulo Wanchope",
		"Walter Centeno",
		"Ronald Gomez",
		"Leonardo Gonzalez",
		"Kurt Bernard",
		"Randall Azofeifa",
		"Harold Wallace",
		"Carlos Hernandez",
		"Gabriel Badilla",
		"Jose Porras",
		"Alvaro Saborio",
		"Douglas Sequeira",
		"Victor Nunez",
		"Michael Rodriguez",
		"Wardy Alfaro",
	}
	f["england"] = []string{
		"Paul Robinson",
		"Gary Neville",
		"Ashley Cole",
		"Steven Gerrard",
		"Rio Ferdinand",
		"John Terry",
		"David Beckham",
		"Frank Lampard",
		"Wayne Rooney",
		"Michael Owen",
		"Joe Cole",
		"Sol Campbell",
		"David James",
		"Wayne Bridge",
		"Jamie Carragher",
		"Owen Hargreaves",
		"Jermaine Jenas",
		"Michael Carrick",
		"Aaron Lennon",
		"Stewart Downing",
		"Peter Crouch",
		"Scott Carson",
		"Theo Walcott",
	}
	f["sweden"] = []string{
		"Andreas Isaksson",
		"Mikael Nilsson",
		"Olof Mellberg",
		"Teddy Lucic",
		"Erik Edman",
		"Tobias Linderoth",
		"Niclas Alexandersson",
		"Anders Svensson",
		"Fredrik Ljungberg",
		"Zlatan Ibrahimovic",
		"Henrik Larsson",
		"John Alvbåge",
		"Petter Hansson",
		"Fredrik Stenman",
		"Karl Svensson",
		"Kim Källström",
		"Johan Elmander",
		"Mattias Jonson",
		"Daniel Andersson",
		"Marcus Allbäck",
		"Christian Wilhelmsson",
		"Markus Rosenberg",
		"Rami Shaaban",
	}
	f["paraguay"] = []string{
		"Justo Villar",
		"Jorge Nunez",
		"Delio Toledo",
		"Carlos Gamarra",
		"Julio Cesar Caceres",
		"Carlos Bonet",
		"Salvador Cabanas",
		"Edgar Barreto",
		"Roque Santa Cruz",
		"Roberto Acuña",
		"Diego Gavilan",
		"Derlis Gomez",
		"Carlos Paredes",
		"Paulo Da Silva",
		"Julio Manzur",
		"Cristian Riveros",
		"Jose Montiel",
		"Nelson Valdez",
		"Julio Dos Santos",
		"Dante Lopez",
		"Denis Caniza",
		"Aldo Bobadilla",
		"Nelson Cuevas",
	}
	f["tirindad and tobago"] = []string{
		"Shaka Hislop",
		"Ian Cox",
		"Avery John",
		"Marvin Andrews",
		"Brent Sancho",
		"Dennis Lawrence",
		"Christopher Birchall",
		"Cyd Gray",
		"Aurtis Whitley",
		"Russell Latapy",
		"Carlos Edwards",
		"Collin Samuel",
		"Cornell Glen",
		"Stern John",
		"Kenwyne Jones",
		"Evans Wise",
		"Atiba Charles",
		"Densill Theobald",
		"Dwight Yorke",
		"Jason Scotland",
		"Kelvin Jack",
		"Clayton Ince",
		"Anthony Wolfe",
	}
	f["argentina"] = []string{
		"Roberto Abbondanzieri",
		"Roberto Ayala",
		"Juan Sorin",
		"Fabricio Coloccini",
		"Esteban Cambiasso",
		"Gabriel Heinze",
		"Javier Saviola",
		"Javier Mascherano",
		"Hernan Crespo",
		"Juan Riquelme",
		"Carlos Tevez",
		"Leonardo Franco",
		"Lionel Scaloni",
		"Rodrigo Palacio",
		"Gabriel Milito",
		"Pablo Aimar",
		"Leandro Cufre",
		"Maximiliano Rodriguez",
		"Lionel Messi",
		"Julio Cruz",
		"Nicolas Burdisso",
		"Luis Gonzalez",
		"Oscar Ustari",
	}
	f["netherland"] = []string{
		"Edwin van der Sar",
		"Kew Jaliens",
		"Khalid Boulahrouz",
		"Joris Mathijsen",
		"Giovanni van Bronckhorst",
		"Denny Landzaat",
		"Dirk Kuijt",
		"Phillip Cocu",
		"Ruud van Nistelrooij",
		"Rafael van der Vaart",
		"Arjen Robben",
		"Jan Kromkamp",
		"Andre Ooijer",
		"John Heitinga",
		"Tim de Cler",
		"Hedwiges Maduro",
		"Robin van Persie",
		"Mark van Bommel",
		"Jan Vennegoor of Hesselink",
		"Wesley Sneijder",
		"Ryan Babel",
		"Henk Timmer",
		"Maarten Stekelenburg",
	}
	f["serbia and montenegro"] = []string{
		"Dragoslav Jevric",
		"Ivan Ergic",
		"Ivica Dragutinovic",
		"Igor Duljaj",
		"Nemanja Vidic",
		"Goran Gavrancic",
		"Ognjen Koroman",
		"Mateja Kezman",
		"Savo Milosevic",
		"Dejan Stankovic",
		"Predrag Djordjevic",
		"Oliver Kovacevic",
		"Dusan Basta",
		"Nenad Djordjevic",
		"Milan Dudic",
		"Dusan Petkovic",
		"Albert Nadj",
		"Zvonimir Vukic",
		"Nikola Zigic",
		"Mladen Krstajic",
		"Danijel Ljuboja",
		"Sasa Ilic",
		"Vladimir Stojkovic",
	}
	f["cote d'ivoire"] = []string{
		"Jean-Jacques Tizie",
		"Kanga Akale",
		"Arthur Boka",
		"Kolo Toure",
		"Didier Zokora",
		"Blaise Kouassi",
		"Emerse Fae",
		"Bonaventure Kalou",
		"Arouna Kone",
		"Gilles Yapi-Yapo",
		"Didier Drogba",
		"Abdoulaye Meite",
		"Marc Zoro",
		"Bakary Kone",
		"Aruna Dindane",
		"Gerard Gnanhouan",
		"Cyrille Domoraud",
		"Kader Keita",
		"Yaya Toure",
		"Guy Demel",
		"Emmanuel Eboue",
		"Romaric N'Dri",
		"Boubacar Barry",
	}
	f["mexico"] = []string{
		"Oswaldo Sanchez",
		"Claudio Suarez",
		"Carlos Salcido",
		"Rafael Marquez",
		"Ricardo Osorio",
		"Gerardo Torrado",
		"Antonio Naelson ZINHA",
		"Pavel Pardo",
		"Jared Borgetti",
		"Guillermo Franco",
		"Ramon Morales",
		"Jose Corona",
		"Guillermo Ochoa",
		"Gonzalo Pineda",
		"Jose Antonio Castro",
		"Mario Mendez",
		"Jose Francisco Fonseca",
		"Andres Guardado",
		"Omar Bravo",
		"Rafael Garcia",
		"Jesus Arellano",
		"Francisco Rodriguez",
		"Luis Perez",
	}
	f["portugal"] = []string{
		"RICARDO Pereira",
		"PAULO FERREIRA",
		"Marco Antonio CANEIRA",
		"RICARDO COSTA",
		"FERNANDO MEIRA",
		"Francisco Jose COSTINHA",
		"LUIS FIGO",
		"Armando Teixeira PETIT",
		"Pedro PAULETA",
		"HUGO VIANA",
		"SIMAO Sabrosa",
		"JoaQUIM Sampaio Silva",
		"Luis MIGUEL Monteiro",
		"NUNO VALENTE",
		"Luis BOA MORTE",
		"RICARDO CARVALHO",
		"CRISTIANO RONALDO",
		"Nuno Ribeiro MANICHE",
		"TIAGO Cardoso Mendes",
		"DECO Luiz de Sousa",
		"Ribeiro NUNO GOMES",
		"PAULO SANTOS",
		"HELDER POSTIGA",
	}
	f["iran"] = []string{
		"Ebrahim Mirzapour",
		"Mehdi Mahdavikia",
		"Sohrab Bakhtiarizadeh",
		"Yahya Golmohammadi",
		"Rahman Rezaei",
		"Javad Nekounam",
		"Ferydoon Zandi",
		"Ali Karimi",
		"Vahid Hashemian",
		"Ali Daei",
		"Rasoul Khatibi",
		"Hassan Roudbarian",
		"Hossein Kaabi",
		"Andranik Teymourian",
		"Arash Borhani",
		"Reza Enayati",
		"Javad Kazemeian",
		"Moharram Navidkia",
		"Amir Hossein Sadeqi",
		"Mohammad Nosrati",
		"Mehrzad Madanchi",
		"Vahid Talebloo",
		"Masoud Shojaei",
	}
	f["angola"] = []string{
		"JOAO RICARDO",
		"Marcos AIROSA",
		"Joao Pereira JAMBA",
		"Antonio LEBO LEBO",
		"Carlos Alonso KALI",
		"Marcos Joaquim MILOY",
		"Paulo FIGUEIREDO",
		"ANDRE Macanga",
		"Pedro MANTORRAS",
		"Fabrice Maieco AKWA",
		"MATEUS",
		"Joao Mamona LAMA",
		"EDSON de Jesus Nobre",
		"Antonio MENDONCA",
		"RUI MARQUES",
		"FLAVIO da Silva Amado",
		"Nsimba ZE KALANGA",
		"Arsenio Cabungula LOVE",
		"Andre TITI BUENGO",
		"Manuel Cange LOCO",
		"Luis Manuel DELGADO",
		"MARIO",
		"MARCO ABREU",
	}
	f["itlay"] = []string{
		"Gianluigi Buffon",
		"Cristian Zaccardo",
		"Fabio Grosso",
		"Daniele De Rossi",
		"Fabio Cannavaro",
		"Andrea Barzagli",
		"Alessandro Del Piero",
		"Gennaro Gattuso",
		"Luca Toni",
		"Francesco Totti",
		"Alberto Gilardino",
		"Angelo Peruzzi",
		"Alessandro Nesta",
		"Marco Amelia",
		"Vincenzo Iaquinta",
		"Mauro Camoranesi",
		"Simone Barone",
		"Filippo Inzaghi",
		"Gianluca Zambrotta",
		"Simone Perrotta",
		"Andrea Pirlo",
		"Massimo Oddo",
		"Marco Materazzi",
	}
	f["czech republic"] = []string{
		"Petr Cech",
		"Zdenek Grygera",
		"Pavel Mares",
		"Tomas Galasek",
		"Radoslav Kovac",
		"Marek Jankulovski",
		"Libor Sionko",
		"Karel Poborsky",
		"Jan Koller",
		"Tomas Rosicky",
		"Pavel Nedved",
		"Vratislav Lokvenc",
		"Martin Jiranek",
		"David Jarolim",
		"Milan Baros",
		"Jaromir Blazek",
		"Jiri Stajner",
		"Marek Heinz",
		"Jan Polak",
		"Jaroslav Plasil",
		"Tomas Ujfalusi",
		"David Rozehnal",
		"Antonin Kinsky",
	}
	f["united states"] = []string{
		"Tim Howard",
		"Chris Albright",
		"Carlos Bocanegra",
		"Pablo Mastroeni",
		"John O'Brien",
		"Steve Cherundolo",
		"Eddie Lewis",
		"Clint Dempsey",
		"Eddie Johnson",
		"Claudio Reyna",
		"Brian Ching",
		"Gregg Berhalter",
		"Jimmy Conrad",
		"Ben Olsen",
		"Bobby Convey",
		"Josh Wolff",
		"DaMarcus Beasley",
		"Kasey Keller",
		"Marcus Hahnemann",
		"Brian McBride",
		"Landon Donovan",
		"Oguchi Onyewu",
		"Eddie Pope",
	}
	f["ghana"] = []string{
		"Sammy Adjei",
		"Hans Sarpei",
		"Asamoah Gyan",
		"Samuel Kuffour",
		"John Mensah",
		"Emmanuel Pappoe",
		"Illiasu Shilla",
		"Michael Essien",
		"Derek Boateng",
		"Stephen Appiah",
		"Sulley Muntary",
		"Alex Tachie-Mensah",
		"Habib Mohamed",
		"Matthew Amoah",
		"John Pantsil",
		"George Owu",
		"Daniel Quaye",
		"Eric Addo",
		"Razak Pimpong",
		"Otto Addo",
		"Issah Ahmed",
		"Richard Kingston",
		"Haminu Dramani",
	}
	f["brazil"] = []string{
		"Nelson DIDA",
		"Marcos de Moraes CAFU",
		"LUCIO da Silva Ferreira",
		"JUAN Silveira dos Santos",
		"EMERSON da Rosa",
		"ROBERTO CARLOS da Silva",
		"ADRIANO Leite Ribeiro",
		"KAKA dos Santos Leite",
		"RONALDO Nazario de Lima",
		"RONALDINHO Moreira",
		"ZE ROBERTO da Silva",
		"ROGERIO CENI",
		"CICINHO de Cezare",
		"Anderson LUISAO da Silva",
		"CRIS Marques Gomes",
		"GILBERTO da Silva Melo",
		"GILBERTO SILVA",
		"Carlos da Silva MINEIRO",
		"JUNINHO PERNAMBUCANO",
		"RICARDINHO Rodrigues",
		"FRED Chaves Guedes",
		"JULIO CESAR Espindola",
		"ROBINHO de Souza",
	}
	f["croatia"] = []string{
		"Stipe Pletikosa",
		"Darijo Srna",
		"Josip Simunic",
		"Robert Kovac",
		"Igor Tudor",
		"Jurica Vranjes",
		"Dario Simic",
		"Marko Babic",
		"Dado Prso",
		"Niko Kovac",
		"Mario Tokic",
		"Joe Didulica",
		"Stjepan Tomas",
		"Luka Modric",
		"Ivan Leko",
		"Jerko Leko",
		"Ivan Klasnic",
		"Ivica Olic",
		"Niko Kranjcar",
		"Anthony Seric",
		"Bosko Balaban",
		"Ivan Bosnjak",
		"Tomislav Butina",
	}
	f["australia"] = []string{
		"Mark Schwarzer",
		"Lucas Neill",
		"Craig Moore",
		"Tim Cahill",
		"Jason Culina",
		"Tony Popovic",
		"Brett Emerton",
		"Josip Skoko",
		"Mark Viduka",
		"Harry Kewell",
		"Stan Lazaridis",
		"Ante Covic",
		"Vince Grella",
		"Scott Chipperfield",
		"John Aloisi",
		"Michael Beauchamp",
		"Archie Thompson",
		"Zeljko Kalac",
		"Joshua Kennedy",
		"Luke Wilkshire",
		"Mile Sterjovski",
		"Mark Milligan",
		"Marco Bresciano",
	}
	f["japan"] = []string{
		"Seigo Narazaki",
		"Makoto Tanaka",
		"Yuichi Komano",
		"Yasuhito Endo",
		"Tsuneyasu Miyamoto",
		"Koji Nakata",
		"Hidetoshi Nakata",
		"Mitsuo Ogasawara",
		"Naohiro Takahara",
		"Shunsuke Nakamura",
		"Seiichiro Maki",
		"Yoichi Doi",
		"Atsushi Yanagisawa",
		"Alessandro Santos",
		"Takashi Fukunishi",
		"Masashi Oguro",
		"Junichi Inamoto",
		"Shinji Ono",
		"Keisuke Tsuboi",
		"Keiji Tamada",
		"Akira Kaji",
		"Yuji Nakazawa",
		"Yoshikatsu Kawaguchi",
	}
	f["france"] = []string{
		"Mickael Landreau",
		"Jean-Alain Boumsong",
		"Eric Abidal",
		"Patrick Vieira",
		"William Gallas",
		"Claude Makelele",
		"Florent Malouda",
		"Vikash Dhorasoo",
		"Sidney Govou",
		"Zinedine Zidane",
		"Sylvain Wiltord",
		"Thierry Henry",
		"Mikael Silvestre",
		"Louis Saha",
		"Lilian Thuram",
		"Fabien Barthez",
		"Gael Givet",
		"Alou Diarra",
		"Willy Sagnol",
		"David Trezeguet",
		"Pascal Chimbonda",
		"Franck Ribery",
		"Gregory Coupet",
	}
	f["switherland"] = []string{
		"Pascal Zuberbühler",
		"Johan Djourou",
		"Ludovic Magnin",
		"Philippe Senderos",
		"Xavier Margairaz",
		"Johann Vogel",
		"Ricardo Cabanas",
		"Raphael Wicky",
		"Alexander Frei",
		"Daniel Gygax",
		"Marco Streller",
		"Diego Benaglio",
		"Stephane Grichting",
		"David Degen",
		"Blerim Dzemaili",
		"Tranquillo Barnetta",
		"Christoph Spycher",
		"Mauro Lustrinelli",
		"Valon Behrami",
		"Patrick Müller",
		"Fabio Coltorti",
		"Hakan Yakin",
		"Philipp Degen",
	}
	f["south korea"] = []string{
		"Won-Jae Lee",
		"Young-Chul Kim",
		"Dong-Jin Kim",
		"Jin-Cheul Choi",
		"Nam-Il Kim",
		"Jin-Kyu Kim",
		"Ji-Sung Park",
		"Do-Heon Kim",
		"Jung-Hwan Ahn",
		"Chu-Young Park",
		"Ki-Hyeon Seol",
		"Young-Pyo Lee",
		"Eul-Yong Lee",
		"Chun-Soo Lee",
		"Ji-Hoon Baek",
		"Kyung-Ho Chung",
		"Ho Lee",
		"Sang-Sik Kim",
		"Jae-Jin Cho",
		"Yong-Dae Kim",
		"Young-Kwang Kim",
		"Chong-Gug Song",
		"Won-Hee Cho",
	}
	f["togo"] = []string{
		"Ouro-Nimini Tchagnirou",
		"Dare Nibombe",
		"Jean-Paul Abalo",
		"Emmanuel Adebayor",
		"Massamasso Tchangai",
		"Yao Aziawonou",
		"Moustapha Salifou",
		"Kuami Agboh",
		"Thomas Dossevi",
		"Cherif Toure Mamam",
		"Robert Malm",
		"Eric Akoto",
		"Richmond Forson",
		"Adekanmi Olufade",
		"Alaixys Romao",
		"Kossi Agassa",
		"Mohamed Kader",
		"Yao Junior Senaya",
		"Ludovic Assemoassa",
		"Affo Erassa",
		"Karim Guede",
		"Kodjovi Obilale",
		"Toure Assimiou",
	}
	f["spain"] = []string{
		"Iker CASILLAS",
		"Michel SALGADO",
		"Mariano PERNIA",
		"Carlos MARCHENA",
		"Carles PUYOL",
		"David ALBELDA Aliques",
		"RAUL Gonzalez Blanco",
		"XAVI Hernandez",
		"Fernando TORRES",
		"Jose Antonio REYES",
		"LUIS GARCIA",
		"ANTONIO LOPEZ",
		"Andres INIESTA",
		"XABI ALONSO",
		"SERGIO RAMOS",
		"Marcos SENNA",
		"JOAQUIN Sanchez",
		"Cesc FABREGAS",
		"Santiago CANIZARES",
		"JUANITO Moreno",
		"DAVID VILLA",
		"PABLO Ibanez",
		"Jose Manuel REINA",
	}
	f["ukraine"] = []string{
		"Oleksandr Shovkovskiy",
		"Andriy Nesmachniy",
		"Oleksandr Iatsenko",
		"Anatoliy Tymoschuk",
		"Vladimir Yezerskiy",
		"Andriy Rusol",
		"Andriy Shevchenko",
		"Oleg Shelayev",
		"Oleg Gusev",
		"Andriy Voronin",
		"Serhiy Rebrov",
		"Andriy Pyatov",
		"Dmytro Chigrynskiy",
		"Andriy Gusin",
		"Artem Milevskiy",
		"Andriy Vorobey",
		"Vladislav Vashchuk",
		"Serhiy Nazarenko",
		"Maksim Kalinichenko",
		"Oleksiy Byelik",
		"Ruslan Rotan",
		"Vyacheslav Sviderskiy",
		"Bogdan Shust",
	}
	f["tunisia"] = []string{
		"Ali Boumnijel",
		"Karim Essediri",
		"Karim Haggui",
		"Alaeddine Yahia",
		"Ziad Jaziri",
		"Hatem Trabelsi",
		"Haykel Guemamdia",
		"Mehdi Nafti",
		"Yassine Chikhaoui",
		"Kaies Ghodhbane",
		"Francileudo dos SANTOS",
		"Jaouhar Mnari",
		"Riyadh Bouazizi",
		"Adel Chedli",
		"Radhi Jaidi",
		"Adel Nefzi",
		"Chaouki Ben Saada",
		"David Jemmali",
		"Anis Ayari",
		"Hamed Namouchi",
		"Karim Saidi",
		"Hamdi Kasraoui",
		"Sofiane Melliti",
	}
	f["saudi arabia"] = []string{
		"Mohammed Al-Deayea",
		"Ahmed Dokhi",
		"Redha Tukar",
		"Hamad Al-Montashari",
		"Naif Al-Qadi",
		"Omar Al-Ghamdi",
		"Mohammed Ameen",
		"Mohammed Noor",
		"Sami Al-Jaber",
		"Mohammad Al-Shlhoub",
		"Saad Al-Harthi",
		"Abdulaziz Khathran",
		"Hussain Sulimani",
		"Saud Khariri",
		"Ahmed Al-Bahri",
		"Khaled Aziz",
		"Mohammed Al-Anbar",
		"Nawaf Al-Temiyat",
		"Mohammed Massad",
		"Yaser Al-Kahtani",
		"Mabrouk Zaid",
		"Mohammad Khojah",
		"Malek Al-Hawsawi",
	}
	F := dataset.SearchSystem_{}
	F.Constructor() // important
	F.Include(FIFAWC2006Key, SportKey, FootballKey, f, true, false, false)
	return F
}

func FIFAWC2010() dataset.SearchSystem_ {
	f := map[string][]string{}
	f["south africa"] = []string{
		"moneeb josephs",
		"siboniso gaxa",
		"tsepo masilela",
		"aaron mokoena",
		"anele ngcongca",
		"macbeth sibaya",
		"lance davids",
		"siphiwe tshabalala",
		"katlego mphela",
		"steven pienaar",
		"teko modise",
		"reneilwe letsholonyane",
		"kagisho dikgacoi",
		"matthew booth",
		"lucas thwala",
		"itumeleng khune",
		"bernard parker",
		"siyabonga nomvethe",
		"surprise moriri",
		"bongani khumalo",
		"siyabonga sangweni",
		"shu-aib walters",
		"thanduyise khuboni",
	}
	f["mexico"] = []string{
		"oscar perez",
		"francisco rodriguez",
		"carlos salcido",
		"rafael marquez",
		"ricardo osorio",
		"gerardo torrado",
		"pablo barrera",
		"israel castro",
		"guillermo franco",
		"cuauhtemoc blanco",
		"carlos vela",
		"paul aguilar",
		"guillermo ochoa",
		"javier hernandez",
		"hector moreno",
		"efrain juarez",
		"giovani dos santos",
		"andres guardado",
		"jonny magallon",
		"jorge torres",
		"adolfo bautista",
		"alberto medina",
		"luis michel",
	}
	f["uruguay"] = []string{
		"fernando muslera",
		"diego lugano",
		"diego godin",
		"jorge fucile",
		"walter gargano",
		"mauricio victorino",
		"edinson cavani",
		"sebastian eguren",
		"luis suarez",
		"diego forlan",
		"alvaro pereira",
		"juan castillo",
		"sebastian abreu",
		"nicolas lodeiro",
		"diego perez",
		"maximiliano pereira",
		"egidio arevalo",
		"ignacio gonzalez",
		"andres scotti",
		"alvaro fernandez",
		"sebastian fernandez",
		"martin caceres",
		"martin silva",
	}
	f["france"] = []string{
		"hugo lloris",
		"bacary sagna",
		"eric abidal",
		"anthony reveillere",
		"william gallas",
		"marc planus",
		"franck ribery",
		"yoann gourcuff",
		"djibril cisse",
		"sidney govou",
		"andre-pierre gignac",
		"thierry henry",
		"patrice evra",
		"jeremy toulalan",
		"florent malouda",
		"steve mandanda",
		"sebastien squillaci",
		"alou diarra",
		"abou diaby",
		"mathieu valbuena",
		"nicolas anelka",
		"gael clichy",
		"cedric carrasso",
	}
	f["argentina"] = []string{
		"diego pozo",
		"martin demichelis",
		"clemente rodriguez",
		"nicolas burdisso",
		"mario bolatti",
		"gabriel heinze",
		"angel di maria",
		"juan veron",
		"gonzalo higuain",
		"lionel messi",
		"carlos tevez",
		"ariel garce",
		"walter samuel",
		"javier mascherano",
		"nicolas otamendi",
		"sergio agüero",
		"jonas gutierrez",
		"martin palermo",
		"diego milito",
		"maximiliano rodriguez",
		"mariano andujar",
		"sergio romero",
		"javier pastore",
	}
	f["nigeria"] = []string{
		"vincent enyeama",
		"joseph yobo",
		"taye taiwo",
		"nwankwo kanu",
		"rabiu afolabi",
		"danny shittu",
		"john utaka",
		"yakubu aiyegbeni",
		"obafemi martins",
		"ideye brown",
		"peter odemwingie",
		"kalu uche",
		"yussuf ayila",
		"sani kaita",
		"lukman haruna",
		"austin ejide",
		"chidi odiah",
		"victor obinna",
		"chinedu ogbuke obasi",
		"dickson etuhu",
		"uwa echiejile",
		"dele adeleye",
		"dele aiyenugba",
	}
	f["south korea"] = []string{
		"woon-jae lee",
		"beom-seok oh",
		"hyung-il kim",
		"yong-hyung cho",
		"nam-il kim",
		"bo-kyung kim",
		"ji-sung park",
		"jung-woo kim",
		"jung-hwan ahn",
		"chu-young park",
		"seung-yeoul lee",
		"young-pyo lee",
		"jae-sung kim",
		"jung-soo lee",
		"dong-jin kim",
		"sung-yueng ki",
		"chung-yong lee",
		"sung-ryong jung",
		"ki-hun yeom",
		"dong-gook lee",
		"young-kwang kim",
		"du-ri cha",
		"min-soo kang",
	}
	f["greece"] = []string{
		"konstantinos chalkias",
		"giourkas seitaridis",
		"christos patsatzoglou",
		"nikos spiropoulos",
		"vangelis moras",
		"alexandros tziolis",
		"georgios samaras",
		"avraam papadopoulos",
		"angelos charisteas",
		"georgios karagounis",
		"loukas vyntra",
		"alexandros tzorvas",
		"michail sifakis",
		"dimitrios salpingidis",
		"vasileios torosidis",
		"sotirios kyrgiakos",
		"theofanis gekas",
		"sotiris ninis",
		"sokratis papastathopoulos",
		"pantelis kapetanos",
		"konstantinos katsouranis",
		"stelios malezas",
		"athanasios prittas",
	}
	f["england"] = []string{
		"david james",
		"glen johnson",
		"ashley cole",
		"steven gerrard",
		"michael dawson",
		"john terry",
		"aaron lennon",
		"frank lampard",
		"peter crouch",
		"wayne rooney",
		"joe cole",
		"robert green",
		"stephen warnock",
		"gareth barry",
		"matthew upson",
		"james milner",
		"shaun wright-phillips",
		"jamie carragher",
		"jermain defoe",
		"ledley king",
		"emile heskey",
		"michael carrick",
		"joe hart",
	}
	f["united states"] = []string{
		"tim howard",
		"jonathan spector",
		"carlos bocanegra",
		"michael bradley",
		"oguchi onyewu",
		"steve cherundolo",
		"damarcus beasley",
		"clint dempsey",
		"herculez gomez",
		"landon donovan",
		"stuart holden",
		"jonathan bornstein",
		"ricardo clark",
		"edson buddle",
		"jay demerit",
		"francisco torres",
		"jozy altidore",
		"brad guzan",
		"maurice edu",
		"robbie findley",
		"clarence goodson",
		"benny feilhaber",
		"marcus hahnemann",
	}
	f["algeria"] = []string{
		"lounes gaouaoui",
		"madjid bougherra",
		"nadir belhadj",
		"anther yahia",
		"rafik halliche",
		"yazid mansouri",
		"ryad boudebouz",
		"medhi lacen",
		"abdelkader ghezzal",
		"rafik saifi",
		"rafik djebbour",
		"habib bellaid",
		"karim matmour",
		"abdelkader laifaoui",
		"karim ziani",
		"faouzi chaouchi",
		"adlane guedioura",
		"carl medjani",
		"hassan yebda",
		"djamel mesbah",
		"foued kadir",
		"djamal abdoun",
		"rais m'bolhi",
	}
	f["slovenia"] = []string{
		"samir handanovic",
		"miso brecko",
		"elvedin dzinic",
		"marko suler",
		"bostjan cesar",
		"branko ilic",
		"nejc pecnik",
		"robert koren",
		"zlatan ljubijankic",
		"valter birsa",
		"milivoje novakovic",
		"jasmin handanovic",
		"bojan jokic",
		"zlatko dedic",
		"rene krhin",
		"aleksander seliga",
		"andraz kirm",
		"aleksandar radosavljevic",
		"suad filekovic",
		"andrej komac",
		"dalibor stevanovic",
		"matej mavric",
		"tim matavz",
	}
	f["germany"] = []string{
		"manuel neuer",
		"marcell jansen",
		"arne friedrich",
		"dennis aogo",
		"serdar tasci",
		"sami khedira",
		"bastian schweinsteiger",
		"mesut özil",
		"stefan kiessling",
		"lukas podolski",
		"miroslav klose",
		"tim wiese",
		"thomas müller",
		"holger badstuber",
		"piotr trochowski",
		"philipp lahm",
		"per mertesacker",
		"toni kroos",
		"claudemir cacau barreto",
		"jerome boateng",
		"marko marin",
		"hans jörg butt",
		"mario gomez",
	}
	f["australia"] = []string{
		"mark schwarzer",
		"lucas neill",
		"craig moore",
		"tim cahill",
		"jason culina",
		"michael beauchamp",
		"brett emerton",
		"luke wilkshire",
		"joshua kennedy",
		"harry kewell",
		"scott chipperfield",
		"adam federici",
		"vince grella",
		"brett holman",
		"mile jedinak",
		"carl valeri",
		"nikita rukavytsya",
		"eugene galekovic",
		"richard garcia",
		"mark milligan",
		"david carney",
		"dario vidosic",
		"marco bresciano",
	}
	f["serbia"] = []string{
		"vladimir stojkovic",
		"antonio rukavina",
		"aleksandar kolarov",
		"gojko kacar",
		"nemanja vidic",
		"branislav ivanovic",
		"zoran tosic",
		"danko lazovic",
		"marko pantelic",
		"dejan stankovic",
		"nenad milijas",
		"bojan isailovic",
		"aleksandar lukovic",
		"milan jovanovic",
		"nikola zigic",
		"ivan obradovic",
		"milos krasic",
		"milos ninkovic",
		"radosav petrovic",
		"neven subotic",
		"dragan mrdja",
		"zdravko kuzmanovic",
		"andjelko djuricic",
	}
	f["ghana"] = []string{
		"daniel agyei",
		"hans sarpei",
		"asamoah gyan",
		"john pantsil",
		"john mensah",
		"anthony annan",
		"samuel inkoom",
		"jonathan mensah",
		"derek boateng",
		"stephen appiah",
		"sulley muntary",
		"prince tagoe",
		"andre ayew",
		"matthew amoah",
		"isaac vorsah",
		"stephen ahorlu",
		"ibrahim ayew",
		"dominic adiyiah",
		"lee addy",
		"quincy owusu-abeyie",
		"kwadwo asamoah",
		"richard kingson",
		"kevin prince boateng",
	}
	f["netherland"] = []string{
		"maarten stekelenburg",
		"gregory van der wiel",
		"john heitinga",
		"joris mathijsen",
		"giovanni van bronckhorst",
		"mark van bommel",
		"dirk kuijt",
		"nigel de jong",
		"robin van persie",
		"wesley sneijder",
		"arjen robben",
		"khalid boulahrouz",
		"andre ooijer",
		"demy de zeeuw",
		"edson braafheid",
		"michel vorm",
		"eljero elia",
		"stijn schaars",
		"ryan babel",
		"ibrahim afellay",
		"klaas-jan huntelaar",
		"sander boschker",
		"rafael van der vaart",
	}
	f["denmark"] = []string{
		"thomas sørensen",
		"christian poulsen",
		"simon kjær",
		"daniel agger",
		"william kvist",
		"lars jacobsen",
		"daniel jensen",
		"jesper grønkjær",
		"jon dahl tomasson",
		"martin jørgensen",
		"nicklas bendtner",
		"thomas kahlenberg",
		"per krøldrup",
		"jakob poulsen",
		"simon poulsen",
		"stephan andersen",
		"mikkel beckmann",
		"søren larsen",
		"dennis rommedahl",
		"thomas enevoldsen",
		"christian eriksen",
		"jesper christiansen",
		"patrick mtiliga",
	}
	f["japan"] = []string{
		"seigo narazaki",
		"yuki abe",
		"yuichi komano",
		"marcus tulio tanaka",
		"yuto nagatomo",
		"atsuto uchida",
		"yasuhito endo",
		"daisuke matsui",
		"shinji okazaki",
		"shunsuke nakamura",
		"keiji tamada",
		"kisho yano",
		"daiki iwamasa",
		"kengo nakamura",
		"yasuyuki konno",
		"yoshito okubo",
		"makoto hasebe",
		"keisuke honda",
		"takayuki morimoto",
		"junichi inamoto",
		"eiji kawashima",
		"yuji nakazawa",
		"yoshikatsu kawaguchi",
	}
	f["cameroon"] = []string{
		"idriss kameni",
		"benoit assou-ekotto",
		"nicolas nkoulou",
		"rigobert song",
		"sebastien bassong",
		"alexandre song",
		"landry nguemo",
		"geremi njitap fotso",
		"samuel eto'o",
		"achille emana",
		"jean makoun",
		"gaetan bong",
		"eric choupo moting",
		"aurelien chedjou",
		"pierre webo",
		"souleymanou hamidou",
		"mohamadou idrissou",
		"eyong enoh",
		"stephane mbia",
		"georges mandjeck",
		"joel matip",
		"guy ndy",
		"vincent aboubakar",
	}
	f["itlay"] = []string{
		"gianluigi buffon",
		"christian maggio",
		"domenico criscito",
		"giorgio chiellini",
		"fabio cannavaro",
		"daniele de rossi",
		"simone pepe",
		"gennaro gattuso",
		"vincenzo iaquinta",
		"antonio di natale",
		"alberto gilardino",
		"federico marchetti",
		"salvatore bocchetti",
		"morgan de sanctis",
		"claudio marchisio",
		"mauro camoranesi",
		"angelo palombo",
		"fabio quagliarella",
		"gianluca zambrotta",
		"giampaolo pazzini",
		"andrea pirlo",
		"riccardo montolivo",
		"leonardo bonucci",
	}
	f["paraguay"] = []string{
		"justo villar",
		"dario veron",
		"claudio morel",
		"denis caniza",
		"julio cesar caceres",
		"carlos bonet",
		"oscar cardozo",
		"edgar barreto",
		"roque santa cruz",
		"edgar benitez",
		"jonathan santana",
		"diego barreto",
		"enrique vera",
		"paulo da silva",
		"victor caceres",
		"cristian riveros",
		"aureliano torres",
		"nelson valdez",
		"lucas barrios",
		"nestor ortigoza",
		"antolin alcaraz",
		"aldo bobadilla",
		"rodolfo gamarra",
	}
	f["new zeland"] = []string{
		"mark paston",
		"ben sigmund",
		"tony lochhead",
		"winston reid",
		"ivan vicelich",
		"ryan nelsen",
		"simon elliott",
		"tim brown",
		"shane smeltz",
		"chris killen",
		"leo bertos",
		"glen moss",
		"andy barron",
		"rory fallon",
		"michael mcglinchey",
		"aaron clapham",
		"dave mulligan",
		"andy boyens",
		"tommy smith",
		"chris wood",
		"jeremy christie",
		"jeremy brockie",
		"james bannatyne",
	}
	f["slovakia"] = []string{
		"jan mucha",
		"peter pekarik",
		"martin skrtel",
		"marek cech",
		"radoslav zabavnik",
		"zdenko strba",
		"vladimir weiss",
		"jan kozak",
		"stanislav sestak",
		"marek sapara",
		"robert vittek",
		"dusan pernis",
		"filip holosko",
		"martin jakubko",
		"miroslav stoch",
		"jan durica",
		"marek hamsik",
		"erik jendrisek",
		"juraj kucka",
		"kamil kopunek",
		"kornel salata",
		"martin petras",
		"dusan kuciak",
	}
	f["brazil"] = []string{
		"julio cesar espindola",
		"maicon douglas sisenando",
		"lucio da silva ferreira",
		"juan silveira dos santos",
		"felipe melo de carvalho",
		"michel fernandes bastos",
		"elano blumer",
		"gilberto silva",
		"luis fabiano clemente",
		"kaka dos santos leite",
		"robinho de souza",
		"heurelho gomes",
		"daniel alves da silva",
		"anderson luisao da silva",
		"thiago emiliano da silva",
		"gilberto da silva melo",
		"josue de oliveira",
		"ramires do nascimento",
		"julio cesar baptista",
		"jose kleberson pereira",
		"nilmar honorato da silva",
		"donieber marangon",
		"edinaldo grafite batista",
	}
	f["north korea"] = []string{
		"myong-guk ri",
		"jong-hyok cha",
		"jun-il ri",
		"nam-chol pak",
		"kwang-chon ri",
		"kum-il kim",
		"chol-hyok an",
		"yun-nam ji",
		"tae-se jong",
		"yong-jo hong",
		"in-guk mun",
		"kum-chol choe",
		"chol-jin pak",
		"nam-chol pak",
		"yong-jun kim",
		"song-chol nam",
		"yong-hak an",
		"myong-gil kim",
		"chol-myong ri",
		"myong-won kim",
		"kwang-hyok ri",
		"kyong-il kim",
		"sung-hyok pak",
	}
	f["cote d'ivoire"] = []string{
		"boubacar barry",
		"brou angoua",
		"arthur boka",
		"kolo toure",
		"didier zokora",
		"steve gohouri",
		"seydou doumbia",
		"salomon kalou",
		"ismael tiote",
		"gervinho kouassi",
		"didier drogba",
		"jean jacques gosso",
		"romaric n'dri",
		"emmanuel kone",
		"aruna dindane",
		"aristide zogbo",
		"siaka tiene",
		"kader keita",
		"yaya toure",
		"guy demel",
		"emmanuel eboue",
		"souleymane bamba",
		"daniel yeboah",
	}
	f["portugal"] = []string{
		"eduardo reis carvalho",
		"bruno alves",
		"paulo ferreira",
		"rolando pires da fonseca",
		"duda barbosa valente",
		"ricardo carvalho",
		"cristiano ronaldo",
		"pedro mendes",
		"liedson da silva muniz",
		"danny alves gomes",
		"simao sabrosa",
		"beto bastos pimparel",
		"luis miguel monteiro",
		"miguel veloso",
		"pepe lima ferreira",
		"raul meireles",
		"ruben amorim",
		"hugo almeida",
		"tiago cardoso mendes",
		"deco luiz de sousa",
		"ricardo costa",
		"daniel fernandes",
		"fabio coentrao",
	}
	f["spain"] = []string{
		"iker casillas",
		"raul albiol",
		"gerard pique",
		"carlos marchena",
		"carles puyol",
		"andres iniesta",
		"david villa",
		"xavi hernandez",
		"fernando torres",
		"cesc fabregas",
		"joan capdevila",
		"victor valdes",
		"juan manuel mata",
		"xabi alonso",
		"sergio ramos",
		"sergio busquets",
		"alvaro arbeloa",
		"pedro rodriguez",
		"fernando llorente",
		"javier martinez",
		"david silva",
		"jesus navas",
		"jose manuel reina",
	}
	f["switherland"] = []string{
		"diego benaglio",
		"stephan lichtsteiner",
		"ludovic magnin",
		"philippe senderos",
		"steve von bergen",
		"benjamin huggel",
		"tranquillo barnetta",
		"gokhan inler",
		"alexander frei",
		"blaise nkufo",
		"valon behrami",
		"marco wölfli",
		"stephane grichting",
		"marco padalino",
		"hakan yakin",
		"gelson fernandes",
		"reto ziegler",
		"albert bunjaku",
		"eren derdiyok",
		"pirmin schwegler",
		"johnny leoni",
		"mario eggimann",
		"xherdan shaqiri",
	}
	f["honduras"] = []string{
		"ricardo canales",
		"osman chavez",
		"maynor figueroa",
		"jhony palacios",
		"victor bernardez",
		"hendry thomas",
		"ramon nunez",
		"wilson palacios",
		"carlos pavon",
		"jerry palacios",
		"david suazo",
		"george welcome",
		"roger espinoza",
		"oscar garcia",
		"walter martinez",
		"mauricio sabillon",
		"edgar alvarez",
		"noel valladares",
		"danilo turcios",
		"amado guevara",
		"emilio izaguirre",
		"donis escober",
		"sergio mendoza",
	}
	f["chile"] = []string{
		"claudio bravo",
		"ismael fuentes",
		"waldo ponce",
		"mauricio isla",
		"pablo contreras",
		"carlos carmona",
		"alexis sanchez",
		"arturo vidal",
		"humberto suazo",
		"jorge valdivia",
		"mark gonzalez",
		"miguel pinto",
		"marco estrada",
		"matias fernandez",
		"jean beausejour",
		"fabian orellana",
		"gary medel",
		"gonzalo jara",
		"gonzalo fierro",
		"rodrigo millar",
		"rodrigo tello",
		"esteban paredes",
		"luis marin",
	}
	F := dataset.SearchSystem_{}
	F.Constructor() // important
	F.Include(FIFAWC2010Key, SportKey, FootballKey, f, true, false, false)
	return F
}

func FIFAWC2014() dataset.SearchSystem_ {
	f := map[string][]string{}
	f["brazil"] = []string{
		"jefferson de oliveira",
		"daniel alves da silva",
		"thiago emiliano da silva",
		"david luiz moreira marinho",
		"fernandinho luiz roza",
		"marcelo vieira da silva",
		"hulk vieira de souza",
		"jose paulinho bezerra",
		"frederico chaves guedes",
		"neymar da silva santos",
		"oscar dos santos emboaba",
		"julio cesar espindola",
		"dante bonfim costa santos",
		"maxwell cabelino andrade",
		"henrique adriano buss",
		"ramires do nascimento",
		"luiz gustavo dias",
		"hernanes de carvalho viana",
		"willian borges da silva",
		"bernard anicio caldeira",
		"joao alves de assis silva",
		"victor leandro bagy",
		"maicon douglas sisenando",
	}
	f["mexico"] = []string{
		"jose corona",
		"francisco rodriguez",
		"carlos salcido",
		"rafael marquez",
		"diego reyes",
		"hector herrera",
		"miguel layun",
		"marco fabian",
		"raul jimenez",
		"giovani dos santos",
		"alan pulido",
		"alfredo talavera",
		"guillermo ochoa",
		"javier hernandez",
		"hector moreno",
		"miguel ponce",
		"isaac brizuela",
		"andres guardado",
		"oribe peralta",
		"javier aquino",
		"carlos peña",
		"paul aguilar",
		"jose vazquez",
	}
	f["cameroon"] = []string{
		"loïc feudjou",
		"benoit assou-ekotto",
		"nicolas nkoulou",
		"cedric djeugoue",
		"dany nounkeu",
		"alexandre song",
		"landry nguemo",
		"benjamin moukandjo",
		"samuel eto'o",
		"vincent aboubakar",
		"jean makoun",
		"henri bedimo",
		"eric choupo-moting",
		"aurelien chedjou",
		"pierre webo",
		"charles itandje",
		"stephane mbia",
		"eyong enoh",
		"fabrice olinga",
		"edgar salli",
		"joel matip",
		"allan nyom",
		"sammy ndjock",
	}
	f["croatia"] = []string{
		"stipe pletikosa",
		"sime vrsaljko",
		"danijel pranjic",
		"ivan perisic",
		"vedran corluka",
		"dejan lovren",
		"ivan rakitic",
		"ognjen vukojevic",
		"nikica jelavic",
		"luka modric",
		"darijo srna",
		"oliver zelenika",
		"gordon schildenfeld",
		"marcelo brozovic",
		"milan badelj",
		"ante rebic",
		"mario mandzukic",
		"ivica olic",
		"sammir cruz campos",
		"mateo kovacic",
		"domagoj vida",
		"eduardo da silva",
		"danijel subasic",
	}
	f["spain"] = []string{
		"iker casillas",
		"raul albiol",
		"gerard pique",
		"javier martinez",
		"juanfran torres",
		"andres iniesta",
		"david villa",
		"xavi hernandez",
		"fernando torres",
		"cesc fabregas",
		"pedro rodriguez",
		"david de gea",
		"juan manuel mata",
		"xabi alonso",
		"sergio ramos",
		"sergio busquets",
		"jorge koke resurreccion",
		"jordi alba",
		"diego costa",
		"santi cazorla",
		"david silva",
		"cesar azpilicueta",
		"jose manuel reina",
	}
	f["netherland"] = []string{
		"jasper cillessen",
		"ron vlaar",
		"stefan de vrij",
		"bruno martins indi",
		"daley blind",
		"nigel de jong",
		"daryl janmaat",
		"jonathan de guzman",
		"robin van persie",
		"wesley sneijder",
		"arjen robben",
		"paul verhaegh",
		"joël veltman",
		"terence kongolo",
		"dirk kuijt",
		"jordy clasie",
		"jeremain lens",
		"leroy fer",
		"klaas-jan huntelaar",
		"georginio wijnaldum",
		"memphis depay",
		"michel vorm",
		"tim krul",
	}
	f["chile"] = []string{
		"claudio bravo",
		"eugenio mena",
		"miiko albornoz",
		"mauricio isla",
		"francisco silva",
		"carlos carmona",
		"alexis sanchez",
		"arturo vidal",
		"mauricio pinilla",
		"jorge valdivia",
		"eduardo vargas",
		"cristopher toselli",
		"jose rojas",
		"fabian orellana",
		"jean beausejour",
		"felipe gutierrez",
		"gary medel",
		"gonzalo jara",
		"jose fuenzalida",
		"charles aranguiz",
		"marcelo diaz",
		"esteban paredes",
		"johnny herrera",
	}
	f["australia"] = []string{
		"maty ryan",
		"ivan franjic",
		"jason davidson",
		"tim cahill",
		"mark milligan",
		"matthew spiranovic",
		"mathew leckie",
		"bailey wright",
		"adam taggart",
		"ben halloran",
		"tommy oar",
		"mitch langerak",
		"oliver bozanic",
		"james troisi",
		"mile jedinak",
		"james holland",
		"matt mckay",
		"eugene galekovic",
		"ryan mcgowan",
		"dario vidosic",
		"massimo luongo",
		"alex wilkinson",
		"marco bresciano",
	}
	f["colombia"] = []string{
		"david ospina",
		"cristian zapata",
		"mario yepes",
		"santiago arias",
		"carlos carbonero",
		"carlos sanchez",
		"pablo armero",
		"abel aguilar",
		"teofilo gutierrez",
		"james rodriguez",
		"juan cuadrado",
		"camilo vargas",
		"fredy guarin",
		"victor ibarbo",
		"alexander mejia",
		"eder balanta",
		"carlos bacca",
		"juan zuniga",
		"adrian ramos",
		"juan quintero",
		"jackson martinez",
		"faryd mondragon",
		"carlos valdes",
	}
	f["cote d'ivoire"] = []string{
		"boubacar barry",
		"ousmane diarrassouba",
		"arthur boka",
		"kolo toure",
		"didier zokora",
		"mathis bolly",
		"jean-daniel akpa-akpro",
		"salomon kalou",
		"ismaël tiote",
		"gervinho kouassi",
		"didier drogba",
		"wilfred bony",
		"didier konan ya",
		"ismaël diomande",
		"max gradel",
		"sylvain gbohouo",
		"serge aurier",
		"constant djakpa",
		"yaya toure",
		"die serey",
		"giovanni sio",
		"souleymane bamba",
		"sayouba mande",
	}
	f["greece"] = []string{
		"orestis karnezis",
		"ioannis maniatis",
		"giorgios tzavelas",
		"konstantinos manolas",
		"vangelis moras",
		"alexandros tziolis",
		"georgios samaras",
		"panagiotis kone",
		"konstantinos mitroglou",
		"georgios karagounis",
		"loukas vyntra",
		"panagiotis glykos",
		"stefanos kapino",
		"dimitrios salpingidis",
		"vasilios torosidis",
		"lazaros christodoulopoulos",
		"theofanis gekas",
		"ioannis fetfatzidis",
		"sokratis papastathopoulos",
		"jose cholevas",
		"konstantinos katsouranis",
		"andreas samaris",
		"panagiotis tachtsidis",
	}
	f["japan"] = []string{
		"eiji kawashima",
		"atsuto uchida",
		"gotoku sakai",
		"keisuke honda",
		"yuto nagatomo",
		"masato morishige",
		"yasuhito endo",
		"hiroshi kiyotake",
		"shinji okazaki",
		"shinji kagawa",
		"yoichiro kakitani",
		"shusaku nishikawa",
		"yoshito okubo",
		"toshihiro aoyama",
		"yasuyuki konno",
		"hotaru yamaguchi",
		"makoto hasebe",
		"yuya osako",
		"masahiko inoha",
		"manabu saito",
		"hiroki sakai",
		"maya yoshida",
		"shuichi gonda",
	}
	f["itlay"] = []string{
		"gianluigi buffon",
		"mattia de sciglio",
		"giorgio chiellini",
		"matteo darmian",
		"thiago motta",
		"antonio candreva",
		"ignazio abate",
		"claudio marchisio",
		"mario balotelli",
		"antonio cassano",
		"alessio cerci",
		"salvatore sirigu",
		"mattia perin",
		"alberto aquilani",
		"andrea barzagli",
		"daniele de rossi",
		"ciro immobile",
		"marco parolo",
		"leonardo bonucci",
		"gabriel paletta",
		"andrea pirlo",
		"lorenzo insigne",
		"marco verratti",
	}
	f["england"] = []string{
		"joe hart",
		"glen johnson",
		"leighton baines",
		"steven gerrard",
		"gary cahill",
		"phil jagielka",
		"jack wilshere",
		"frank lampard",
		"daniel sturridge",
		"wayne rooney",
		"danny welbeck",
		"chris smalling",
		"ben foster",
		"jordan henderson",
		"alex oxlade-chamberlain",
		"phil jones",
		"james milner",
		"rickie lambert",
		"raheem sterling",
		"adam lallana",
		"ross barkley",
		"fraser forster",
		"luke shaw",
	}
	f["uruguay"] = []string{
		"fernando muslera",
		"diego lugano",
		"diego godin",
		"jorge fucile",
		"walter gargano",
		"alvaro pereira",
		"cristian rodriguez",
		"abel hernandez",
		"luis suarez",
		"diego forlan",
		"christian stuani",
		"rodrigo muñoz",
		"jose maria gimenez",
		"nicolas lodeiro",
		"diego perez",
		"maximiliano pereira",
		"egidio arevalo",
		"gaston ramirez",
		"sebastian coates",
		"alvaro gonzalez",
		"edinson cavani",
		"martin caceres",
		"martin silva",
	}
	f["costa rica"] = []string{
		"keylor navas",
		"johnny acosta",
		"giancarlo gonzalez",
		"michael umaña",
		"celso borges",
		"oscar duarte",
		"christian bolaños",
		"dave myrie",
		"joel campbell",
		"bryan ruiz",
		"michael barrantes",
		"waylon francis",
		"oscar granados",
		"randall brenes",
		"junior diaz",
		"cristian gamboa",
		"yeltsin tejeda",
		"patrick pemberton",
		"roy miller",
		"diego calvo",
		"marcos ureña",
		"jose cubero",
		"daniel cambronero",
	}
	f["france"] = []string{
		"hugo lloris",
		"mathieu debuchy",
		"patrice evra",
		"raphaël varane",
		"mamadou sakho",
		"yohan cabaye",
		"remy cabella",
		"mathieu valbuena",
		"olivier giroud",
		"karim benzema",
		"antoine griezmann",
		"rio mavuba",
		"eliaquim mangala",
		"blaise matuidi",
		"bacary sagna",
		"stephane ruffier",
		"lucas digne",
		"moussa sissoko",
		"paul pogba",
		"loïc remy",
		"laurent koscielny",
		"morgan schneiderlin",
		"mickaël landreau",
	}
	f["ecuador"] = []string{
		"maximo banguera",
		"jorge guagua",
		"frickson erazo",
		"juan paredes",
		"alex ibarra",
		"cristhian noboa",
		"jefferson montero",
		"edison mendez",
		"joao rojas",
		"walter ayovi",
		"felipe caicedo",
		"adrian bone",
		"enner valencia",
		"oswaldo minda",
		"michael arroyo",
		"antonio valencia",
		"jaimen ayovi",
		"oscar bagui",
		"luis saritama",
		"fidel martinez",
		"gabriel achilier",
		"alexander dominguez",
		"carlos gruezo",
	}
	f["switherland"] = []string{
		"diego benaglio",
		"stephan lichtsteiner",
		"reto ziegler",
		"philippe senderos",
		"steve von bergen",
		"michael lang",
		"tranquillo barnetta",
		"gökhan inler",
		"haris seferovic",
		"granit xhaka",
		"valon behrami",
		"yann sommer",
		"ricardo rodriguez",
		"valentin stocker",
		"blerim dzemaili",
		"gelson fernandes",
		"mario gavranovic",
		"admir mehmedi",
		"josip drmic",
		"johan djourou",
		"roman bürki",
		"fabian schär",
		"xherdan shaqiri",
	}
	f["honduras"] = []string{
		"luis lopez",
		"osman chavez",
		"maynor figueroa",
		"juan pablo montes",
		"victor bernardez",
		"juan carlos garcia",
		"emilio izaguirre",
		"wilson palacios",
		"jerry palacios",
		"mario martinez",
		"jerry bengtson",
		"edder delgado",
		"carlo costly",
		"oscar garcia",
		"roger espinoza",
		"rony martinez",
		"andy najar",
		"noel valladares",
		"luis garrido",
		"jorge claros",
		"brayan beckeles",
		"donis escober",
		"marvin chavez",
	}
	f["argentina"] = []string{
		"sergio romero",
		"ezequiel garay",
		"hugo campagnaro",
		"pablo zabaleta",
		"fernando gago",
		"lucas biglia",
		"angel di maria",
		"enzo perez",
		"gonzalo higuain",
		"lionel messi",
		"maximiliano rodriguez",
		"agustin orion",
		"augusto fernandez",
		"javier mascherano",
		"martin demichelis",
		"marcos rojo",
		"federico fernandez",
		"rodrigo palacio",
		"ricardo alvarez",
		"sergio agüero",
		"mariano andujar",
		"ezequiel lavezzi",
		"jose maria basanta",
	}
	f["nigeria"] = []string{
		"vincent enyeama",
		"joseph yobo",
		"ejike uzoenyi",
		"ruben gabriel",
		"efe ambrose",
		"azubuike egwuekwe",
		"ahmed musa",
		"peter odemwingie",
		"emmanuel emenike",
		"john obi mikel",
		"victor moses",
		"ebenezer odunlami",
		"juwon oshaniwa",
		"godfrey oboabona",
		"ramon azeez",
		"austin ejide",
		"ogenyi onazi",
		"michael babatunde",
		"uche nwofor",
		"okechukwu uchebo",
		"chigozie agbim",
		"kenneth omeruo",
		"shola ameobi",
	}
	f["bosnia and herzegovina"] = []string{
		"asmir begovic",
		"avdija vrsajevic",
		"ermin bicakcic",
		"emir spahic",
		"sead kolasinac",
		"ognjen vranjes",
		"muhamed besic",
		"miralem pjanic",
		"vedad ibisevic",
		"zvjezdan misimovic",
		"edin dzeko",
		"jasmin fejzic",
		"mensur mujdza",
		"tino sven susic",
		"toni sunjic",
		"senad lulic",
		"senijad ibricic",
		"haris medunjanin",
		"edin visca",
		"izet hajrovic",
		"anel hadzic",
		"asmir avdukic",
		"sejad salihovic",
	}
	f["iran"] = []string{
		"rahman ahmadi",
		"khosro heydari",
		"ehsan haji safi",
		"jalal hosseini",
		"amirhossein sadeghi",
		"javad nekounam",
		"masoud shojaei",
		"reza haghighi",
		"alireza jahan bakhsh",
		"karim ansari fard",
		"ghasem hadadifar",
		"alireza haghighi",
		"hossein mahini",
		"andranik timotian",
		"pejman montazeri",
		"reza ghoochannejad",
		"ahmad alnameh",
		"bakhtiar rahmani",
		"hashem beikzadeh",
		"steven beitashour",
		"ashkan dejagah",
		"daniel davari",
		"mehrdad pooladi",
	}
	f["germany"] = []string{
		"manuel neuer",
		"kevin grosskreutz",
		"matthias ginter",
		"benedikt höwedes",
		"mats hummels",
		"sami khedira",
		"bastian schweinsteiger",
		"mesut özil",
		"andre schürrle",
		"lukas podolski",
		"miroslav klose",
		"ron-robert zieler",
		"thomas müller",
		"julian draxler",
		"erik durm",
		"philipp lahm",
		"per mertesacker",
		"toni kroos",
		"mario götze",
		"jerome boateng",
		"shkodran mustafi",
		"roman weidenfeller",
		"christoph kramer",
	}
	f["portugal"] = []string{
		"eduardo reis carvalho",
		"bruno alves",
		"pepe lima ferreira",
		"miguel veloso",
		"fabio coentrao",
		"william carvalho",
		"cristiano ronaldo",
		"joao moutinho",
		"hugo almeida",
		"vieirinha de freitas",
		"ederzito macedo lopes",
		"rui patricio",
		"ricardo costa",
		"luis neto",
		"rafael silva",
		"raul meireles",
		"nani luis da cunha",
		"silvestre varela",
		"andre almeida",
		"ruben amorim",
		"joao pereira",
		"beto bastos pimparel",
		"helder postiga",
	}
	f["united states"] = []string{
		"tim howard",
		"deandre yedlin",
		"omar gonzalez",
		"michael bradley",
		"matt besler",
		"john brooks",
		"damarcus beasley",
		"clint dempsey",
		"aron johannsson",
		"mikkel diskerud",
		"alejandro bedoya",
		"brad guzan",
		"jermaine jones",
		"brad davis",
		"kyle beckerman",
		"julian green",
		"jozy altidore",
		"chris wondolowski",
		"graham zusi",
		"geoff cameron",
		"timothy chandler",
		"nick rimando",
		"fabian johnson",
	}
	f["ghana"] = []string{
		"steven adams",
		"samuel inkoom",
		"asamoah gyan",
		"daniel opare",
		"michael essien",
		"afriyie acquah",
		"christian atsu",
		"emmanuel agyemang-badu",
		"kevin prince boateng",
		"andre ayew",
		"sulley muntari",
		"adam kwarasey",
		"jordan ayew",
		"albert adomah",
		"rashid sumaila",
		"fatau dauda",
		"mohammed rabiu",
		"majeed waris",
		"jonathan mensah",
		"kwadwo asamoah",
		"john boye",
		"mubarak wakaso",
		"harrison afful",
	}
	f["russia"] = []string{
		"igor akinfeev",
		"aleksey kozlov",
		"georgy shchennikov",
		"sergey ignashevich",
		"andrey semenov",
		"maksim kanunnikov",
		"igor denisov",
		"denis glushakov",
		"alexander kokorin",
		"alan dzagoev",
		"aleksandr kerzhakov",
		"yury lodygin",
		"vladimir granat",
		"vasily berezutskiy",
		"pavel mogilevetc",
		"sergey ryzhikov",
		"oleg shatov",
		"yuri zhirkov",
		"alexander samedov",
		"victor fayzulin",
		"alexey ionov",
		"andrey eshchenko",
		"dmitry kombarov",
	}
	f["south korea"] = []string{
		"sung-ryong jung",
		"chang-soo kim",
		"suk-young yun",
		"tae-hwi kwak",
		"young-gwon kim",
		"seok-ho hwang",
		"bo-kyung kim",
		"dae-sung ha",
		"heung-min son",
		"chu-young park",
		"keun-ho lee",
		"yong lee",
		"ja-cheol koo",
		"kook-young han",
		"jong-woo park",
		"sung-yueng ki",
		"chung-yong lee",
		"shin-wook kim",
		"dong-won ji",
		"jeong-ho hong",
		"seung-gyu kim",
		"joo-ho park",
		"bum-young lee",
	}
	f["belgium"] = []string{
		"thibaut courtois",
		"toby alderweireld",
		"thomas vermaelen",
		"vincent kompany",
		"jan vertonghen",
		"axel witsel",
		"kevin de bruyne",
		"marouane fellaini",
		"romelu lukaku",
		"eden hazard",
		"kevin mirallas",
		"simon mignolet",
		"sammy bossut",
		"dries mertens",
		"daniel van buyten",
		"steven defour",
		"divock origi",
		"nicolas lombaerts",
		"mousa dembele",
		"adnan januzaj",
		"anthony vanden borre",
		"nacer chadli",
		"laurent ciman",
	}
	f["algeria"] = []string{
		"cedric si mohammed",
		"madjid bougherra",
		"faouzi ghoulam",
		"esseid belkalem",
		"rafik halliche",
		"djamel mesbah",
		"hassan yebda",
		"medhi lacen",
		"nabil ghilas",
		"sofiane feghouli",
		"yacine brahimi",
		"carl medjani",
		"islam slimani",
		"nabil bentaleb",
		"el arabi soudani",
		"mohamed zemmamouche",
		"liassine cadamuro",
		"abdelmoumene djabou",
		"saphir taider",
		"aissa mandi",
		"riyad mahrez",
		"mehdi mostefa",
		"rais m'bolhi",
	}
	F := dataset.SearchSystem_{}
	F.Constructor() // important
	F.Include(FIFAWC2014Key, SportKey, FootballKey, f, true, false, false)
	return F
}

func Laliga2009() dataset.SearchSystem_ {
	f := map[string][]string{}
	f["barcelona"] = []string{
		"víctor valdés",
		"xavi",
		"samuel eto'o",
		"dani alves",
		"lionel messi",
		"carles puyol",
		"gerard piqué",
		"éric abidal",
		"thierry henry",
		"rafael márquez",
		"yaya touré",
		"andrés iniesta",
		"seydou keita",
		"sergio busquets",
		"eiður guðjohnsen",
		"sylvinho",
		"martín cáceres",
		"alexander hleb",
		"bojan krkić",
		"pedro",
		"víctor sánchez",
		"josé manuel pinto",
		"xavi torres",
		"oier olazábal",
		"marc muniesa",
		"jeffrén suárez",
		"alberto botía",
		"thiago alcántara",
		"abraham gonzález",
	}
	f["real madrid"] = []string{
		"iker casillas",
		"raúl",
		"sergio ramos",
		"gonzalo higuaín",
		"fabio cannavaro",
		"pepe",
		"arjen robben",
		"fernando gago",
		"gabriel heinze",
		"marcelo",
		"lassana diarra",
		"wesley sneijder",
		"rafael van der vaart",
		"guti",
		"klaas-jan huntelaar",
		"christoph metzelder",
		"miguel torres",
		"mahamadou diarra",
		"míchel salgado",
		"ruud van nistelrooy",
		"royston drenthe",
		"rubén",
		"javi garcía",
		"javier saviola",
		"gary kagelmacher",
		"miguel palanca",
		"daniel parejo",
		"julien faubert",
		"marcos tébar",
		"alberto bueno",
	}
	f["sevilla"] = []string{
		"andrés palop",
		"sébastien squillaci",
		"jesús navas",
		"fernando navarro",
		"romaric",
		"frédéric kanouté",
		"renato",
		"julien escudé",
		"aldo duscher",
		"adriano",
		"luís fabiano",
		"aquivaldo mosquera",
		"diego capel",
		"enzo maresca",
		"david prieto",
		"abdoulay konko",
		"ivica dragutinović",
		"diego perotti",
		"federico fazio",
		"josé ángel crespo",
		"lautaro acosta",
		"javi varas",
		"javier chevantón",
		"arouna koné",
		"tom de mul",
		"emiliano armenteros",
		"teemu pukki",
		"fernando rodríguez",
		"josé carlos",
	}
	f["atletico madrid"] = []string{
		"sergio agüero",
		"paulo assunção",
		"tomáš ujfaluši",
		"leo franco",
		"diego forlán",
		"simão sabrosa",
		"maxi rodríguez",
		"john heitinga",
		"mariano pernía",
		"raúl garcía",
		"luis amaranto perea",
		"pablo ibáñez",
		"antonio lópez",
		"maniche",
		"florent sinama pongolle",
		"giourkas seitaridis",
		"grégory coupet",
		"éver banega",
		"luis garcía",
		"ignacio camacho",
		"álvaro domínguez",
		"miguel",
	}
	f["villarreal"] = []string{
		"diego lópez",
		"joan capdevila",
		"diego godín",
		"sebastián eguren",
		"joseba llorente",
		"giuseppe rossi",
		"gonzalo rodríguez",
		"santi cazorla",
		"marcos senna",
		"robert pirès",
		"javi venta",
		"ángel lópez",
		"ariel ibagaza",
		"cani",
		"fabricio fuentes",
		"bruno soriano",
		"nihat kahveci",
		"matías fernández",
		"guillermo franco",
		"pascal cygan",
		"jozy altidore",
		"edmílson",
		"javier matilla",
		"jordi pablo",
		"joan tomàs",
		"mario gaspar",
	}
	f["valencia"] = []string{
		"juan mata",
		"raúl albiol",
		"david villa",
		"miguel monteiro",
		"joaquín",
		"david albelda",
		"emiliano moretti",
		"carlos marchena",
		"alexis",
		"rubén baraja",
		"manuel fernandes",
		"renan brito soares",
		"hedwiges maduro",
		"césar sánchez",
		"david silva",
		"pablo hernández",
		"edu gaspar",
		"fernando morientes",
		"vicente rodríguez",
		"asier del horno",
		"miguel ángel angulo",
		"míchel",
		"vicente guaita",
		"iván helguera",
		"thiago carleto",
		"curro torres",
	}
	f["deportivo la coruna"] = []string{
		"filipe luís",
		"daniel aranzubia",
		"alberto lopo",
		"juan rodríguez",
		"zé castro",
		"joan verdú",
		"andrés guardado",
		"ángel lafita",
		"manuel pablo",
		"sergio",
		"julian",
		"pablo álvarez",
		"rodolfo bodipo",
		"laure",
		"antonio tomás",
		"lassad nouioui",
		"diego colotto",
		"riki",
		"adrián lópez",
		"mista",
		"juan carlos valerón",
		"cristian hidalgo",
		"omar bravo",
		"pablo amo",
		"gustavo munúa",
	}
	f["malaga"] = []string{
		"jesús gámez",
		"nabil baha",
		"weligton oliveira",
		"duda",
		"eliseu",
		"apoño",
		"javier calleja",
		"iñaki goitia",
		"hélder rosário",
		"lolo",
		"adrián lópez",
		"albert luque",
		"nacho",
		"miguel ángel",
		"ibán cuadrado",
		"francesc arnau",
		"manolo gaspar",
		"pablo",
		"salva ballesta",
		"fernando",
		"cheli",
		"adriano",
		"josé juan luque",
		"pere martí",
		"adriano rossato",
	}
	f["mallorca"] = []string{
		"juan arango",
		"aritz aduriz",
		"josé luis martí",
		"fernando varela",
		"josé manuel jurado",
		"david navarro",
		"josé nunes",
		"cléber santana",
		"enrique corrales",
		"josemi",
		"lionel scaloni",
		"mario suárez",
		"iván ramis",
		"ayoze díaz díaz",
		"dudu aouate",
		"miguel ángel moyá",
		"germán lux",
		"pierre webó",
		"alhassane keita",
		"chory castro",
		"óscar trejo",
		"juanmi callejón",
	}
	f["espanyol"] = []string{
		"carlos kameni",
		"daniel jarque",
		"luis garcía",
		"nenê",
		"sergio sánchez",
		"moisés hurtado",
		"nicolás pareja",
		"raúl tamudo",
		"román martínez",
		"iván",
		"grégory béranger",
		"ferran corominas",
		"david garcía",
		"iván alonso",
		"javier chica",
		"josé callejón",
		"ángel martínez",
		"francisco rufete",
		"milan smiljanić",
		"jesús maría lacruz",
		"valdo",
		"marc torrejón",
		"steve finnan",
		"óscar sielva",
		"jonathan soriano",
		"cristian álvarez",
	}
	f["almeria"] = []string{
		"bruno",
		"álvaro negredo",
		"mané",
		"diego alves",
		"juan manuel ortiz",
		"hernán pellerano",
		"juanito",
		"albert crusat",
		"pablo piatti",
		"carlos garcía",
		"kalu uche",
		"julio álvarez",
		"santiago acasiete",
		"fernando soriano",
		"iriney",
		"corona",
		"chico flores",
		"esteban",
		"guilherme santos",
		"miguel ángel nieto",
		"josé ortiz bernal",
		"esteban solari",
		"michel",
		"natalio",
	}
	f["racing santander"] = []string{
		"toño",
		"iván marcano",
		"mehdi lacen",
		"óscar serrano",
		"jonathan pereira",
		"pedro munitis",
		"gonzalo colsa",
		"pablo pinillos caro",
		"ezequiel garay",
		"juan valera espín",
		"nikola žigić",
		"césar navas",
		"mohamed tchité",
		"lászló sepsi",
		"peter luccin",
		"toni moral",
		"josé moratón",
		"christian",
		"oriol lozano",
		"juanjo expósito",
		"fabio coltorti",
		"edu bedia",
		"luis fernández",
		"jorge gonçalves",
		"jorge lópez",
		"sergio canales",
		"jesús berrocal",
		"luisma",
		"uri santos",
		"josé picón",
	}
	f["athletic club"] = []string{
		"gorka iraizoz",
		"fernando llorente",
		"andoni iraola",
		"javi martínez",
		"fernando amorebieta",
		"aitor ocio",
		"pablo orbaiz",
		"david lópez",
		"markel susaeta",
		"francisco yeste",
		"mikel balenziaga",
		"koikili lertxundi",
		"ion vélez",
		"igor gabilondo",
		"gaizka toquero",
		"carlos gurpegui",
		"ustaritz",
		"xabier etxeita",
		"joseba etxeberria",
		"joseba garmendia",
	}
	f["sporting gijon"] = []string{
		"diego castro",
		"rafel sastre",
		"diego camacho",
		"gerard autet",
		"carmelo gonzález",
		"míchel",
		"roberto canella",
		"mate bilić",
		"sergio matabuena",
		"iván hernández",
		"david barral",
		"luis morán",
		"iván cuéllar",
		"neru",
		"raúl cámara",
		"iñaki lafuente",
		"pedro",
		"kike mateo",
		"josé ángel",
		"jorge garcía",
		"tati maldonado",
		"sergio sánchez",
		"alberto lora",
		"andreu guerao",
		"jürgen colin",
		"omar sampedro",
	}
	f["osasuna"] = []string{
		"césar azpilicueta",
		"javad nekounam",
		"juanfran",
		"miguel flaño",
		"jaroslav plašil",
		"francisco puñal",
		"nacho monreal",
		"roberto",
		"masoud shojaei",
		"walter pandiani",
		"sergio",
		"krisztián vadócz",
		"ricardo",
		"josetxo",
		"oier sanjurjo",
		"césar cruchaga",
		"rovérsio",
		"enrique sola",
		"dady",
		"santiago ezquerro",
		"javier portillo",
		"javier flaño",
		"héctor font",
		"antonio hidalgo",
		"jokin esparza",
		"ludovic delporte",
		"sunny",
		"rúper",
	}
	f["valladolid"] = []string{
		"álvaro rubio",
		"alberto marcos rey",
		"jonathan sesma",
		"pedro león",
		"pedro lópez muñoz",
		"luis prieto zalbidegoitia",
		"borja fernández",
		"sergio asenjo",
		"henok goitom",
		"víctor",
		"josé garcía calvo",
		"fabián canobbio",
		"javier baraja",
		"ángel vivar dorado",
		"justo villar",
		"iñaki bea jauregi",
		"nano",
		"damián escudero",
		"haris medunjanin",
		"óscar sánchez",
		"marcos aguirre",
		"bartholomew ogbeche",
		"pedro oldoni",
		"kike lópez",
		"jesús rueda",
		"alberto",
	}
	f["getafe"] = []string{
		"cata díaz",
		"javier casquero",
		"esteban granero",
		"david cortés",
		"mario",
		"lucas licht",
		"jaime gavilán",
		"roberto soldado",
		"juan ángel albín",
		"eugen polanski",
		"manu del moral",
		"ikechukwu uche",
		"jacobo",
		"fabio celestini",
		"cosmin contra",
		"pato abbondanzieri",
		"rafa",
		"david belenguer",
		"joffre guerrón",
		"ibrahim kaş",
		"vladimir stojković",
		"óscar ustari",
		"adrián gonzález",
		"kepa blanco",
		"mario cotelo",
	}
	f["real betis"] = []string{
		"juanito",
		"arzu",
		"nélson marcos",
		"achille emaná",
		"fernando vega",
		"mehmet aurélio",
		"sergio garcía",
		"capi",
		"ricardo",
		"damià abella",
		"mark gonzález",
		"melli",
		"casto",
		"ricardo oliveira",
		"juanma",
		"edu",
		"mariano pavone",
		"fabián monzón",
		"alberto rivera",
		"david rivas",
		"juande",
		"josé mari",
		"xisco",
		"josé cañas",
		"david odonkor",
		"branko ilić",
		"marko babić",
		"diego segura",
		"lima",
	}
	f["numancia"] = []string{
		"juan pablo colinas",
		"domingo cisma",
		"josé barkero",
		"txomin nagore",
		"juanra",
		"boris",
		"asier goiria",
		"javier del pino",
		"sergio ortega",
		"dimas delgado",
		"juan carlos moreno",
		"carlos bellvís",
		"césar palacios",
		"carlos aranda",
		"mario",
		"manuel pavón",
		"gorka brit",
		"juan quero",
		"felipe guréndez",
		"raúl bravo",
		"egoitz jaio gabiola",
		"álvaro antón",
		"antonio guayre",
		"marián kelemen",
		"lago junior",
		"toché",
	}
	f["recreativo"] = []string{
		"asier riesgo",
		"nasief morris",
		"javier camuñas",
		"javi fuego",
		"aitor tornavaca",
		"jesús vázquez",
		"iago bouzón",
		"adrián colunga",
		"césar arzo",
		"sisi",
		"rafael barber",
		"josé manuel casado",
		"marco ruben",
		"poli",
		"javi guerrero",
		"andrés lamas",
		"alain nef",
		"cristian maidana",
		"kanga akalé",
		"sebastián nayar",
		"beto",
		"pablo oliveira",
		"ersen martin",
		"quique álvarez",
		"mario garcía pizarraya",
		"joselito",
		"juan villar",
	}
	F := dataset.SearchSystem_{}
	F.Constructor() // important
	F.Include(Laliga2009Key, SportKey, FootballKey, f, true, false, false)
	return F
}

func PremierLeague2012() dataset.SearchSystem_ {
	f := map[string][]string{}
	f["manchester city"] = []string{
		"joe hart",
		"david silva",
		"vincent kompany",
		"gareth barry",
		"yaya touré",
		"sergio agüero",
		"joleon lescott",
		"gaël clichy",
		"samir nasri",
		"micah richards",
		"pablo zabaleta",
		"james milner",
		"edin džeko",
		"mario balotelli",
		"nigel de jong",
		"adam johnson",
		"aleksandar kolarov",
		"kolo touré",
		"carlos tevez",
		"stefan savić",
		"david pizarro",
		"owen hargreaves",
		"abdul razak",
		"nedum onuoha",
	}
	f["manchester united"] = []string{
		"patrice evra",
		"wayne rooney",
		"david de gea",
		"rio ferdinand",
		"jonny evans",
		"michael carrick",
		"phil jones",
		"nani",
		"danny welbeck",
		"antonio valencia",
		"ashley young",
		"javier hernández",
		"ryan giggs",
		"chris smalling",
		"paul scholes",
		"park ji-sung",
		"rafael",
		"anders lindegaard",
		"anderson",
		"darren fletcher",
		"nemanja vidić",
		"dimitar berbatov",
		"tom cleverley",
		"fábio",
		"ben amos",
		"darron gibson",
		"michael owen",
		"paul pogba",
		"zeki fryers",
		"federico macheda",
		"will keane",
	}
	f["arsenal"] = []string{
		"wojciech szczęsny",
		"robin van persie",
		"alexandre song",
		"laurent koscielny",
		"theo walcott",
		"mikel arteta",
		"thomas vermaelen",
		"aaron ramsey",
		"per mertesacker",
		"bacary sagna",
		"tomáš rosický",
		"gervinho",
		"kieran gibbs",
		"johan djourou",
		"andré santos",
		"yossi benayoun",
		"andrey arshavin",
		"francis coquelin",
		"alex oxlade-chamberlain",
		"carl jenkinson",
		"emmanuel frimpong",
		"ignasi miquel",
		"marouane chamakh",
		"samir nasri",
		"armand traoré",
		"thierry henry",
		"abou diaby",
		"nico yennaris",
		"henri lansbury",
		"nicklas bendtner",
		"sébastien squillaci",
		"park chu-young",
	}
	f["tottenham"] = []string{
		"brad friedel",
		"kyle walker",
		"gareth bale",
		"luka modrić",
		"benoît assou-ekotto",
		"younès kaboul",
		"emmanuel adebayor",
		"scott parker",
		"rafael van der vaart",
		"ledley king",
		"aaron lennon",
		"sandro",
		"william gallas",
		"jermain defoe",
		"niko kranjčar",
		"jake livermore",
		"michael dawson",
		"louis saha",
		"danny rose",
		"sébastien bassong",
		"vedran ćorluka",
		"peter crouch",
		"roman pavlyuchenko",
		"ryan nelsen",
		"tom huddlestone",
		"giovani dos santos",
		"steven pienaar",
		"adam smith",
		"cameron lancaster",
	}
	f["newcastle united"] = []string{
		"tim krul",
		"jonás gutiérrez",
		"danny simpson",
		"fabricio coloccini",
		"yohan cabaye",
		"demba ba",
		"cheick tioté",
		"ryan taylor",
		"mike williamson",
		"davide santon",
		"gabriel obertan",
		"hatem ben arfa",
		"leon best",
		"steven taylor",
		"james perch",
		"danny guthrie",
		"papiss cissé",
		"shola ameobi",
		"peter løvenkrands",
		"joey barton",
		"haris vučkić",
		"dan gosling",
		"sammy ameobi",
		"sylvain marveaux",
		"shane ferguson",
		"alan smith",
	}
	f["chelsea"] = []string{
		"petr čech",
		"john terry",
		"ashley cole",
		"juan mata",
		"ramires",
		"daniel sturridge",
		"branislav ivanović",
		"frank lampard",
		"josé bosingwa",
		"raul meireles",
		"fernando torres",
		"david luiz",
		"didier drogba",
		"john obi mikel",
		"florent malouda",
		"oriol romeu",
		"michael essien",
		"gary cahill",
		"salomon kalou",
		"ryan bertrand",
		"nicolas anelka",
		"paulo ferreira",
		"alex",
		"henrique hilário",
		"ross turnbull",
		"romelu lukaku",
		"sam hutchinson",
		"josh mceachran",
		"yossi benayoun",
	}
	f["everton"] = []string{
		"tim howard",
		"leighton baines",
		"marouane fellaini",
		"tony hibbert",
		"phil jagielka",
		"john heitinga",
		"leon osman",
		"tim cahill",
		"sylvain distin",
		"phil neville",
		"louis saha",
		"steven pienaar",
		"séamus coleman",
		"darron gibson",
		"jack rodwell",
		"royston drenthe",
		"nikica jelavić",
		"denis stracqualursi",
		"landon donovan",
		"diniyar bilyaletdinov",
		"victor anichebe",
		"magaye gueye",
		"apostolos vellios",
		"ross barkley",
		"shane duffy",
		"james mcfadden",
		"mikel arteta",
		"jermaine beckford",
		"conor mcaleny",
		"jose baxter",
	}
	f["liverpool"] = []string{
		"pepe reina",
		"josé enrique",
		"martin škrtel",
		"jordan henderson",
		"luis suárez",
		"stewart downing",
		"charlie adam",
		"daniel agger",
		"dirk kuyt",
		"glen johnson",
		"andy carroll",
		"jamie carragher",
		"jay spearing",
		"craig bellamy",
		"steven gerrard",
		"lucas leiva",
		"martin kelly",
		"maxi rodríguez",
		"jonjo shelvey",
		"jon flanagan",
		"sebastián coates",
		"doni",
		"fábio aurélio",
		"brad jones",
		"raul meireles",
		"raheem sterling",
	}
	f["fulham"] = []string{
		"brede hangeland",
		"clint dempsey",
		"john arne riise",
		"mousa dembélé",
		"danny murphy",
		"mark schwarzer",
		"damien duff",
		"stephen kelly",
		"philippe senderos",
		"aaron hughes",
		"bryan ruiz",
		"bobby zamora",
		"chris baird",
		"andrew johnson",
		"steve sidwell",
		"pavel pogrebnyak",
		"dickson etuhu",
		"mahamadou diarra",
		"david stockdale",
		"kerim frei",
		"zdeněk grygera",
		"simon davies",
		"orlando sá",
		"pajtim kasami",
		"alexander kačaniklić",
		"matthew briggs",
		"marcel gecov",
		"marcello trotta",
	}
	f["west bromwich"] = []string{
		"ben foster",
		"youssouf mulumbu",
		"jonas olsson",
		"gareth mcauley",
		"jerome thomas",
		"chris brunt",
		"peter odemwingie",
		"shane long",
		"james morrison",
		"nicky shorey",
		"steven reid",
		"paul scharner",
		"billy jones",
		"graham dorrans",
		"liam ridgewell",
		"marc-antoine fortuné",
		"keith andrews",
		"simon cox",
		"gabriel tamaș",
		"somen tchoyi",
		"craig dawson",
		"zoltán gera",
		"gonzalo jara",
		"george thorne",
		"márton fülöp",
	}
	f["swansea"] = []string{
		"michel vorm",
		"ashley williams",
		"scott sinclair",
		"neil taylor",
		"leon britton",
		"àngel rangel",
		"danny graham",
		"joe allen",
		"nathan dyer",
		"steven caulker",
		"gylfi sigurðsson",
		"wayne routledge",
		"garry monk",
		"mark gower",
		"kemy agustien",
		"jazz richards",
		"leroy lita",
		"luke moore",
		"stephen dobbie",
		"andrea orlandi",
		"alan tate",
		"josh mceachran",
		"gerhard tremmel",
		"federico bessone",
		"vangelis moras",
	}
	f["norwich city"] = []string{
		"john ruddy",
		"russell martin",
		"kyle naughton",
		"wes hoolahan",
		"bradley johnson",
		"grant holt",
		"anthony pilkington",
		"david fox",
		"steve morison",
		"elliott bennett",
		"andrew surman",
		"zak whitbread",
		"marc tierney",
		"andrew crofts",
		"leon barnett",
		"elliott ward",
		"adam drury",
		"jonny howson",
		"simeon jackson",
		"ryan bennett",
		"daniel ayala",
		"ritchie de laet",
		"simon lappin",
		"chris martin",
		"aaron wilbraham",
		"james vaughan",
		"declan rudd",
	}
	f["sunderland"] = []string{
		"stéphane sessègnon",
		"sebastian larsson",
		"jack colback",
		"simon mignolet",
		"phil bardsley",
		"john o'shea",
		"kieran richardson",
		"nicklas bendtner",
		"michael turner",
		"lee cattermole",
		"craig gardner",
		"james mcclean",
		"wes brown",
		"david vaughan",
		"matthew kilgallon",
		"keiren westwood",
		"titus bramble",
		"ahmed elmohamady",
		"fraizer campbell",
		"connor wickham",
		"wayne bridge",
		"anton ferdinand",
		"asamoah gyan",
		"ji dong-won",
		"sotirios kyrgiakos",
		"david meyler",
		"craig gordon",
		"ryan noble",
	}
	f["stocke city"] = []string{
		"jonathan walters",
		"ryan shawcross",
		"marc wilson",
		"robert huth",
		"peter crouch",
		"matthew etherington",
		"glenn whelan",
		"dean whitehead",
		"asmir begović",
		"andy wilkinson",
		"jermaine pennant",
		"rory delap",
		"thomas sørensen",
		"jonathan woodgate",
		"ryan shotton",
		"matt upson",
		"kenwyne jones",
		"wilson palacios",
		"cameron jerome",
		"ricardo fuller",
		"salif diao",
		"danny higginbotham",
		"danny pugh",
	}
	f["wigan athletic"] = []string{
		"ali al-habsi",
		"maynor figueroa",
		"gary caldwell",
		"victor moses",
		"james mccarthy",
		"emmerson boyce",
		"antolín alcaraz",
		"franco di santo",
		"jordi gómez",
		"james mcarthur",
		"mohamed diamé",
		"jean beausejour",
		"ben watson",
		"ronnie stam",
		"david jones",
		"hugo rodallega",
		"conor sammon",
		"shaun maloney",
		"steve gohouri",
		"adrián lópez",
		"albert crusat",
		"patrick van aanholt",
		"callum mcmanaman",
	}
	f["aston villa"] = []string{
		"stephen warnock",
		"shay given",
		"gabriel agbonlahor",
		"james collins",
		"alan hutton",
		"richard dunne",
		"stiliyan petrov",
		"charles n'zogbia",
		"darren bent",
		"stephen ireland",
		"chris herd",
		"emile heskey",
		"carlos cuéllar",
		"marc albrighton",
		"ciaran clark",
		"barry bannan",
		"fabian delph",
		"eric lichaj",
		"brad guzan",
		"nathan baker",
		"gary gardner",
		"andreas weimann",
		"robbie keane",
		"luke young",
		"nathan delfouneso",
		"jermaine jenas",
		"samir carruthers",
	}
	f["queens park rangers"] = []string{
		"paddy kenny",
		"anton ferdinand",
		"joey barton",
		"shaun derry",
		"shaun wright-phillips",
		"jamie mackie",
		"adel taarabt",
		"luke young",
		"alejandro faurlín",
		"clint hill",
		"armand traoré",
		"nedum onuoha",
		"danny gabbidon",
		"bobby zamora",
		"taye taiwo",
		"heiðar helguson",
		"jay bothroyd",
		"fitz hall",
		"ákos buzsáky",
		"samba diakité",
		"djibril cissé",
		"matthew connolly",
		"radek černý",
		"tommy smith",
		"bradley orr",
		"dj campbell",
		"patrick agyemang",
		"bruno perone",
		"robert hulse",
		"kieron dyer",
		"hogan ephraim",
		"federico macheda",
		"michael harriman",
		"jason puncheon",
		"bruno andrade",
	}
	f["bolton wanderers"] = []string{
		"nigel reo-coker",
		"martin petrov",
		"mark davies",
		"chris eagles",
		"david n'gog",
		"david wheater",
		"zat knight",
		"kevin davies",
		"grétar steinsson",
		"ádám bogdán",
		"sam ricketts",
		"gary cahill",
		"jussi jääskeläinen",
		"fabrice muamba",
		"ivan klasnić",
		"paul robinson",
		"darren pratley",
		"tim ream",
		"dedryck boyata",
		"ryo miyaichi",
		"marcos alonso",
		"tuncay şanlı",
		"joe riley",
		"ricardo gardner",
		"tyrone mears",
		"gaël kakuta",
		"marvin sordell",
		"josh vela",
		"lee chung-yong",
		"robbie blake",
	}
	f["blackburn rovers"] = []string{
		"paul robinson",
		"junior hoilett",
		"morten gamst pedersen",
		"steven nzonzi",
		"jason lowe",
		"yakubu aiyegbeni",
		"scott dann",
		"mauro formica",
		"martin olsson",
		"gaël givet",
		"david dunn",
		"grant hanley",
		"christopher samba",
		"marcus olsson",
		"radosav petrović",
		"bradley orr",
		"rubén rochina",
		"míchel salgado",
		"jason roberts",
		"david goodwillie",
		"adam henley",
		"simon vukčević",
		"anthony modeste",
		"mark bunn",
		"brett emerton",
		"jake kean",
		"ryan nelsen",
		"josh morris",
		"vince grella",
		"nick blackman",
		"jordan slew",
	}
	f["wolverhampton wanderers"] = []string{
		"stephen ward",
		"wayne hennessey",
		"matthew jarvis",
		"karl henry",
		"christophe berra",
		"richard stearman",
		"roger johnson",
		"kevin doyle",
		"steven fletcher",
		"david edwards",
		"jamie o'hara",
		"stephen hunt",
		"michael kightly",
		"ronald zubar",
		"kevin foley",
		"sébastien bassong",
		"sylvan ebanks-blake",
		"nenad milijaš",
		"david davis",
		"emmanuel frimpong",
	}
	F := dataset.SearchSystem_{}
	F.Constructor() // important
	F.Include(PremierLeague2012Key, SportKey, FootballKey, f, true, false, false)
	return F
}

func SeriaA2014() dataset.SearchSystem_ {
	f := map[string][]string{}
	f["juventus"] = []string{
		"paul pogba",
		"gianluigi buffon",
		"kwadwo asamoah",
		"giorgio chiellini",
		"carlos tevez",
		"fernando llorente",
		"andrea pirlo",
		"leonardo bonucci",
		"arturo vidal",
		"andrea barzagli",
		"stephan lichtsteiner",
		"claudio marchisio",
		"martín cáceres",
		"angelo ogbonna",
		"mauricio isla",
		"simone padoin",
		"sebastian giovinco",
		"marco storari",
		"mirko vučinić",
		"dani osvaldo",
		"federico peluso",
		"fabio quagliarella",
		"paolo de ceglie",
		"rubinho",
		"marco motta",
		"simone pepe",
	}
	f["roma"] = []string{
		"morgan de sanctis",
		"leandro castán",
		"medhi benatia",
		"miralem pjanić",
		"daniele de rossi",
		"gervinho",
		"maicon sisenando",
		"kevin strootman",
		"alessandro florenzi",
		"francesco totti",
		"adem ljajić",
		"radja nainggolan",
		"dodô",
		"mattia destro",
		"vasilis torosidis",
		"federico balzaretti",
		"alessio romagnoli",
		"rodrigo taddei",
		"marco borriello",
		"michael bradley",
		"rafael tolói",
		"michel bastos",
		"nicolás burdisso",
		"marquinho",
		"łukasz skorupski",
		"tin jedvaj",
		"federico ricci",
		"luca mazzitelli",
		"gianluca caprari",
	}
	f["napoli"] = []string{
		"josé callejón",
		"raúl albiol",
		"gökhan inler",
		"pepe reina",
		"gonzalo higuaín",
		"lorenzo insigne",
		"federico fernández",
		"marek hamšík",
		"christian maggio",
		"dries mertens",
		"blerim džemaili",
		"goran pandev",
		"valon behrami",
		"miguel britos",
		"faouzi ghoulam",
		"anthony réveillère",
		"jorginho",
		"giandomenico mesto",
		"pablo armero",
		"henrique",
		"rafael cabral",
		"duván zapata",
		"juan zúñiga",
		"paolo cannavaro",
		"toni doblas",
		"josip radošević",
		"bruno uvini",
		"roberto colombo",
		"igor łasicki",
		"davide bariti",
	}
	f["internazionale"] = []string{
		"rodrigo palacio",
		"samir handanović",
		"yuto nagatomo",
		"esteban cambiasso",
		"jonathan moreira",
		"rolando",
		"juan jesus",
		"fredy guarín",
		"ricky álvarez",
		"andrea ranocchia",
		"hugo campagnaro",
		"mateo kovačić",
		"walter samuel",
		"hernanes",
		"saphir taïder",
		"mauro icardi",
		"zdravko kuzmanović",
		"danilo d'ambrosio",
		"diego milito",
		"javier zanetti",
		"juan pablo carrizo",
		"álvaro pereira",
		"marco andreolli",
		"rubén botta",
		"ishak belfodil",
		"wallace oliveira",
		"gaby mudingayi",
		"federico bonazzoli",
	}
	f["parma"] = []string{
		"antonio mirante",
		"marco parolo",
		"mattia cassani",
		"alessandro lucarelli",
		"marco marchionni",
		"jonathan biabiany",
		"antonio cassano",
		"massimo gobbi",
		"amauri",
		"afriyie acquah",
		"felipe dal belo",
		"walter gargano",
		"gabriel paletta",
		"cristian molinaro",
		"raffaele palladino",
		"ezequiel schelotto",
		"nicola sansone",
		"aleandro rosi",
		"jaime valdés",
		"pedro mendes",
		"gianni munari",
		"pavol bajza",
		"yohan benalouane",
		"joel obi",
		"djamel mesbah",
		"stefano okaka",
		"josé mauri",
		"daniele galloppa",
		"nicola pavarini",
		"alberto cerri",
	}
	f["torino"] = []string{
		"daniele padelli",
		"matteo darmian",
		"emiliano moretti",
		"alessio cerci",
		"kamil glik",
		"giuseppe vives",
		"ciro immobile",
		"omar el kaddouri",
		"nikola maksimović",
		"cesare bovo",
		"alexander farnerud",
		"danilo d'ambrosio",
		"jasmin kurtić",
		"migjen basha",
		"matteo brighi",
		"giovanni pasquale",
		"riccardo meggiorini",
		"salvatore masiello",
		"paulo vitor barreto",
		"alessandro gazzi",
		"guillermo daniel rodríguez",
		"panagiotis tachtsidis",
		"nicola bellomo",
		"marko vešović",
		"marcelo larrondo",
		"lys gomis",
	}
	f["milan"] = []string{
		"nigel de jong",
		"christian abbiati",
		"riccardo montolivo",
		"kaká",
		"mario balotelli",
		"philippe mexès",
		"cristián zapata",
		"sulley muntari",
		"kévin constant",
		"urby emanuelson",
		"andrea poli",
		"adil rami",
		"ignazio abate",
		"mattia de sciglio",
		"daniele bonera",
		"robinho",
		"adel taarabt",
		"keisuke honda",
		"valter birsa",
		"alessandro matri",
		"giampaolo pazzini",
		"cristian zaccardo",
		"antonio nocerino",
		"gabriel",
		"marco amelia",
		"michael essien",
		"matías silvestre",
		"riccardo saponara",
		"bryan cristante",
		"m'baye niang",
		"stephan el shaarawy",
		"andrea petagna",
	}
	f["lazio"] = []string{
		"antonio candreva",
		"senad lulić",
		"ștefan radu",
		"cristian ledesma",
		"lorik cana",
		"lucas biglia",
		"miroslav klose",
		"federico marchetti",
		"abdoulay konko",
		"ogenyi onazi",
		"giuseppe biava",
		"etrit berisha",
		"álvaro gonzález",
		"luis pedro cavanda",
		"keita baldé",
		"andré dias",
		"hernanes",
		"michaël ciani",
		"bruno pereirinha",
		"diego novaretti",
		"brayan perea",
		"stefano mauri",
		"felipe anderson",
		"ederson",
		"sergio floccari",
		"hélder postiga",
		"joseph minala",
		"mamadou tounkara",
		"gaël kakuta",
		"luca crecco",
	}
	f["hellas verona"] = []string{
		"rafael",
		"luca toni",
		"fabrizio cacciatore",
		"emil hallfreðsson",
		"rômulo",
		"vangelis moras",
		"juan iturbe",
		"domenico maietta",
		"alessandro agostini",
		"jorginho",
		"juanito",
		"rafael marques",
		"michelangelo albertazzi",
		"boško janković",
		"alejandro gonzález",
		"marquinho",
		"marco donadel",
		"massimo donati",
		"raphael martinho",
		"jacopo sala",
		"ezequiel cirigliano",
		"iván pillud",
		"daniele cacia",
		"matteo bianchetti",
		"michael rabušic",
		"nícolas andrade",
		"simon laner",
		"godfred donsah",
		"samuele longo",
	}
	f["atalanta"] = []string{
		"germán denis",
		"andrea consigli",
		"carlos carmona",
		"giacomo bonaventura",
		"luca cigarini",
		"guglielmo stendardo",
		"maximiliano moralez",
		"cristian raimondi",
		"davide brivio",
		"mario yepes",
		"cristiano del grosso",
		"yohan benalouane",
		"daniele baselli",
		"stefano lucchini",
		"giulio migliaccio",
		"marko livaja",
		"marcelo estigarribia",
		"franco brienza",
		"gianpaolo bellini",
		"michele canini",
		"giuseppe de luca",
		"moussa koné",
		"lionel scaloni",
		"constantin nica",
		"marco sportiello",
		"riccardo cazzola",
		"guido marilungo",
		"rubén bentancourt",
		"mattia caldara",
		"joakim olausson",
		"luigi giorgi",
	}
	f["sampdoria"] = []string{
		"lorenzo de silvestri",
		"angelo da costa júnior",
		"shkodran mustafi",
		"manolo gabbiadini",
		"angelo palombo",
		"daniele gastaldello",
		"éder",
		"vasco regini",
		"nenad krstičić",
		"pedro obiang",
		"roberto soriano",
		"andrea costa",
		"paweł wszołek",
		"gianluca sansone",
		"stefano okaka",
		"birkir bjarnason",
		"renan garcia",
		"maxi lópez",
		"davide gavazzi",
		"nicola pozzi",
		"vincenzo fiorillo",
		"michele fornasier",
		"gaetano berardi",
		"savvas gentsoglou",
		"antonino barillà",
		"bartosz salamon",
		"mirko eramo",
		"andrea petagna",
		"alessio sestu",
		"matías rodríguez",
		"paolo castellini",
		"mattia lombardo",
		"enzo maresca",
	}
	f["udinese"] = []string{
		"danilo larangeira",
		"roberto pereyra",
		"thomas heurtaux",
		"allan",
		"gabriel silva",
		"antonio di natale",
		"dušan basta",
		"maurizio domizzi",
		"emmanuel agyemang-badu",
		"giampiero pinzi",
		"andrea lazzari",
		"bruno fernandes",
		"simone scuffet",
		"luis muriel",
		"naldo",
		"željko brkić",
		"silvan widmer",
		"ivan kelava",
		"nicolás lópez",
		"maicosuel",
		"igor bubnjić",
		"hassan yebda",
		"douglas santos",
		"giovanni pasquale",
		"piotr zieliński",
		"mathias ranégie",
		"jadson",
	}
	f["genoa"] = []string{
		"mattia perin",
		"alberto gilardino",
		"luca antonelli",
		"luca antonini",
		"giovanni marchese",
		"andrea bertolacci",
		"šime vrsaljko",
		"daniele portanova",
		"matuzalém",
		"sebastien de maio",
		"davide biondini",
		"thomas manfredini",
		"nicolás burdisso",
		"moussa konaté",
		"stefano sturaro",
		"giannis fetfatzidis",
		"marco motta",
		"paolo de ceglie",
		"juraj kucka",
		"giuseppe sculli",
		"emanuele calaiò",
		"francesco lodi",
		"isaac cofie",
		"alessandro gamberini",
		"ricardo centurión",
		"cabral",
		"mario santana",
		"mario sampirisi",
		"albano bizzarri",
		"antonio floro flores",
		"adrian stoian",
	}
	f["cagliari"] = []string{
		"luca rossettini",
		"davide astori",
		"daniele conti",
		"daniele dessena",
		"marco sau",
		"vlada avramov",
		"francesco pisano",
		"nicola murru",
		"víctor ibarbo",
		"albin ekdal",
		"andrea cossu",
		"radja nainggolan",
		"mauricio pinilla",
		"danilo avelar",
		"gabriele perico",
		"sebastian eriksson",
		"nenê",
		"michael agazzi",
		"matías cabrera",
		"agim ibraimi",
		"matías vecino",
		"lorenzo ariaudo",
		"dario del fabro",
		"marco silvestri",
		"andrea tabanelli",
		"antonio adán",
		"adryan",
		"marios oikonomou",
		"alessandro bastrini",
		"antonio loi",
		"simone solinas",
	}
	f["chievo"] = []string{
		"luca rigoni",
		"nicolas frey",
		"boštjan cesar",
		"alberto paloschi",
		"përparim hetemaj",
		"cyril théréau",
		"ivan radovanović",
		"dario dainelli",
		"boukary dramé",
		"gennaro sardo",
		"christian puggioni",
		"simone bentivoglio",
		"michael agazzi",
		"marcelo estigarribia",
		"alessandro bernardini",
		"tiberio guarente",
		"alessio sestu",
		"roberto guana",
		"matteo rubin",
		"sergio pellissier",
		"claiton",
		"adrian stoian",
		"michele canini",
		"victor obinna",
		"paul papp",
		"dejan lazarević",
		"manuel pamić",
		"riccardo improta",
		"lorenzo squizzi",
		"maxwell acosty",
		"tomasz kupisz",
		"matteo ardemagni",
		"leandro paredes",
		"maodo malick mbaye",
		"adrián calello",
		"mamadou samassa",
	}
	f["sassuolo"] = []string{
		"gianluca pegolo",
		"francesco magnanelli",
		"alessandro longhi",
		"domenico berardi",
		"simone zaza",
		"marcello gazzola",
		"luca antei",
		"simone missiroli",
		"antonio floro flores",
		"paolo cannavaro",
		"paolo bianco",
		"luca marrone",
		"reto ziegler",
		"jasmin kurtić",
		"raman chibsah",
		"lorenzo ariaudo",
		"davide biondini",
		"francesco acerbi",
		"nicola sansone",
		"ezequiel schelotto",
		"sergio floccari",
		"pedro mendes",
		"lino marzorati",
		"matteo brighi",
		"aleandro rosi",
		"jonathan rossini",
		"karim laribi",
		"gaetano masucci",
		"diego farias",
		"emanuele terranova",
		"thomas manfredini",
		"alberto pomini",
		"antonio rosati",
		"raffaele pucino",
		"marius alexe",
		"leonardo pavoletti",
		"antonio sanabria",
		"ettore gliozzi",
	}
	f["catania"] = []string{
		"gonzalo bergessio",
		"pablo barrientos",
		"mariano julio izco",
		"mariano andújar",
		"lucas castro",
		"jaroslav plašil",
		"alexis rolín",
		"nicolás spolli",
		"gino peruzzi",
		"giuseppe bellusci",
		"cristiano biraghi",
		"francesco lodi",
		"fabián rinaudo",
		"fabián monzón",
		"norbert gyömbér",
		"pablo álvarez",
		"nicola legrottaglie",
		"alberto frison",
		"sebastián leto",
		"sergio almirón",
		"keko",
		"panagiotis tachtsidis",
		"tiberio guarente",
		"maxi lópez",
		"ciro capuano",
		"bruno petković",
		"francesco fedato",
		"kingsley boateng",
		"simone caruso",
		"souleymane doukara",
		"marco biagianti",
		"federico freire",
		"fabio aveni",
		"sergio garufi",
	}
	f["bologna"] = []string{
		"gianluca curci",
		"mikael antonsson",
		"györgy garics",
		"cesare natali",
		"archimede morleo",
		"panagiotis kone",
		"rene krhin",
		"lazaros christodoulopoulos",
		"rolando bianchi",
		"jonatan cristaldo",
		"alessandro diamanti",
		"diego pérez",
		"michele pazienza",
		"andrea mantovani",
		"nicolò cherubin",
		"frederik sørensen",
		"diego laxalt",
		"marek čech",
		"davide moscardelli",
		"josé ángel crespo",
		"robert acquafresca",
		"francesco della rocca",
		"erik friberg",
		"ibson",
		"dejan stojanović",
		"daniele paponi",
		"federico rodríguez",
		"denis alibec",
	}
	f["livorno"] = []string{
		"francesco bardi",
		"paulinho",
		"federico ceccherini",
		"emerson",
		"leandro greco",
		"marco biagianti",
		"ibrahima mbaye",
		"andrea luci",
		"andrea coda",
		"alfred duncan",
		"innocent emeghara",
		"marco benassi",
		"pasquale schiattarella",
		"leandro rinaudo",
		"djamel mesbah",
		"luca siligardi",
		"paolo castellini",
		"nahuel valentini",
		"ishak belfodil",
		"giuseppe gemiti",
		"cristiano piccini",
		"luca anania",
		"jonny mosquera",
		"alessandro lambrughi",
		"luca belingheri",
		"miguel borja",
		"federico dionisi",
		"daniele bartolini",
		"elia bruzzi",
		"elia bruzzi",
		"gabriele aldegani",
	}
	F := dataset.SearchSystem_{}
	F.Constructor() // important
	F.Include(SeriaA2014Key, SportKey, FootballKey, f, true, false, false)
	return F
}

func BuildFootball() FootballParcel {
	fw2002, fw2006, fw2010, fw2014, la2009, pe2012, se2014 := FIFAWC2002(), FIFAWC2006(), FIFAWC2010(), FIFAWC2014(), Laliga2009(), PremierLeague2012(), SeriaA2014()

	e2002, c2002, f2002, b2002, i2002 := fw2002.Manager(FIFAWC2002Key)
	e2006, c2006, f2006, b2006, i2006 := fw2006.Manager(FIFAWC2006Key)
	e2010, c2010, f2010, b2010, i2010 := fw2010.Manager(FIFAWC2010Key)
	e2014, c2014, f2014, b2014, i2014 := fw2014.Manager(FIFAWC2014Key)
	el2009, cl2009, fl2009, bl2009, il2009 := la2009.Manager(Laliga2009Key)
	ep2012, cp2012, fp2012, bp2012, ip2012 := pe2012.Manager(PremierLeague2012Key)
	es2014, cs2014, fs2014, bs2014, is2014 := se2014.Manager(SeriaA2014Key)
	parcel1 := SportsParcel{Event: e2002, Category: c2002, Field: f2002, Book: b2002, MappedItems: i2002}
	parcel2 := SportsParcel{Event: e2006, Category: c2006, Field: f2006, Book: b2006, MappedItems: i2006}
	parcel3 := SportsParcel{Event: e2010, Category: c2010, Field: f2010, Book: b2010, MappedItems: i2010}
	parcel4 := SportsParcel{Event: e2014, Category: c2014, Field: f2014, Book: b2014, MappedItems: i2014}
	parcel5 := SportsParcel{Event: el2009, Category: cl2009, Field: fl2009, Book: bl2009, MappedItems: il2009}
	parcel6 := SportsParcel{Event: ep2012, Category: cp2012, Field: fp2012, Book: bp2012, MappedItems: ip2012}
	parcel7 := SportsParcel{Event: es2014, Category: cs2014, Field: fs2014, Book: bs2014, MappedItems: is2014}

	ready := []SportsParcel{parcel1, parcel2, parcel3, parcel4, parcel5, parcel6, parcel7}
	pack := FootballParcel{Pack: ready}
	return pack
}

func FootballEvents() []string {
	events := []string{}
	openBuild := BuildFootball()
	for _, event := range openBuild.Pack {
		events = append(events, event.Event)
	}
	return events
}

func FootballCategory() string {
	category := []string{}
	token := BuildFootball().Pack
	for _, cat := range token {
		category = append(category, cat.Category)
	}
	category = dataset.EraseDuplicate(category)
	cat := category[0]
	return cat
}

func FootballBook() string {
	fi := ""
	token := BuildFootball().Pack
	for _, cat := range token {
		fi = cat.Book
	}
	return fi
}

func FootballLists() []string {
	ma := []string{}
	token := BuildFootball().Pack
	for _, t := range token {
		for items := range t.MappedItems {
			ma = append(ma, items)
		}
	}
	return ma
}

func FootballSheet() map[string][]string {
	sheet := map[string][]string{}
	token := BuildFootball().Pack
	for _, t := range token {
		maps.Copy(sheet, t.MappedItems)
	}
	return sheet
}
