// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CurrentDeck struct {
	ID        string `json:"id"`
	First     string `json:"_first"`
	Second    string `json:"_second"`
	IsDefault bool   `json:"isDefault"`
}

type DailyEvents struct {
	Locify []*IDailyEvents `json:"locify"`
	Clash  []*IDailyEvents `json:"clash"`
}

type Display struct {
	Name           string    `json:"name"`
	Nickname       string    `json:"nickname"`
	ID             string    `json:"id"`
	Image          *IImage   `json:"image"`
	ClashProfile   *IProfile `json:"clashProfile"`
	OnevoneProfile *IProfile `json:"onevoneProfile"`
	TwovtwoProfile *IProfile `json:"twovtwoProfile"`
	NygProfile     *IProfile `json:"nygProfile"`
}

type IBooks struct {
	Entertainment []string `json:"entertainment"`
	Sports        []string `json:"sports"`
}

type ICredits struct {
	Coins string `json:"coins"`
	Spurs string `json:"spurs"`
	Theme string `json:"theme"`
}

type IDailyEvents struct {
	EventName   string `json:"eventName"`
	Reward      string `json:"reward"`
	Completed   int32  `json:"completed"`
	ToComplete  int32  `json:"toComplete"`
	Progress    int32  `json:"progress"`
	IsClash     bool   `json:"isClash"`
	Description string `json:"description"`
}

type IImage struct {
	ImgURL  string `json:"imgURL"`
	ImgName string `json:"imgName"`
	ID      string `json:"id"`
}

type IProfile struct {
	GamesPlayed int32  `json:"gamesPlayed"`
	Tier        string `json:"tier"`
	Rating      int32  `json:"rating"`
	Points      int32  `json:"points"`
}

type IStore struct {
	Price string `json:"Price"`
	Title string `json:"Title"`
}

type PowerProfile struct {
	Power   string `json:"power"`
	Spur    int32  `json:"spur"`
	Counter int32  `json:"counter"`
	Level   int32  `json:"level"`
	Allow   bool   `json:"allow"`
	Display string `json:"display"`
}

type PowerProgress struct {
	Upgrades []*PowerProfile `json:"upgrades"`
}

type Query struct {
}

type Store struct {
	Coin []*IStore `json:"coin"`
	Spur []*IStore `json:"spur"`
}

type Subscription struct {
}

type LoginReply struct {
	Msg                    string         `json:"msg"`
	UpdatedPlayerCredits   *ICredits      `json:"updatedPlayerCredits"`
	Name                   string         `json:"name"`
	Nickname               string         `json:"nickname"`
	UpdatedStore           *Store         `json:"updatedStore"`
	UpdatedEvents          *DailyEvents   `json:"updatedEvents"`
	UpdatedDisplay         *Display       `json:"updatedDisplay"`
	UpdatedPowerupUpgrades *PowerProgress `json:"updatedPowerupUpgrades"`
	CurrentDeck            *CurrentDeck   `json:"currentDeck"`
}
