// Package update guess can be made director, story-writer, cast // origin: just for safer-side // genre: action,...// category: hollyworl,...
package update

import (
	"fmt"
	"maps"
	"nyg/dataset"
)

type MoviesParcel struct {
	Pack []EntertainmentParcel
}

// keys
const (
	Bollywood2001Key = "BOLLYWOOD 2001"
	Bollywood2002Key = "BOLLYWOOD 2002"
	Bollywood2003Key = "BOLLYWOOD 2003"
	Bollywood2004Key = "BOLLYWOOD 2004"
	Bollywood2005Key = "BOLLYWOOD 2005"

	MarathiChitrapat2001Key = "MARATHI CHITRAPAT 2001"
	MarathiChitrapat2002Key = "MARATHI CHITRAPAT 2002"
	MarathiChitrapat2003Key = "MARATHI CHITRAPAT 2003"
	MarathiChitrapat2004Key = "MARATHI CHITRAPAT 2004"
	MarathiChitrapat2005Key = "MARATHI CHITRAPAT 2005"

	Hollywood2001Key = "HOLLYWOOD 2001"
	Hollywood2002Key = "HOLLYWOOD 2002"
	Hollywood2003Key = "HOLLYWOOD 2003"
	Hollywood2004Key = "HOLLYWOOD 2004"
	Hollywood2005Key = "HOLLYWOOD 2005"

	MovesKey = "MOVIES"
)

func Bollywood2001() dataset.SearchSystem_ {
	b2001 := map[string][]string{}
	b2001["kabhi khushi kabhi gham"] = []string{
		"Amitabh Bachchan",
		"Jaya Bachchan",
		"Nandini Raichand",
		"Shah Rukh Khan",
		"Shah Rukh Khan",
		"Kajol",
		"Hrithik Roshan",
		"Kareena Kapoor",
		"Jibraan Khan",
		"Farida Jalal",
		"Rani Mukerji",
		"Alok Nath",
		"Amar Talwar",
		"Johny Lever",
		"Achala Sachdev",
		"Himani Shivpuri",
		"Aryan Khan",
		"Sushma Seth",
		"Ramona Sunavala",
		"Jeroo Writer",
		"Vikas Sethi",
		"Simone Singh",
		"Malvika Raaj",
		"Kavesh Majmudar",
		"Jugal Hansraj",
		"Jessy Lever",
		"Ashutosh Singh",
		"Shilpa Mehta",
		"Shashikala Jawalkar",
		"Parzaan Dastur",
		"Tamzin Griffin",
		"Amar Adatia",
		"Abraham Chowdhury",
		"Ali Haji",
		"Karlo",
		"Samir Shah",
		"Bharat Mistri",
		"karan johar",
		"sheena parikh",
	}
	b2001["gada: ek prem katha"] = []string{
		"Sunny Deol",
		"Tara Singh",
		"Ameesha Patel",
		"Amrish Puri",
		"Lillete Dubey",
		"Vivek Shauq",
		"Utkarsh Sharma",
		"Suresh Oberoi",
		"Madhumalti Kapoor",
		"Tony Mirrcandani",
		"Mushtaq Khan",
		"Samar Jai Singh",
		"Pramod Moutho",
		"Kanika Shivpuri",
		"Malavika Shivpuri",
		"Anil Sharma",
		"Shaktimaan tanvar",
	}
	b2001["kaho naa pyaar hai"] = []string{
		"Rakesh Roshan",
		"Hrithik Roshan",
		"Ameesha Patel",
		"Anupam Kher",
		"Dalip Tahil",
		"Mohnish Behl",
		"Ashish Vidyarthi",
		"Satish Shah",
		"Farida Jalal",
		"Tanaaz Currim Irani",
		"Payal Malhotra",
		"Rajesh Tandon",
		"Vrajesh Hirjee",
		"Rammohan Sharma",
		"Shama Deshpande",
		"Kamal Singh",
		"Irin",
		"Farhad Nathani",
		"Asha Patel",
		"Abhishek Sharma",
		"Master Farzaan Dastoor",
	}
	b2001["mohabbatein"] = []string{
		"aditya chopra",
		"Amitabh Bachchan",
		"Shah Rukh Khan",
		"Subhash Hakla",
		"Shah Rukh Khan",
		"Aishwarya Rai Bachchan",
		"Jimmy Shergill",
		"Karan",
		"Uday Chopra",
		"Vicky",
		"Jugal Hansraj",
		"Sameer",
		"Preeti Jhangiani",
		"Shamita Shetty",
		"Kim Sharma",
		"Anupam Kher",
		"Archana Puran Singh",
		"Saurabh Shukla",
		"Helen",
		"Amrish Puri",
		"Shefali Shah",
		"Raman Lamba",
		"Deepak",
		"Parzaan Dastur",
		"Ayush",
		"Ram Mohan",
		"Khan Baba",
		"Rushad Rana",
		"Mehul Nisar",
		"Palash Dutta",
		"Pearl Sukhadia",
		"Meghna Patel",
		"Sindhu Tolani",
		"Sitaram",
		"Gurdial Sira",
		"Harpal Singh Pali",
	}
	b2001["lagaan"] = []string{"Aamir Khan",
		"Gracy Singh",
		"Rachel Shelley",
		"Paul Blackthorne",
		"Suhasini Mulay",
		"Kulbhushan Kharbanda",
		"Raghubir Yadav",
		"Rajendra Gupta",
		"Rajesh Vivek",
		"Shri Vallabh Vyas",
		"Javed Khan Amrohi",
		"Raj Zutshi",
		"Akhilendra Mishra",
		"Dayashankar Pandey",
		"Yashpal Sharma",
		"Amin Hajee",
		"Pradeep Singh Rawat",
		"Aditya Lakhia",
		"A.K. Hangal",
		"John Rowe",
		"David Gant",
		"Jeremy Child",
		"Ben Nealon",
		"Anupam Shyam",
		"Raja Awasthi",
		"Pramatesh Mehta",
		"Bhim Vakani",
		"Amin Gazi",
		"Anu Ansari",
		"Parveen Bano",
		"Chris England",
		"Howard Lee",
		"Simon Holmes",
		"Ray Eves",
		"Jon House",
		"Neil Patrick",
		"Jamie Whitby Coles",
		"Barry Hart",
		"Alex Shirtcliff",
		"Amitabh Bachchan"}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Bollywood2001Key, EntertainmentKey, MovesKey, b2001, false, true, false)
	return M
}

func Bollywood2002() dataset.SearchSystem_ {
	b2002 := map[string][]string{}
	b2002["devdas"] = []string{
		"Shah Rukh Khan",
		"Aishwarya Rai Bachchan",
		"Madhuri Dixit",
		"Jackie Shroff",
		"Kirron Kher",
		"Smita Jaykar",
		"Tiku Talsania",
		"Vijayendra Ghatge",
		"Milind Gunaji",
		"Ananya Khare",
		"Manoj Joshi",
		"Ava Mukherjee",
		"Dina Pathak",
		"Vijay Crishna",
		"Muni Jha",
		"Sunil Rege",
		"Jaya Bhattacharya",
		"Apara Mehta",
		"Mohit",
		"Bansaree Madhani",
		"Kapil Soni",
		"Rashika Pratap Singh",
		"Amardeep Jha",
		"Aksha Pardasany",
		"Gargi Patel",
		"Neha Pendse",
		"Disha Vakani",
		"Mona Parekh",
		"Vallabh Gada",
		"Atul Vyas",
		"Raja Kapse",
		"Heera Singh",
		"sanjay leela bhansali",
	}
	b2002["saathiya"] = []string{
		"shaad ali",
		"mani ratnam",
		"Vivek Oberoi",
		"Rani Mukerji",
		"Shah Rukh Khan",
		"Tabu",
		"Sandhya Mridul",
		"Tanuja Samarth",
		"Satish Shah",
		"Swaroop Sampat",
		"Tinnu Anand",
		"Ujjwal Rana",
		"Anju Mahendru",
		"Sharat Saxena",
		"Shehnaz Anand",
		"Anu Ansari",
		"Chandrashekhar Gautam",
		"Karl Katgara",
		"Kunal Kumar",
		"Prerna Sharma",
		"Pubali Sanyal",
		"Samantha Tremayne",
		"Shanu Sharma",
		"Trishla Patel",
		"Shamita Shetty",
		"Aarya Mehta",
		"Aditya Srivastav",
		"Ashwini Kumar",
		"Bijon Das Gupta",
		"Deepraj Rana",
		"Deepak Qazir",
		"Gautam Saugat",
		"Geeta Nair",
		"Honey Lalwani",
		"Hosang Bamji",
		"Indira D'Souza",
		"Jaya Bhattacharya",
		"Karthik",
		"Shyam",
		"Lalian",
		"Lovina Vaswani",
		"Madhuri",
		"Mansi Upadhyay",
		"Manu Rishi Chadha",
		"Paritosh Sand",
		"Prakash Agarwal",
		"Prem Prakash Singh",
		"Rahul Chahan",
		"Ramesh Goyal",
		"Rishav Joshi",
		"Rohit Raj",
		"Sanjay Mishra",
		"Shail Mehta",
		"Shaukat Azmi",
		"Subodh Kumar",
		"Vaishali Thakkar",
		"Vinay Apte",
		"Yashodhan Bal",
	}
	b2002["aakhio se goli maare"] = []string{
		"Govinda",
		"Raveena Tandon",
		"Kader Khan",
		"Shakti Kapoor",
		"Johny Lever",
		"Govardhan Asrani",
		"Anjana Mumtaz",
		"Satyendra Kapoor",
		"Avtar Gill",
		"Dinesh Hingoo",
		"Razak Khan",
		"Rana Jung Bahadur",
		"Tiku Talsania",
		"Beena Banerjee",
		"Rajshree Solanki",
		"Viju Khote",
		"Ghanshyam Rohera",
		"Manmauji",
		"Veeru Krishnan",
		"Shyam Solanki",
		"Rauf Raja",
		"Shyam Awasthi",
		"Rajeev Kaul",
		"Harmesh Malhotra",
	}
	b2002["mere yaar ki shaadi hain"] = []string{
		"Uday Chopra",
		"Jimmy Shergill",
		"Bipasha Basu",
		"Tanaaz Currim Irani",
		"Shamita Shetty",
		"Alok Nath",
		"Neena Kulkarni",
		"Sheela Sharma",
		"Deven Verma",
		"Bindu Desai",
		"Mehul Buch",
		"Ajit",
		"Saurabh Shukla",
		"Tushar Dalvi",
		"Raja Vaid",
		"Sanjay Gadhvi",
	}
	b2002["awaara pagal dewaana"] = []string{
		"Akshay Kumar",
		"Suniel Shetty",
		"Aftab Shivdasani",
		"Paresh Rawal",
		"Preeti Jhangiani",
		"Amrita Arora",
		"Supriya Pilgaonkar",
		"Aarti Chhabria",
		"Johny Lever",
		"Rahul Dev",
		"Om Puri",
		"Govardhan Asrani",
		"Vikram Bhatt",
		"Anand Vardhan",
		"Mangesh Kulkarni",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Bollywood2002Key, EntertainmentKey, MovesKey, b2002, false, true, false)
	return M
}

func Bollywood2003() dataset.SearchSystem_ {
	b2003 := map[string][]string{}
	b2003["munna bhai M.B.B.S"] = []string{
		"Sanjay Dutt",
		"Arshad Warsi",
		"Gracy Singh",
		"Boman Irani",
		"Sunil Dutt",
		"Rohini Hattangadi",
		"Kurush Deboo",
		"Jimmy Shergill",
		"Yatin Karyekar",
		"Khurshed Lawyer",
		"Bomie E. Dotiwala",
		"Rohitash Gaud",
		"Priya Bapat",
		"Rita Puri",
		"Surendra Rajan",
		"Mumait Khan",
		"Suresh Chatwal",
		"Atul Srivastava",
		"Neha Dubey",
		"Vishal Thakkar",
		"Anuradha Chandan",
		"Rajkumar Hirani",
	}
	b2003["kal ho na ho"] = []string{
		"Shah Rukh Khan",
		"Preity G Zinta",
		"Saif Ali Khan",
		"Jaya Bachchan",
		"Sushma Seth",
		"Reema Lagoo",
		"Lillete Dubey",
		"Delnaaz Irani",
		"Rani Mukerji",
		"Athit Naik",
		"Jhanak Shukla",
		"Sonali Bendre",
		"Satish Shah",
		"Sulabha Arya",
		"Rajpal Naurang Yadav",
		"Ketki Dave",
		"Kamini Khanna",
		"Simone Singh",
		"Shoma Anand",
		"Sanjay Kapoor",
		"Michael Pinkhas",
		"Anaita Shroff",
		"Zohra Sehgal",
		"Achala Sachdev",
		"Deepesh Bhatt",
		"Dodo Bhujwala",
		"Kanika Shivpuri",
		"Dara Singh Randhawa",
		"Nikhil Advani",
		"Karan Johar",
	}
	b2003["gangaajal"] = []string{
		"Ajay Devgn",
		"Gracy Singh",
		"Mohan Joshi",
		"Yashpal Sharma",
		"Akhilendra Mishra",
		"Mukesh Tiwari",
		"Ayub Khan",
		"Chetan Pandit",
		"Anup Soni",
		"Mohan Agashe",
		"Yash Gawli",
		"Payal Srivastava",
		"Dayashankar Pandey",
		"Prakash Jha",
	}
	b2003["koi mil gaya"] = []string{
		"Rekha",
		"Hrithik Roshan",
		"Preity G Zinta",
		"Rajat Bedi",
		"Prem Chopra",
		"Rajeev Verma",
		"Beena Banerjee",
		"Anjana Mumtaz",
		"Mukesh Rishi",
		"Johny Lever",
		"Anuj Pandit",
		"Hansika Motwani",
		"Mohit Makkad",
		"Jai Choksi",
		"Omkar Purohit",
		"Pranita Bishnoi",
		"Chhote Ustad",
		"Rakesh Roshan",
		"Aaryamann Sapru",
		"Rakesh Roshan",
	}
	b2003["baghban"] = []string{
		"Amitabh Bachchan",
		"Hema Malini",
		"Salman Khan",
		"Mahima Chaudhry",
		"Aman Verma",
		"Samir Soni",
		"Sahil Chaddha",
		"Nasir Khan",
		"Suman Ranganath",
		"Divya Dutta",
		"Arzoo Govitrikar",
		"Rimi Sen",
		"Yash Gawli",
		"Paresh Rawal",
		"Lillete Dubey",
		"Sharat Saxena",
		"Sanjeeda Sheikh",
		"Govardhan Asrani",
		"Avtar Gill",
		"Mohan Joshi",
		"Anang Desai",
		"Nakul Vaid",
		"Shashi Kiran",
		"Gajendra Chauhan",
		"Sudipta Roy",
		"Neha Ghanekar",
		"Titiksha Burman",
		"Ravi Chopra",
		"Baldev Raj Chopra",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Bollywood2003Key, EntertainmentKey, MovesKey, b2003, false, true, false)
	return M
}

func Bollywood2004() dataset.SearchSystem_ {
	b2004 := map[string][]string{}
	b2004["main hoon naa"] = []string{
		"Shah Rukh Khan",
		"Sushmita Sen",
		"Suniel Shetty",
		"Zayed Khan",
		"Amrita Rao",
		"Kabir Bedi",
		"Naseeruddin Shah",
		"Boman Irani",
		"Bindu Desai",
		"Satish Shah",
		"Kirron Kher",
		"Nassar Abdulla",
		"Kunal Kumar",
		"Rajiv Panjabi",
		"Rakhi Sawant",
		"Murli Sharma",
		"Praveen Sirohi",
		"Farah Khan",
	}
	b2004["veer-zara"] = []string{
		"Shah Rukh Khan",
		"Preity G Zinta",
		"Rani Mukerji",
		"Kirron Kher",
		"Divya Dutta",
		"Boman Irani",
		"Anupam Kher",
		"Amitabh Bachchan",
		"Hema Malini",
		"Manoj Bajpayee",
		"Zohra Sehgal",
		"S.M. Zaheer",
		"Tom Alter",
		"Akhilendra Mishra",
		"Arun Bali",
		"Rushad Rana",
		"Balwant Bansal",
		"Vicky Ahuja",
		"Ranjeev Verma",
		"Kulbir Badesron",
		"Gurinder Singh",
		"Sankeetaan Raravir",
		"Mart Kenneth Rebamonte",
		"Gurdas Maan",
		"Vinod Negi",
		"Anoop Kamal Singh",
		"Huzefa Gadiwala",
		"Vishal Om Prakash",
		"Firdaus Hassan",
		"Banwari Lal Jhol",
		"Jeetendra Bharadwaj",
		"Rajesh Jolly",
		"Kanwar Jagdish",
		"Dev Vivek Kantawala",
		"Chandni Jas Keerat",
		"Sanjay Singh Bhadli",
		"Shivaya Singh",
		"Amir Zadey",
		"Manish Arora",
		"Darshan Aulakh",
		"Pankaj Raina",
		"Yash Chopra",
		"Aditya Chopra",
	}
	b2004["mujse shaadi karogi"] = []string{
		"Salman Khan",
		"Akshay Kumar",
		"Priyanka Chopra Jonas",
		"Amrish Puri",
		"Rajpal Naurang Yadav",
		"Satish Shah",
		"Supriya Karnik",
		"Kader Khan",
		"Rekha Rao",
		"Shashikala Jawalkar",
		"Upasana Singh",
		"David Dhawan",
		"Anees Bazme",
	}
	b2004["Krishna Cottage"] = []string{
		"Sohail Khan",
		"Isha Koppikar",
		"Anita Hassanandani Reddy",
		"Rati Agnihotri",
		"Hiten Tejwani",
		"Nupur",
		"Vrajesh Hirjee",
		"Raj Zutshi",
		"Santram Verma",
		"Abhigyan Jha",
	}
	b2004["abb tumhare vatan saathiyo"] = []string{
		"Amitabh Bachchan",
		"Akshay Kumar",
		"Bobby Deol",
		"Divya Khossla",
		"Sandali Sinha",
		"Nagma",
		"Aarti Chhabria",
		"Kapil Kaustubh Sharma",
		"Surendra Pal",
		"Rajesh Vivek",
		"Vivek Shauq",
		"Danny Denzongpa",
		"Govind Namdeo",
		"Vishwajeet Pradhan",
		"Ashutosh Rana",
		"Sikandar Khan",
		"Anil Sharma",
		"Sanjay Sharma",
		"Shatkimaan Talwar",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Bollywood2004Key, EntertainmentKey, MovesKey, b2004, false, true, false)
	return M
}

func Bollywood2005() dataset.SearchSystem_ {
	b2005 := map[string][]string{}
	b2005["paheli"] = []string{
		"Shah Rukh Khan",
		"Rani Mukerji",
		"Anupam Kher",
		"Naseeruddin Shah",
		"Ratna Pathak Shah",
		"Amitabh Bachchan",
		"Suniel Shetty",
		"Juhi Chawla",
		"Dilip Prabhawalkar",
		"Neena Kulkarni",
		"Padma Rani",
		"Rajpal Naurang Yadav",
		"Aditi Govitrikar",
		"Somesh Agarwal",
		"Mohan Bhandari",
		"Rajneeshh Dubey",
		"A.K. Hangal",
		"Preeti Gupta",
		"Nikhil Ratnaparkhi",
		"Aashif Sheikh",
		"Lekh Tandon",
		"Surendra Rajan",
		"Anita Wahi",
		"Vijay Mishra",
		"Advait Trivedi",
		"Palak Jain",
		"Sharvari Jamenis",
		"Vijayadan Detha",
		"Amol Palekar",
	}
	b2005["maine pyarr kyun kiya"] = []string{
		"Salman Khan",
		"Sushmita Sen",
		"Katrina Kaif",
		"Sohail Khan",
		"Arshad Warsi",
		"Rajpal Naurang Yadav",
		"Beena Kak",
		"David Dhawan",
	}
	b2005["no entry"] = []string{
		"Anil Kapoor",
		"Salman Khan",
		"Fardeen Khan",
		"Bipasha Basu",
		"Lara Dutta",
		"Esha Deol",
		"Celina Jaitly",
		"Boman Irani",
		"Paresh Ganatra",
		"Pratima Kazmi",
		"Dinesh Hingoo",
		"Anjan Srivastav",
		"Mangala Kenkre",
		"Sameera Reddy",
		"Anees Bazmee",
	}
	b2005["dewaane hue pagal"] = []string{
		"Shahid Kapoor",
		"Akshay Kumar",
		"Suniel Shetty",
		"Rimi Sen",
		"Paresh Rawal",
		"Om Puri",
		"Johny Lever",
		"Vijay Raaz",
		"Suresh Menon",
		"Govardhan Asrani",
		"Rakesh Bedi",
		"Supriya Pilgaonkar",
		"Baljeet Singh",
		"Vivek Oberoi",
		"Aftab Shivdasani",
		"Snehal Dabi",
		"Sayyed Abid",
		"Anu Malik",
		"Leena",
		"Vikram Bhatt",
		"Kiran Kotrial",
	}
	b2005["sarkar"] = []string{
		"Amitabh Bachchan",
		"Abhishek Bachchan",
		"Kay Kay Menon",
		"Supriya Pathak",
		"Katrina Kaif",
		"Tanishaa Mukerji",
		"Rukhsar Rehman",
		"Anupam Kher",
		"Kota Srinivasa Rao",
		"Deepak Shirke",
		"Ishrat Ali",
		"Zakir Hussain",
		"Ravi Kale",
		"Raju Mavani",
		"Jeeva",
		"Anant Jog",
		"Mangala Kenkre",
		"Priyanka Kothari",
		"Virendra Saxena",
		"Bhushan",
		"Nagesh Bhonsle",
		"Rasika Joshi",
		"Saurabh Dubey",
		"Raju Thakkar",
		"Uday Sabnis",
		"Anil Yadav",
		"Dinesh Lamba",
		"Saksham Dayma",
		"Gautam Shetty",
		"Rushad Rana",
		"Ram Gopal Verma",
		"Manish Gupta",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Bollywood2005Key, EntertainmentKey, MovesKey, b2005, false, true, false)
	return M
}
func MarathiChitrapat2001() dataset.SearchSystem_ {
	m2001 := map[string][]string{}
	m2001["devki"] = []string{
		"Abhiram Bhadkamkar",
		"Milind Gawali",
		"Smita Jaykar",
		"Sudhir Joshi",
		"Preeti Koppikar",
		"Alka Kubal",
		"Girish Oak",
		"Shilpa Tulaskar",
		"Anurag Worlikar",
		"Suhas Shirvalkar",
		"Milind Uday",
	}
	m2001["ashi dyaneshwari"] = []string{
		"Ramesh Bhatkar",
		"Sharad Bhutadiya",
		"Krupa Kulkarni",
		"Nandu Madhav",
		"Rajshri Nagarkar",
		"Akstha Naik",
		"Usha Naik",
		"Smita Oak",
		"Suhas Palshikar",
		"Kuldeep Pawar",
		"Angraj Shinde",
		"Sayaji Shinde",
		"Baby Shraddha",
		"Shanta Tambe",
		"Nishigandha Wad",
		"Rajan Suryawanshi",
		"S.M. Rajan",
	}
	m2001["dyhasparva"] = []string{
		"Seema Biswas",
		"Nishith Dadhich",
		"Mohan Gokhale",
		"Kishore Kadam",
		"Sachin Khedekar",
		"Atul Kulkarni",
		"Shreeram Lagoo",
		"Sanjay Mone",
		"Minal Paranjape",
		"Sanjay Pawar",
		"Varsha Usgaonkar",
		"Amol Palekar",
		"Chitra Palekar",
	}
	m2001["tulas aali gharat"] = []string{
		"Ravindra Berde",
		"Vijay Kadam",
		"Avinash Kharshikar",
		"Alka Kubal",
		"Bhalchandra Kulkarni",
		"Mehmood Jr.",
		"Master Parvez",
		"Asha Patil",
		"Sharad Ponkshe",
		"Shobha Shiralkar",
		"Sharmila Vatve",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(MarathiChitrapat2001Key, EntertainmentKey, MovesKey, m2001, false, true, false)
	return M
}

func MarathiChitrapat2002() dataset.SearchSystem_ {
	m2002 := map[string][]string{}
	m2002["devi ahilya bai"] = []string{
		"Sadashiv Amrapurkar",
		"Malhar Rao Holkar",
		"Shabana Azmi",
		"Praveen Bhole",
		"Bharati Jaffrey",
		"Mallika Prasad",
		"Aishwarya Shidhaye",
		"Ganesh Yadav",
		"Jayoo Natiker",
	}
	m2002["vaastupurush"] = []string{
		"Sadashiv Amrapurkar",
		"Uttara Baokar",
		"Siddharth Daftardar",
		"Mahesh Elkunchwar",
		"Atul Kulkarni",
		"Ravindra Mankani",
		"Sumitra Bhave",
		"Sunil Sukthankar",
	}
	m2002["dagina"] = []string{
		"Madhu Apte",
		"Laxmikant Berde",
		"Sarjerao Gaikwad",
		"Bhalchandra Kulkarni",
		"Majnalkar",
		"Poornima Patankar",
		"Sanjivani Rathod",
		"Raj Shekar",
		"Shobha Shiralkar",
		"Sharmila Vatve",
		"Jagdesh Patankar",
	}
	m2002["sahi re sahi"] = []string{

		"Mrunal Bhuskute",
		"Bharat Jadhav",
		"Geetanjali Kambli",
		"Seema Lad",
		"Jayraj Nair",
		"Aishwarya Shinde",
		"Meera Sukhatme",
		"Kedar Shirshekar",
		"Manoj Takne",
		"Prashant Vichare",
		"Kedar Shinde",
	}
	m2002["dahavi pha"] = []string{
		"Atul Kulkarni",
		"Jyoti Subhash",
		"Milind Gunaji",
		"Nimish Kathale",
		"Vrishasen Dabholkar",
		"Sumitra Barve",
		"Sunil Sukthankar",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(MarathiChitrapat2002Key, EntertainmentKey, MovesKey, m2002, false, true, false)
	return M
}

func MarathiChitrapat2003() dataset.SearchSystem_ {
	m2003 := map[string][]string{}
	m2003["bhau bheej"] = []string{
		"Asavle Guruji",
		"Alka Inamdar",
		"Raj",
		"Madhu Kambikar",
		"Alka Kubal",
		"Bhalchandra Kulkarni",
		"Nandu Patil",
		"Kuldeep Pawar",
		"Manik Raj",
		"Chhaya Sangaonkar",
		"Ashok Shinde",
		"Nanda Shinde",
		"Pramod Shinde",
		"Purva Shinde",
		"Shobha Shiralkar",
		"Nishigandha Wad",
		"Pramod Shinde",
	}
	m2003["chutki"] = []string{
		"Anirudh Banavalkar",
		"Sandip Dalvi",
		"Prajakta Joshi",
		"Asmita Keluskar",
		"Shrikant Gurav",
	}
	m2003["shodh"] = []string{
		"Laxmikant Berde",
		"Ravindra Berde",
		"Ramesh Bhatkar",
		"Sharmil Bhatwal",
		"Ankur Deshpande",
		"Prajakta Dighe",
		"Anant Jog",
		"Afreen Khan",
		"Vida Koteka",
		"Neeraj Patil",
		"Satyajit Sawant",
		"Shobha Shiralkar",
		"Sunil Tawde",
		"Pradeep Berlekar",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(MarathiChitrapat2003Key, EntertainmentKey, MovesKey, m2003, false, true, false)
	return M
}

func MarathiChitrapat2004() dataset.SearchSystem_ {
	m2004 := map[string][]string{}
	m2004["navra mazha navsacha"] = []string{
		"Sachin Pilgaonkar",
		"Supriya Pilgaonkar",
		"Ashok Saraf",
		"Anand Abhyankar",
		"Ali Asgar",
		"Pradip Kabre",
		"Reema Lagoo",
		"Johny Lever",
		"Vaibhav Mangale",
		"Priyanka Mungekar",
		"Sonu Nigam",
		"Atul Parchure",
		"Vijay Patkar",
		"Pradeep Patwardhan",
		"Vijay Patwardhan",
		"Kuldeep Pawar",
		"Madhurani Gokhale Prabulkar",
		"Vikas Samudre",
		"Nirmiti Sawant",
		"Kishori Shahane",
		"Mahesh Subhedar",
		"Satish Tare",
		"Sunil Tawde",
		"Jaywant Wadkar",
		"Vinay Yedekar",
	}
	m2004["shegavicha rana Gajanan"] = []string{
		"Ravindra Berde",
		"Babanrao Gholap",
		"Sayaji Shinde",
		"Deepak Shirke",
		"Babanrao Gholap",
	}
	m2004["oti krishnamaichi"] = []string{
		"Alka Kubal",
		"Ravi Patwardhan",
		"Sharad Ponkshe",
		"Mayur Vaishnav",
	}
	m2004["sakshatkar"] = []string{
		"Ramesh Bhatkar",
		"Ankush Chaudhari",
		"Vijay Chavan",
		"Mangesh Desai",
		"Suhasini Deshpande",
		"Megha Dhade",
		"Uday Lagoo",
		"Aishwarya Narkar",
		"Sarita Pradhan",
		"Sharad Ponkshe",
		"Ashok Shinde",
		"Varsha Usgaonkar",
		"Kiransai",
	}
	m2004["aga bai arecha"] = []string{
		"Bharti Achrekar",
		"Sonali Bendre",
		"Vijay Chavan",
		"Shubhangi Gokhale",
		"Bharat Jadhav",
		"Siddharth Jadhav",
		"Rasika Joshi",
		"Suhas Joshi",
		"Tejaswini Pandit",
		"Dilip Prabhawalkar",
		"Rekha Sawant",
		"Mandar Shinde",
		"Vinay Yedekar",
		"Kedar Shinde",
		"Guru Thakur",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(MarathiChitrapat2004Key, EntertainmentKey, MovesKey, m2004, false, true, false)
	return M
}

func MarathiChitrapat2005() dataset.SearchSystem_ {
	m2005 := map[string][]string{}
	m2005["pak pak pakaak"] = []string{
		"Nana Patekar",
		"Saksham Kulkarni",
		"Narayani Shastri",
		"Usha Nadkarni",
		"Jyoti Subhash",
		"Rekha Kamat",
		"Vijay Patwardhan",
		"Arun Hornekar",
		"Vidyadhar Joshi",
		"Anand Ingle",
		"Nandu Pol",
		"Gautam Joglekar",
	}
	m2005["jatra: hyalagaad re tyalagaad"] = []string{
		"Kushal Badrike",
		"Munir Baghman",
		"Mohan Bagode",
		"Priya Arun Berde",
		"Shankar Bhake",
		"Jaiwant Bhalekar",
		"Dilip Budhkar",
		"Ankush Chaudhari",
		"Vijay Chavan",
		"Kishore Chougule",
		"Harshad Dalvi",
		"Rajendra Deodhar",
		"Rajan Deshmukh",
		"Rajesh Dhawale",
		"Pratok Gaikwad",
		"Hitesh Gandhi",
		"Rahul Geete",
		"Deepali Ghitke",
		"Komal Ghitke",
		"Ghansham Ghorpade",
		"Himani",
		"Harbal Inamdar",
		"Bharat Jadhav",
		"Chandrashekhar Jadhav",
		"Siddharth Jadhav",
		"Arvind Kadavle",
		"Bhujangrao Kale",
		"Sidhuroopa Kamarkar",
		"Sanjay Katavle",
		"Raza Khan",
		"Sanjay Khapre",
		"Ganesh Khebedkar",
		"Viju Khote",
		"Mahesh Kokate",
		"Rajesh Kolan",
		"Paresh Ladd",
		"Saurabh Lele",
		"Vedehi Lele",
		"Upendra Limaye",
		"Manmohan Mahimkar",
		"Vilas Mehmankar",
		"Ramesh More",
		"Nagnath Nahaye",
		"Jayraj Nair",
		"Jairaj Nayyar",
		"Samir Nikam",
		"Pallavi Pandagle",
		"Ranchita Pandit",
		"Bhaskar Pawaskar",
		"Pratima",
		"Shankar Premi",
		"Chandana Ramesh",
		"Ashok Razdan",
		"Kranti Redkar",
		"Shevanta",
		"Ganesh Revdekar",
		"Ganya",
		"Vikas Samant",
		"Sandeep Sapkal",
		"Kamlakar Satputhe",
		"Dipali Sayyad",
		"Sameer Shaikh",
		"Pradeep Sharma",
		"Nissar Sheikh",
		"Ashok Shinde",
		"Bhandar Shinde",
		"Ganesh Shinde",
		"Raju Shinde",
		"Shweta",
		"Amir Tadwalkar",
		"Raju",
		"Sunil Tawde",
		"Vinod Tiwari",
		"Abhir Tondavkar",
		"Vandana Vaknis",
		"Ramesh Vani",
		"Kedar Shinde",
	}
	m2005["kay daicha bola"] = []string{
		"Mohan Agashe",
		"Parthaa Akerkar",
		"Sharvari Jamenis",
		"Girish Joshi",
		"Sachin Khedekar",
		"Amita Khopkar",
		"Sanjay Mone",
		"Arun Nalawade",
		"Akshay Pendse",
		"Nirmiti Sawant",
		"Pushkar Shrotri",
		"Ganesh Yadav",
		"Chandrakant Kulkarni",
	}
	m2005["kalubaichya naavan changbhala"] = []string{
		"Makarand Anaspure",
		"Sagar Chougule",
		"Suhasini Deshpande",
		"Samera Gujar",
		"Dinkar Inamdar",
		"Maya Jadhav",
		"Alka Kubal",
		"Surekha Kudachi",
		"Ajay Lobo",
		"Seva More",
		"Prasad Oak",
		"Kuldeep Pawar",
		"Swapnil Rajshekhar",
		"Chhaya Sangaonkar",
		"Ashok Saraf",
		"Nanda Shinde",
		"Prakash Hilage",
	}
	m2005["khabardar"] = []string{
		"Bharat Jadhav",
		"Nirmiti Sawant",
		"Sanjay Narvekar",
		"Makarand Anaspure",
		"Vinay Apte",
		"Vijay Chavan",
		"Rajesh Gade",
		"Kishori Godbole",
		"Ameya Hunaswadkar",
		"Rasika Joshi",
		"Pandharinath Kamble",
		"Mahesh Kothare",
		"Seva More",
		"Sunil Tawde",
		"Resham Tipnis",
		"Madhura Velankar",
		"Mahesh Kothare",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(MarathiChitrapat2005Key, EntertainmentKey, MovesKey, m2005, false, true, false)
	return M
}

func Hollywood2001() dataset.SearchSystem_ {
	h2001 := map[string][]string{}
	h2001["don't say a word"] = []string{
		"Michael Douglas",
		"Nathan Conrad",
		"Sean Bean",
		"Brittany Murphy",
		"Skye McCole Bartusiak",
		"Famke Janssen",
		"Jennifer Esposito",
		"Shawn Doyle",
		"Victor Argo",
		"Conrad Goode",
		"Paul Schulze",
		"Lance Reddick",
		"Guy Torry",
		"Oliver Platt",
		"Aidan Devine",
		"Alex Campbell",
		"Philip DeWilde",
		"Sam Montesano",
		"Arlene Duncan",
		"Judy Sinclair",
		"Larry Block",
		"David Warshofsky",
		"Darren Frost",
		"Philip Williams",
		"Louis Vanaria",
		"Daniel Kash",
		"Lucie Laurier",
		"Isabella Fink",
		"Ray Iannicelli",
		"Colm Magner",
		"Cyrus Farmer",
		"Martin Roach",
		"Patricia Mauceri",
		"Tony Bruno",
		"Paul J.Q. Lee",
		"Johnny Prince",
		"Michael Sercerchi",
		"Lorli Villanueva",
		"Gary Fleder",
		"Andrew Kalven",
	}
	h2001["shrek"] = []string{
		"Mike Myers",
		"Eddie Murphy",
		"Cameron Diaz",
		"John Lithgow",
		"Vincent Cassel",
		"Peter Dennis",
		"Clive Pearse",
		"Jim Cummings",
		"Bobby Block",
		"Chris Miller",
		"Cody Cameron",
		"Kathleen Freeman",
		"Michael Galasso",
		"Christopher Knights",
		"Simon J. Smith",
		"Conrad Vernon",
		"Jacquie Barnbrook",
		"Guillaume Aretos",
		"John Bisom",
		"Matthew Gonder",
		"Calvin Remsberg",
		"Jean-Paul Vignon",
		"Val Bettin",
		"Andrew Adamson",
		"Sally Dworsky",
		"Jeremy Harrington",
		"Baka Prase",
		"Aron Warner",
	}
	h2001["monster, inc."] = []string{
		"John Goodman",
		"Billy Crystal",
		"Mary Gibbs",
		"Steve Buscemi",
		"James Coburn",
		"Jennifer Tilly",
		"Bob Peterson",
		"John Ratzenberger",
		"Frank Oz",
		"Daniel Gerson",
		"Steve Susskind",
		"Bonnie Hunt",
		"Jeff Pidgeon",
		"Samuel Lord Black",
		"Jack Angel",
		"Bob Bergen",
		"Rodger Bumpass",
		"Gino Conforti",
		"Jennifer Darling",
		"Patti Deutsch",
		"Pete Docter",
		"Bobby Edner",
		"Ashley Edner",
		"Paul Eiding",
		"Katie Scarlett",
		"Bill Farmer",
		"Keegan Farrell",
		"Pat Fraley",
		"Teresa Ganzel",
		"Taylor Gifaldi",
		"Marc John Jefferies",
		"Joe Lala",
		"Noah Luke",
		"Sherry Lynn",
		"Danny Mann",
		"Mona Marshall",
		"Mickie McGowan",
		"Laraine Newman",
		"Kay Panabaker",
		"Phil Proctor",
		"Josh Qualtieri",
		"Guido Quaroni",
		"Jan Rabson",
		"Lisa Raggio",
		"Joe Ranft",
		"Sophia Ranft",
		"Katherine Ringgold",
		"Bob Scott",
		"David Silverman",
		"Jim Thornton",
		"Lee Unkrich",
		"Greg Berg",
		"Mel Blanc",
		"Donald Fullilove",
		"Jacques Marin",
		"Stojan Matavulj",
		"Branko Menicanin",
		"Patrick Pinney",
		"Nikki Rapp",
		"Wallace Shawn",
		"Patty Wirtz",
	}
	h2001["rush hour 2"] = []string{
		"Jackie Chan",
		"Chris Tucker",
		"John Lone",
		"Ziyi Zhang",
		"Roselyn Sanchez",
		"Alan King",
		"Harris Yulin",
		"Kenneth Tsang",
		"Lisa LoCicero",
		"Mei Melançon",
		"Maggie Q",
		"Patricia Chan",
		"Gelbert Coloma",
		"Lucy Lin",
		"Cindy Lu",
		"Wing Sang Pang",
		"Mei Ling Wong",
		"William Wai-Lun Duen",
		"Shawn Peretz",
		"Audrey Quock",
		"Ernie Reyes Jr.",
		"Jeremy Piven",
		"Verena Mei",
		"Joel McKinnon Miller",
		"Angela Little",
		"Julia Schultz",
		"Saul Rubinek",
		"Gianni Russo",
		"James J. Ghang",
		"Michael Chow",
		"Teresa Chao Yi Lin",
		"Tanya Newbould",
		"Matthew Barry",
		"James C. Duke",
		"Elizabeth Anweis",
		"Jonathan Burleigh Barnthouse",
		"Melissa Biggs",
		"Tai Li Bond",
		"Don Cheadle",
		"Andy Cheng",
		"Chucky Currie",
		"Mitch Ehrecke",
		"Tom Sean Foley",
		"Joss Gomez",
		"Constance Hsu",
		"Rico Lee Junior",
		"James Lew",
		"Roger Lim",
		"Mars",
		"Kathryn Melton",
		"Hyeon-jin Park",
		"Cynthia Pinot",
		"Simon Rhee",
		"Nicholas Rich",
		"Ivan Shaw",
		"Lina So",
		"Reggi Danielle Sweat",
		"Felicia Tang",
		"Michael A. Tessiero",
		"Jodi Thomas",
		"Juting Tsang",
		"Natasha Yi",
	}
	h2001["sound of the sea"] = []string{
		"Bigas Luna",
		"Rafeal Azcona",
		"Jordi Mollà",
		"Leonor Watling",
		"Eduard Fernández",
		"Neus Agulló",
		"Pep Cortés",
		"Ricky Colomer",
		"Sergio Caballero",
		"Carla Collado",
		"Juan Muñoz",
		"Pablo Rivero",
		"Ana María Máñez",
		"Clara Serrano",
		"Bautista Devesa",
		"José Gonga",
		"Ricardo López",
		"Javier Coromina",
		"Ximo Vidal",
		"Paco Bertomeu",
		"Juli Cantó",
		"Ernesto Arango",
		"Mar Terol",
		"José Luis Pérez-de los Cobos",
		"Manuel Jover",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Hollywood2001Key, EntertainmentKey, MovesKey, h2001, true, false, false)
	return M
}

func Hollywood2002() dataset.SearchSystem_ {
	h2002 := map[string][]string{}
	h2002["frida"] = []string{
		"Salma Hayek",
		"Mía Maestro",
		"Amelia Zapata",
		"Alejandro Usigli",
		"Diego Luna",
		"Alfred Molina",
		"Lucia Bravo",
		"Valeria Golino",
		"Patricia Reyes Spíndola",
		"Loló Navarro",
		"Roger Rees",
		"Fermín Martínez",
		"Roberto Medina",
		"Ashley Judd",
		"Antonio Banderas",
		"Lila Downs",
		"Martha Claudia Moreno",
		"Maria Ines Pintado",
		"Aida López",
		"Ivana Sejenovich",
		"Diego Espinosa",
		"Ehécatl Chávez",
		"Elliot Goldenthal",
		"Edward Norton",
		"Saffron Burrows",
		"Didi Conn",
		"Julian Sedgwick",
		"William Raymond",
		"Jorge Guerrero",
		"Mary Luz Palacio",
		"Geoffrey Rush",
		"Margarita Sanz",
		"Omar Chagall",
		"Anthony Alvarez",
		"Enoc Leaño",
		"Karine Plantadit",
		"Chavela Vargas",
		"Jorge Zepeda",
		"Jose Astorga",
		"Benjamín Benítez",
		"Thomas Ebert",
		"Claudia Frías",
		"Felipe Fulop",
		"Joey Mazzarino",
		"Andrés Montiel",
		"Mauricio Osorio",
		"Jorge Valdés García",
		"Eszter Zakariás",
		"Antonio Zavala Kugler",
		"Julia Taymor",
		"Hayden Herrera",
	}
	h2002["john q"] = []string{
		"Gabriela Oltean",
		"Denzel Washington",
		"Kimberly Elise",
		"Ron Annabelle",
		"Daniel E. Smith",
		"David Thornton",
		"Barry G. King",
		"Laura Harring",
		"Kevin Connolly",
		"Larissa Laskin",
		"Vanessa Branch",
		"Stephanie Moore",
		"Anne Heche",
		"James Woods",
		"Michael Jaye",
		"Yanna McIntosh",
		"Linda Massad",
		"Lester Mathews",
		"Noam Jenkins",
		"Allegra Fulton",
		"Darrin Brown",
		"Paul Johansson",
		"Shera Danese",
		"Kirsta Teague",
		"Ethan Suplee",
		"Rick Sood",
		"Shawn Hatosy",
		"Heather Wahlquist",
		"Julie Bird",
		"Troy Byer",
		"Troy Winbush",
		"Eddie Griffin",
		"Martha Chaves",
		"Scott Bloom",
		"Dina Spybey-Waters",
		"Carlos Diaz",
		"Joe Duer",
		"Simon Sinn",
		"Robert Duvall",
		"Obba Babatundé",
		"Ray Liotta",
		"Jeff Douglas",
		"Keram Malicki-Sánchez",
		"Philip Williams",
		"Nigel Shawn Williams",
		"Frank Cassavetes",
		"Colin Evans",
		"Angelo Tsarouchas",
		"Marcia Johnson",
		"Vijay Mehta",
		"Andrew Schaff",
		"Malcolm Nefsky",
		"Jay Leno",
		"Gloria Allred",
		"Larry King",
		"Arianna Huffington",
		"Ted Demme",
		"Nas",
		"Bill Maher",
		"Claire Rankin",
		"Philip Craig",
		"Gerry Quigley",
		"Olunike Adeliyi",
		"John Alan Andrews",
		"Joanna Bennett",
		"Jennifer Cohen",
		"Chantal Cousineau",
		"Cheryl De Luca",
		"Wendy Graham",
		"Larry Hatcher",
		"Sandra Jackson",
		"Gillian Leigh",
		"Rona Leon",
		"Jane Luk",
		"Marcus Mayer",
		"Mehmet Oz",
		"Diana Platts",
		"Christy Ring",
		"Michael Sercerchi",
		"Carroll Shelby",
		"Victor Sutton",
		"Nick Cassavetes",
		"James Kearns",
	}
	h2002["ice age"] = []string{
		"Ray Romano",
		"John Leguizamo",
		"Denis Leary",
		"Goran Visnjic",
		"Jack Black",
		"Cedric The Entertainer",
		"Stephen Root",
		"Diedrich Bader",
		"Alan Tudyk",
		"Lorri Bagley",
		"Jane Krakowski",
		"Peter Ackerman",
		"P.J. Benjamin",
		"Josh Hamilton",
		"Chris Wedge",
		"Denny Dillon",
		"Mitzi McCall",
		"Tara Strong",
		"Michael Bell",
		"Carlos Saldanha",
		"Chris Wedge",
		"Micheal J.Wilson",
		"James Bresnahan",
		"Galen T. Chu",
		"Doug Compton",
		"Xeth Feinberg",
		"Jeff Siergey",
		"Micheal Thurmeier",
	}
	h2002["stuard little"] = []string{
		"Michael J. Fox",
		"Geena Davis",
		"Hugh Laurie",
		"Jonathan Lipnicki",
		"Anna Hoelck",
		"Ashley Hoelck",
		"Nathan Lane",
		"Melanie Griffith",
		"James Woods",
		"Steve Zahn",
		"Marc John Jefferies",
		"Angelo Massagli",
		"Jim Doughan",
		"Brad Garrett",
		"Conan McCarty",
		"Maria Bamford",
		"Daniel Hansen",
		"Kevin Olson",
		"Dyllan Christopher",
		"Bobby Walsh",
		"Michael C. Fuchs",
		"Raymond Ma",
		"Amelia Marshall",
		"Ronobir Lahiri",
		"Connie Roderick",
		"David Tabatsky",
		"Frank Aquilino",
		"Salvatore Pate",
		"Rachael Harris",
		"Greg Bronson",
		"John Eric Brown",
		"Robert Harriell",
		"Robert Resto",
		"Charline Tetiyevsky",
		"Rob Minkoff",
		"Douglas Wick",
		"Bruce Jeol Rubin",
	}
	h2002["28 days later"] = []string{
		"Alex Palmer",
		"Bindu De Stoppani",
		"Jukka Hiltunen",
		"David Schneider",
		"Cillian Murphy",
		"Toby Sedgwick",
		"Naomie Harris",
		"Noah Huntley",
		"Christopher Dunne",
		"Emma Hitching",
		"Alexander Delamere",
		"Kim McGarrity",
		"Brendan Gleeson",
		"Megan Burns",
		"Justin Hackney",
		"Luke Mably",
		"Stuart McQuarrie",
		"Ricci Harnett",
		"Leo Bill",
		"Junior Laniyan",
		"Ray Panthaki",
		"Christopher Eccleston",
		"Sanjay Rambaruth",
		"Marvin Campbell",
		"Adrian Christopher",
		"Richard Dwyer",
		"Nick Ewans",
		"Terry John",
		"Paul Kasey",
		"Sebastian Knapp",
		"Nicholas James Lewis",
		"Jenni Lush",
		"Tristan Matthiae",
		"Jeffrey Rann",
		"Joelle Simpson",
		"Al Stokes",
		"Steen Young",
		"Danny Boyle",
		"Alex Garland",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Hollywood2002Key, EntertainmentKey, MovesKey, h2002, true, false, false)
	return M
}

func Hollywood2003() dataset.SearchSystem_ {
	h2003 := map[string][]string{}
	h2003["Oldboy"] = []string{
		"Choi Min-sik",
		"Yoo Ji-tae",
		"Kang Hye-jeong",
		"Kim Byeong-Ok",
		"Ji Dae-han",
		"Oh Dal-su",
		"Lee Seung-shin",
		"Yoon Jin-seo",
		"Oh Tae-kyung",
		"Yoo Yeon-seok",
		"Il-han Oo",
		"Lee Young-hee",
		"Kim Young Ae",
		"Mi Mi Lee",
		"Jae-Duk Han",
		"Jung Ae Kwak",
		"San Kim",
		"Chae-soo Jang",
		"Seol-a Im",
		"Syd Lim",
		"Chang-hak Choi",
		"Bi-Joon Shin",
		"Seok-jae Seong",
		"Choi Jae-sup",
		"Jin-Yool Yoon",
		"Seon-bok Mun",
		"Park Jae-woong",
		"Oh Soon-tae",
		"Hong-Pyo Lee",
		"Geun-Seok Park",
		"Heo Myeong-haeng",
		"Kim Won-jung",
		"Sung-Gyu Park",
		"Jung-pil Lee",
		"Seon-Rang Han",
		"Beom-sik Sin",
		"Jung-ok Han",
		"Dong Hyun Baek",
		"Myeong-cheol Ju",
		"Ji-hun Park",
		"Choon-Beom Choi",
		"Myeong-seok Seo",
		"Woo-Jae Jeon",
		"Jo Sang-gyeong",
		"Young-ju Oh",
		"Lee Ji-hye",
		"Joong-hyun Ji",
		"Sang-moo Moon",
		"Oh Gwang-Rok",
		"Lee Dae-yeon",
		"Park Myung-shin",
		"Su-hyeon Kim",
		"Yi Yong",
		"Park Chan-wook",
		"Garon Tsuchyia",
		"Nobukai Minegishi",
	}
	h2003["finding nemo"] = []string{
		"Albert Brooks",
		"Ellen DeGeneres",
		"Alexander Gould",
		"Willem Dafoe",
		"Brad Garrett",
		"Allison Janney",
		"Austin Pendleton",
		"Stephen Root",
		"Vicki Lewis",
		"Joe Ranft",
		"Geoffrey Rush",
		"Andrew Stanton",
		"Elizabeth Perkins",
		"Nicholas Bird",
		"Bob Peterson",
		"Barry Humphries",
		"Eric Bana",
		"Bruce Spence",
		"Bill Hunter",
		"LuLu Ebeling",
		"Jordan Ranft",
		"Erica Beck",
		"Erik Per Sullivan",
		"John Ratzenberger",
		"Andrew Stanton",
		"Lee Unkrich",
	}
	h2003["the last samurai"] = []string{
		"Ken Watanabe",
		"Tom Cruise",
		"William Atherton",
		"Chad Lindberg",
		"Ray Godshall Sr.",
		"Billy Connolly",
		"Tony Goldwyn",
		"Masato Harada",
		"Masashi Odate",
		"John Koyama",
		"Timothy Spall",
		"Shichinosuke Nakamura",
		"Togo Igawa",
		"Satoshi Nikaido",
		"Shintaro Wada",
		"Shin Koyamada",
		"Hiroyuki Sanada",
		"Shun Sugata",
		"Koyuki",
		"Sosuke Ikematsu",
		"Aoi Minato",
		"Seizô Fukumoto",
		"Shoji Yoshihara",
		"Kosaburo Nomura IV",
		"Takashi Noguchi",
		"Noguchi Takayuki",
		"Sven Toorvald",
		"Scott Wilson",
		"Yuki Matsuzaki",
		"Mitsuyuki Oishi",
		"Jiro Wada",
		"Hiroshi Watanabe",
		"Yusuke Myochin",
		"Hiroaki Amano",
		"Kenta Daibo",
		"Koji Fujii",
		"Makoto Hashiba",
		"Shimpei Horinouchi",
		"Takashi Kora",
		"Shane Kosugi",
		"Takeshi Maya",
		"Seiji Mori",
		"Lee Murayama",
		"Takeru Shimizu",
		"Shinji Suzuki",
		"Hisao Takeda",
		"Ryoichiro Yonekura",
		"Ryoichi Noguchi",
		"Emmy Collins",
		"Darin Fujimori",
		"Eiji Inoue",
		"Junichi Yanagita",
		"Edward Zwick",
		"John Logan",
	}
	h2003["gothika"] = []string{
		"Halle Berry",
		"Robert Downey Jr.",
		"Charles S. Dutton",
		"John Carroll Lynch",
		"Bernard Hill",
		"Penélope Cruz",
		"Dorian Harewood",
		"Bronwen Mantel",
		"Kathleen Mackey",
		"Matthew G. Taylor",
		"Michel Perron",
		"Andrea Sheldon",
		"Anana Rydvald",
		"Laura Mitchell",
		"Amy Sloan",
		"Noel Burton",
		"Benz Antoine",
		"Andy Bradshaw",
		"Jason Cavalier",
		"Jasson Finney",
		"Terry Simpson",
		"Kwasi Songui",
		"Caroline Van Vlaardingen",
		"Al Vandecruys",
		"Noah Bernett",
		"Mathieu Kassovitz",
		"Sebastian Gutierrze",
	}
	h2003["johnny english"] = []string{
		"Rowan Atkinson",
		"Tasha de Vasconcelos",
		"Ben Miller",
		"Greg Wise",
		"Douglas McFerran",
		"Steve Nicolson",
		"Terence Harvey",
		"Kevin McNally",
		"Tim Pigott-Smith",
		"Nina Young",
		"Rowland Davies",
		"Natalie Imbruglia",
		"Philippa Fordham",
		"John Malkovich",
		"Tim Berrington",
		"Simon Bernstein",
		"Martin Lawton",
		"Neville Phillips",
		"Oliver Ford Davies",
		"Takuya Matsumoto",
		"Peter Tenn",
		"Sam Beazley",
		"Kevin Moore",
		"Faruk Pruti",
		"Marc Danbury",
		"Jack Raymond",
		"Jenny Galloway",
		"Haylie Ecker",
		"Tania Davis",
		"Eos Chater",
		"Gay-Yee Westerhoff",
		"Chris Tarrant",
		"James Greene",
		"Clive Graham",
		"Trevor McDonald",
		"Clare Beckwith",
		"James Embree",
		"Irene Hamilton",
		"Philip Harvey",
		"Peter Howitt",
		"Serena Lorien",
		"Norman Campbell Rees",
		"Laurence Richardson",
		"Scott Samain",
		"Prunella Scales",
		"Leonard Silver",
		"Tina Simmons",
		"Glenn Webster",
		"Philip Widdicombe",
		"Yana Yanezic",
		"Peter Howitt",
		"Neal Purvis",
		"Robert Wade",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Hollywood2003Key, EntertainmentKey, MovesKey, h2003, true, false, false)
	return M
}

func Hollywood2004() dataset.SearchSystem_ {
	h2004 := map[string][]string{}
	h2004["notebook"] = []string{
		"Ryan Gosling",
		"Rachel McAdams",
		"Joan Allen",
		"Jamie Anne Allman",
		"Renée Amber",
		"Sasha Azevedo",
		"Obba Babatundé",
		"Matthew Barry",
		"Ronald Betts",
		"Frederick Bingham",
		"Elizabeth Bond",
		"Milton Buras",
		"Bradley D. Capshaw",
		"Daniel Chamblin",
		"Kevin Connolly",
		"John Cundari",
		"Daniel Czekalski",
		"Nancy De Mayo",
		"James Scott Deaton",
		"The Amazebian",
		"Starletta DuPois",
		"Jennifer Echols",
		"Madison Wayne Ellis",
		"Leslea Fisher",
		"Robert Fraisse",
		"Michael D. Fuller",
		"James Garner",
		"Mark Garner",
		"Ed Grady",
		"Erin Guzowski",
		"Deborah Hobart",
		"Robert Ivey",
		"Tim Ivey",
		"Sylvia Jefferies",
		"Mark Johnson",
		"Eve Kagan",
		"Jude Kitchens",
		"Geoffrey Knight",
		"Rebecca Koon",
		"Kweli Leapart",
		"Pat Leonard",
		"Julianne Keller Lewis",
		"Todd Lewis",
		"James Marsden",
		"James Middleton",
		"Cullen Moss",
		"Lindy Newton",
		"Riley Novak",
		"Meredith O'Brien",
		"Tim O'Brien",
		"Chuck Pacheco",
		"Jonathan Parks Jordan",
		"Scott Ritenour",
		"Hugh Robertson",
		"Peter Rosenfeld",
		"Gena Rowlands",
		"Andrew Schaff",
		"Matt Shelly",
		"Sam Shepard",
		"Anthony-Michael Q. Thomas",
		"David Thornton",
		"Sherril M. Turner",
		"Heather Wahlquist",
		"Robert Washington",
		"Barbara Weetman",
		"Stephanie Wheeler",
		"Sandra Elise Williams",
		"Meredith Zealy",
		"David Abrams",
		"Patricia Buckley-Moss",
		"Jonathan Dickson",
		"Taylor Engel",
		"Bob Forrest",
		"Paul Johansson",
		"Michael L. Nesbitt",
		"Adam Sumner",
		"Cameron Thrower",
		"Bruce Williamson",
		"Quincy Lamar Wills",
		"Nick Cassavetes",
		"Nicholas Sparks",
	}
	h2004["the incredibles"] = []string{
		"Craig T. Nelson at an event for The Proposal (2009)",
		"Craig T. Nelson",
		"Bob Parr/Mr. Incredible(voice)",
		"Holly Hunter at an event for The 61st Primetime Emmy Awards (2009)",
		"Holly Hunter",
		"Helen Parr/Elastigirl(voice)",
		"Samuel L. Jackson at an event for Resurrecting the Champ (2007)",
		"Samuel L. Jackson",
		"Lucius Best/Frozone(voice)",
		"Jason Lee in Kissing a Fool (1998)",
		"Jason Lee",
		"Buddy Pine/Syndrome(voice)",
		"Dominique Louis",
		"Dominique Louis",
		"Bomb Voyage(voice)",
		"Theodore Newton",
		"Theodore Newton",
		"Newsreel Narrator(voice) (as Teddy Newton)",
		"Jean Sincere",
		"Jean Sincere",
		"Mrs. Hogenson(voice)",
		"Eli Fucile",
		"Eli Fucile",
		"Maeve Andrews",
		"Wallace Shawn",
		"Spencer Fox",
		"Lou Romano",
		"Wayne Canney",
		"Sarah Vowell",
		"Michael Bird",
		"Elizabeth Peña",
		"Bud Luckey",
		"Brad Bird",
		"Bret 'Brook' Parker",
		"Kimberly Adair Clark",
		"John Ratzenberger",
		"Mark Andrews",
		"Nicholas Bird",
		"Louis Martin Braga III",
		"Mary Elizabeth Clark",
		"Pete Docter",
		"Louis Gonzales",
		"Elizabeth Greenberg",
		"Juliet Greenberg",
		"Billy Guardino",
		"Dennis 'D.J.' Jennings",
		"Ollie Johnston",
		"Bradford Lewis",
		"Ted Mathot",
		"Jazzie Mahannah",
		"Randy Nelson",
		"Bob Peterson",
		"Jeff Pidgeon",
		"Juliet Pokorny",
		"Joe Ranft",
		"Lori Richardson",
		"A.J. Riebli III",
		"Katherine Ringgold",
		"Stephen Schaffer",
		"Bob Scott",
		"Peter Sohn",
		"Andrew Stanton",
		"Frank Thomas",
		"Pamela Gaye Walker",
		"Patrick Walker",
		"Deirdre Warin",
		"Brad Bird",
	}
	h2004["shreks 2"] = []string{
		"Mike Myers",
		"Eddie Murphy",
		"Cameron Diaz",
		"Julie Andrews",
		"Antonio Banderas",
		"John Cleese",
		"Rupert Everett",
		"Jennifer Saunders",
		"Aron Warner",
		"Kelly Asbury",
		"Cody Cameron",
		"Addams Family Premiere",
		"Christopher Knights",
		"David P. Smith",
		"Mark Moseley",
		"Kelly Cooney Cilella",
		"Wendy Bilanski",
		"Larry King",
		"Guillaume Aretos",
		"Chris Miller",
		"Latifa Ouaou",
		"Alina Phelan",
		"Erika Thomas",
		"Joan Rivers",
		"Andrew Adamson",
		"Jonathan Ross",
		"Kate Thornton",
		"Andrew Adamson",
		"Kelly Asbury",
		"Conrad Vernon",
		"William Steig",
	}
	h2004["kung fu hustle"] = []string{
		"Stephen Chow",
		"Xiaogang Feng",
		"Wah Yuen",
		"Zhihua Dong",
		"Danny Kwok-Kwan Chan",
		"Tze-Chung Lam",
		"Siu-Lung Leung",
		"Qiu Yuen",
		"Kai-Man Tin",
		"Kang Xi Jia",
		"Fung Hak-On",
		"Shengyi Huang",
		"Suet Lam",
		"Cheung-Yan Yuen",
		"Chi Ling Chiu",
		"Xing Yu",
		"Yibai Zhang",
		"Si Lu Ren",
		"Xiaolong Ding",
		"Mingming Zhang",
		"Oliver Wong",
		"Kai Shi Chen",
		"Wellson Chin",
		"Wen Hui He",
		"David Hung",
		"Billy Ma",
		"Hao Tian Yuan",
		"Min-Hun Fung",
		"Nang Yang",
		"Chao Xia Liu",
		"Stephen Chow",
	}
	h2004["garfiled"] = []string{
		"Breckin Meyer",
		"Jennifer Love Hewitt",
		"Stephen Tobolowsky",
		"Bill Murray",
		"Evan Arnold",
		"Mark Christopher Lawrence",
		"Vanessa Campbell",
		"Daamen J. Krall",
		"Rufus Gifford",
		"Randee Reicher",
		"Ryan McKasson",
		"Susan Moore",
		"Eve Brent",
		"Bill Hoag",
		"Michael Monks",
		"Mel Rodriguez",
		"Juliette Goglia",
		"Ben Kronen",
		"Fabio Serafini",
		"Jerry Hauck",
		"Jerry Giles",
		"Evan Helmuth",
		"Annalea Rawicz",
		"Danny Gil",
		"Leyna Nguyen",
		"Frank Payne",
		"Joe Ochman",
		"Joe Bays",
		"Danna Hansen",
		"Joseph Edward Taylor",
		"John F. Schaffer",
		"Joe Towne",
		"Joseph Hale",
		"Nick Cannon",
		"Alan Cumming",
		"David Eigenberg",
		"Brad Garrett",
		"Jimmy Kimmel",
		"Debra Messing",
		"Richard Kind",
		"Debra Jo Rupp",
		"Jordan Kaiser",
		"Wyatt Smith",
		"Alyson Stoner",
		"Peter Hewitt",
		"Jim Davis",
		"Joel Cohen",
		"Alec Sokolow",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Hollywood2004Key, EntertainmentKey, MovesKey, h2004, true, false, false)
	return M
}

func Hollywood2005() dataset.SearchSystem_ {
	h2005 := map[string][]string{}
	h2005["charlie and the choclate factory"] = []string{
		"Johnny Depp",
		"Freddie Highmore",
		"David Kelly",
		"Helena Bonham Carter",
		"Noah Taylor",
		"Missi Pyle",
		"James Fox",
		"Deep Roy",
		"Christopher Lee",
		"Adam Godley",
		"Franziska Troegner",
		"AnnaSophia Robb",
		"Julia Winter",
		"Jordan Fry",
		"Philip Wiegratz",
		"Blair Dunlop",
		"Liz Smith",
		"Eileen Essell",
		"David Morris",
		"Nitin Ganatra",
		"Shelley Conn",
		"Chris Cresswell",
		"Philip Philmar",
		"Tony Kirwood",
		"Todd Boyce",
		"Nayef Rashed",
		"Menis Yousry",
		"Harry Taylor",
		"Hubertus Geller",
		"Francesca Hunt",
		"Garrick Hagon",
		"Kevin Eldon",
		"Mark Heap",
		"Roger Frost",
		"Oscar James",
		"Colette Appleby",
		"Debora Weston",
		"Annette Badland",
		"Steve Hope Wynne",
		"Geoffrey Holder",
		"Danny Elfman",
		"Tim Burton",
		"Roald Dahi",
	}
	h2005["madagscar"] = []string{
		"Ben Stiller",
		"Chris Rock",
		"David Schwimmer",
		"Jada Pinkett Smith",
		"Sacha Baron Cohen",
		"Cedric The Entertainer",
		"Andy Richter",
		"Tom McGrath",
		"Christopher Knights",
		"Chris Miller",
		"Eric Darnell",
		"David Cowgill",
		"Steve Apostolina",
		"Elisa Gabrielli",
		"Devika Parikh",
		"David P. Smith",
		"Cody Cameron",
		"Bob Saget",
		"Billy Dobson",
		"Sheb Wooley",
		"Eric Darnell",
		"Tom McGrath",
		"Mark Burton",
		"Billy Frolick",
	}
	h2005["zathura: a space adventure"] = []string{
		"Jonah Bobo",
		"Josh Hutcherson",
		"Dax Shepard",
		"Kristen Stewart",
		"Tim Robbins",
		"Frank Oz",
		"John Alexander",
		"Derek Mears",
		"Douglas Tait",
		"Joe Bucaro III",
		"Jeff Wolfe",
		"Stuart Scott",
		"Jon Favreau",
		"Chris Van Allsburg",
	}
	h2005["chicken little"] = []string{
		"Zach Braff",
		"Garry Marshall",
		"Don Knotts",
		"Patrick Stewart",
		"Amy Sedaris",
		"Steve Zahn",
		"Joan Cusack",
		"Wallace Shawn",
		"Harry Shearer",
		"Fred Willard",
		"Catherine O'Hara",
		"Patrick Warburton",
		"Adam West",
		"Mark Walton",
		"Director Mark Dindal",
		"Dan Molina",
		"Joe Whyte",
		"Sean Elmore",
		"Evan Dunn",
		"Matthew Josten",
		"Kelly Hoover",
		"Will Finn",
		"Dara McGarry",
		"Mark Kennedy",
		"Brad Abrell",
		"Tom Amundsen",
		"Steve Bencich",
		"Greg Berg",
		"Julianne Buescher",
		"David Cowgill",
		"Terri Douglas",
		"Chris Edgerly",
		"Amanda Fein",
		"Caitlin Fein",
		"Pat Fraley",
		"Eddie Frierson",
		"Jackie Gonneau",
		"Archie Hahn",
		"Jason Harris",
		"Brittney Lee Harvey",
		"Brian Herskowitz",
		"Mandy Kaplan",
		"Nathan Kress",
		"Anne Lockhart",
		"Connor Matheus",
		"Mona Marshall",
		"Scott Menville",
		"Rene Mujica",
		"Jonathan Nichols-Navarro",
		"Paul Pape",
		"Aaron Spann",
		"Pepper Sweeney",
		"Linda Begonja",
		"Scott Conrad",
		"Nina Kaic",
		"Mile Kekin",
		"Mia Krajcar",
		"Edo Maajka",
		"Sven Medvesek",
		"Igor Mesin",
		"Kresimir Mikic",
		"Ivica Zadro",
		"Ljubo Zecevic",
		"Mark Dindal",
		"Mark Kennedy",
	}
	h2005["pride and prejudice"] = []string{
		"Keira Knightley",
		"Talulah Riley",
		"Rosamund Pike",
		"Jena Malone",
		"Carey Mulligan",
		"Donald Sutherland",
		"Brenda Blethyn",
		"Claudie Blakley",
		"Sylvester Morand",
		"Simon Woods",
		"Kelly Reilly",
		"Matthew Macfadyen",
		"Pip Torrens",
		"Janet Whiteside",
		"Sinead Matthews",
		"Roy Holder",
		"Rupert Friend",
		"Tom Hollander",
		"Jay Simpson",
		"Judi Dench",
		"Rosamund Stephen",
		"Samantha Bloom",
		"Cornelius Booth",
		"Penelope Wilton",
		"Peter Wight",
		"Meg Wynn Owen",
		"Tamzin Merchant",
		"Moya Brady",
		"Lambton Maid",
		"Mark Arends",
		"Billy Burke",
		"Francesca Casale",
		"Kate Copeland",
		"Kristin Michelle Duncil",
		"LynNita Ellis",
		"Edward Hayes-Neary",
		"Stephen Humby",
		"Hannah Hutchins",
		"Bret Jones",
		"Mark Joslin",
		"Katia Louise",
		"Pamela Martin",
		"John C. McDonnell",
		"Arnold Montey",
		"Julene Renee",
		"Olivia Rosewood",
		"Liam Thomas",
		"Joe Wright",
		"Jane Austen",
	}
	M := dataset.SearchSystem_{}
	M.Constructor() // important
	M.Include(Hollywood2005Key, EntertainmentKey, MovesKey, h2005, true, false, false)
	return M
}

func BuildMovies() MoviesParcel {
	m2001, m2002, m2003, m2004, m2005 :=
		MarathiChitrapat2001(), MarathiChitrapat2002(), MarathiChitrapat2005(), MarathiChitrapat2004(), MarathiChitrapat2005()
	b2001, b2002, b2003, b2004, b2005 :=
		Bollywood2001(), Bollywood2002(), Bollywood2005(), Bollywood2004(), Bollywood2005()
	e2001, e2002, e2003, e2004, e2005 :=
		Hollywood2001(), Hollywood2002(), Hollywood2005(), Hollywood2004(), Hollywood2005()

	me2001, mc2001, mf2001, mb2001, mi2001 := m2001.Manager(MarathiChitrapat2001Key)
	me2002, mc2002, mf2002, mb2002, mi2002 := m2002.Manager(MarathiChitrapat2002Key)
	me2003, mc2003, mf2003, mb2003, mi2003 := m2003.Manager(MarathiChitrapat2003Key)
	me2004, mc2004, mf2004, mb2004, mi2004 := m2004.Manager(MarathiChitrapat2004Key)
	me2005, mc2005, mf2005, mb2005, mi2005 := m2005.Manager(MarathiChitrapat2005Key)

	be2001, bc2001, bf2001, bb2001, bi2001 := b2001.Manager(Bollywood2001Key)
	be2002, bc2002, bf2002, bb2002, bi2002 := b2002.Manager(Bollywood2002Key)
	be2003, bc2003, bf2003, bb2003, bi2003 := b2003.Manager(Bollywood2003Key)
	be2004, bc2004, bf2004, bb2004, bi2004 := b2004.Manager(Bollywood2004Key)
	be2005, bc2005, bf2005, bb2005, bi2005 := b2005.Manager(Bollywood2005Key)

	ee2001, ec2001, ef2001, eb2001, ei2001 := e2001.Manager(Hollywood2001Key)
	ee2002, ec2002, ef2002, eb2002, ei2002 := e2002.Manager(Hollywood2002Key)
	ee2003, ec2003, ef2003, eb2003, ei2003 := e2003.Manager(Hollywood2003Key)
	ee2004, ec2004, ef2004, eb2004, ei2004 := e2004.Manager(Hollywood2004Key)
	ee2005, ec2005, ef2005, eb2005, ei2005 := e2005.Manager(Hollywood2005Key)

	parcel1 := EntertainmentParcel{Event: me2001, Category: mc2001, Field: mf2001, Book: mb2001, MappedItems: mi2001}
	parcel2 := EntertainmentParcel{Event: me2002, Category: mc2002, Field: mf2002, Book: mb2002, MappedItems: mi2002}
	parcel3 := EntertainmentParcel{Event: me2003, Category: mc2003, Field: mf2003, Book: mb2003, MappedItems: mi2003}
	parcel4 := EntertainmentParcel{Event: me2004, Category: mc2004, Field: mf2004, Book: mb2004, MappedItems: mi2004}
	parcel5 := EntertainmentParcel{Event: me2005, Category: mc2005, Field: mf2005, Book: mb2005, MappedItems: mi2005}
	parcel6 := EntertainmentParcel{Event: be2001, Category: bc2001, Field: bf2001, Book: bb2001, MappedItems: bi2001}
	parcel7 := EntertainmentParcel{Event: be2002, Category: bc2002, Field: bf2002, Book: bb2002, MappedItems: bi2002}
	parcel8 := EntertainmentParcel{Event: be2003, Category: bc2003, Field: bf2003, Book: bb2003, MappedItems: bi2003}
	parcel9 := EntertainmentParcel{Event: be2004, Category: bc2004, Field: bf2004, Book: bb2004, MappedItems: bi2004}
	parcel10 := EntertainmentParcel{Event: be2005, Category: bc2005, Field: bf2005, Book: bb2005, MappedItems: bi2005}
	parcel11 := EntertainmentParcel{Event: ee2001, Category: ec2001, Field: ef2001, Book: eb2001, MappedItems: ei2001}
	parcel12 := EntertainmentParcel{Event: ee2002, Category: ec2002, Field: ef2002, Book: eb2002, MappedItems: ei2002}
	parcel13 := EntertainmentParcel{Event: ee2003, Category: ec2003, Field: ef2003, Book: eb2003, MappedItems: ei2003}
	parcel14 := EntertainmentParcel{Event: ee2004, Category: ec2004, Field: ef2004, Book: eb2004, MappedItems: ei2004}
	parcel15 := EntertainmentParcel{Event: ee2005, Category: ec2005, Field: ef2005, Book: eb2005, MappedItems: ei2005}

	ready := []EntertainmentParcel{parcel1, parcel2, parcel3, parcel4, parcel5, parcel6, parcel7, parcel8, parcel9, parcel10, parcel11, parcel12, parcel13, parcel14, parcel15}
	pack := MoviesParcel{Pack: ready}
	return pack
}

func MoviesEvents() []string {
	events := []string{}
	openBuild := BuildMovies()
	for _, event := range openBuild.Pack {
		events = append(events, event.Event)
	}
	return events
}

func MoviesCategory() string {
	category := []string{}
	token := BuildMovies().Pack
	for _, cat := range token {
		category = append(category, cat.Category)
	}
	category = dataset.EraseDuplicate(category)
	cat := category[0]
	fmt.Println(category)
	return cat
}

func MoviesBook() string {
	fi := ""
	token := BuildMovies().Pack
	for _, cat := range token {
		fi = cat.Book
	}
	return fi
}

func MoviesLists() []string {
	ma := []string{}
	token := BuildMusic().Pack
	for _, t := range token {
		for items := range t.MappedItems {
			ma = append(ma, items)
		}
	}
	return ma
}

func MoviesSheet() map[string][]string {
	sheet := map[string][]string{}
	token := BuildMusic().Pack
	for _, t := range token {
		maps.Copy(sheet, t.MappedItems)
	}
	return sheet
}
