// Package update guesses can be made via hit character, actor played by director
package update

import (
	"fmt"
	"maps"
	"nyg/dataset"
)

type EntertainmentParcel struct {
	Event       string
	Category    string
	Field       string
	Book        string
	MappedItems map[string][]string
}

type ShowsParcel struct {
	Pack []EntertainmentParcel
}

// keys
const (
	Hindi2005ShowsKey = "HINDI 2005"
	Hindi2000ShowsKey = "HINDI 2000"

	English2005ShowsKey = "ENGLISH 2005"
	English2001ShowsKey = "ENGLISH 2001"
	English2012ShowsKey = "ENGLISH 2012"

	Marathi2001ShowsKey = "MARATHI 2001"
	Marathi2014ShowsKey = "MARATHI 2014"

	ShowsKey         = "SHOWS"
	EntertainmentKey = "Entertainment"
)

func ShowsHindi2000() dataset.SearchSystem_ {
	h2000 := map[string][]string{}
	h2000["son pari"] = []string{
		"Mrinal Kulkarni",
		"Son Pari",
		"Son Aunty",
		"Tanvi Hegde",
		"Frooty",
		"Tooty",
		"Kaivalya Chheda",
		"Jeff D'souza",
		"Agast Annand",
		"Ghanshyam",
		"Ashok Lokhande",
		"Altamash",
		"Altu",
		"Yashraj Kushwaha",
		"Yash",
		"Vinamra Pancharia",
		"Karan",
		"Khujli",
		"Akul Tripathi",
		"Bunty",
		"Shashikala Jawalkar",
		"Dadi",
		"Deepshikha Nagpal",
		"Ruby",
		"Tina Parekh",
		"Jennifer D'Souza",
		"Anita Kanwal",
		"Mrs. Dhillon",
		"Harsh Khurana",
		"Deepak",
		"Vivek Mushran",
		"Rohit",
		"Harjot Singh Dhaliwal",
		"Dharm",
		"Ashyapak Ji",
		"Karan Arora",
		"Niraj Vikram",
		"Sameer Kulkarni",
		"Vijay Krishna Acharya",
		"Gayatri Chandrashekaran",
		"Akul Tripathi",
		"Niraj Vikram",
	}
	h2000["shakala boom boom"] = []string{
		"Kinshuk Vaidya",
		"Sanju",
		"Hansika Motwani",
		"Hansika Motwani",
		"Karuna",
		"shona",
		"Jennifer Winget",
		"Piya",
		"Sainee Raj",
		"Ritu",
		"Kaivalya Chheda",
		"Neeraj",
		"Rahul Joshi",
		"Shaan",
		"Kurush Deboo",
		"Colonel K.K.",
		"Rajesh Balwani",
		"Mama Ji",
		"Tanvi Hegde",
		"Fruity",
		"Ankit Shah",
		"Sumit",
		"Vinod Kumar Singh",
		"Pawn Parkhi",
		"Saurbh Bharadwaj",
		"Niraj Vikram",
	}
	h2000["karishma kaa karishma"] = []string{
		"",
		"Jhanak Shukla",
		"Karishma",
		"Karishma Malhotra",
		"Sanjeev Seth",
		"Vikram",
		"Vikram Malhotra",
		"Eva Grover",
		"Sheetal",
		"Sheetal Malhotra",
		"Tisca Chopra",
		"Tisca Chopra",
		"Sheetal",
		"Mayyank Taandon",
		"Mayyank Taandon",
		"Rahul Malhotra",
		"Jamnadas Majethia",
		"Paresh Parekh",
		"Bhavana Balsawar",
		"Shraddha Parekh",
		"Shweta Basu Prasad",
		"Sweety Parekh",
		"Nupur Alankar",
		"Dolly",
		"Kurush Deboo",
		"Lappu",
		"Ankit Shah",
		"Swapna Joshi",
		"Aparna Ganesh",
		"Abid Hussain",
		"Raghuvir Shekawat",
	}
	h2000["kabhi sass bhi kabhi bahu thi"] = []string{
		"Smriti Malhotra-Irani",
		"Tulsi Mihir Virani",
		"Ronit Roy",
		"Mihir Virani",
		"Amar Upadhyay",
		"Mihir Mansukh Virani",
		"Sudha Shivpuri",
		"Govardhan Virani",
		"Hiten Tejwani",
		"Karan Mihir Virani",
		"Sumeet Sachdev",
		"Sandeep Baswana",
		"Sahil Hemant Virani",
		"Kamalika Guha Thakurta",
		"Gayatri Jamnadas Virani",
		"Riva Bubber",
		"Damini Gautam Virani",
		"Shilpa Saklani",
		"Ganga Joshi",
		"Apara Mehta",
		"Savita Mansukh Virani",
		"Tasneem Sheikh",
		"Mohini Mittal Virani",
		"Ritu Chaudhary",
		"Shoba Mehra Virani",
		"Akashdeep Saigal",
		"Ansh Mihir Virani",
		"Ketki Dave",
		"Daksha Himmat Virani",
		"Prachee Shah",
		"Pooja Hemant Virani",
		"Shakti Singh",
		"Mansukh Virani",
		"Hussain Kuwajerwala",
		"Chirag Virani",
		"Suvarna Jha",
		"Tripti",
		"Jaya Bhattacharya",
		"Payal Pratap Mehra",
		"Muni Jha",
		"Jamnadas Virani",
		"JD",
		"Jitendra Trehan",
		"Himmat Virani",
		"Karishma Tanna",
		"Indira Gandhi",
		"Indu",
		"Abhijit Khurana",
		"Tarun Hemant Virani",
		"Naman Shaw",
		"Nakul Virani",
		"Vivan Bhatena",
		"Abhishek Mehra",
		"Khyaati Khandke Keswani",
		"Sejal Anand Gandhi",
		"Vikas Sethi",
		"Abir Bhasin",
		"Rohit Bakshi",
		"Vishal Pratap Mehra",
		"Kiran Dubey",
		"Karishma Virani Dey",
		"Sudhir Dalvi",
		"Govardhan Virani",
		"Hansika Motwani",
		"Baavri Virani",
		"Jiten Lalwani",
		"Kiran Virani",
		"Mandira Bedi",
		"Dr. Mandira Kapadia",
		"Inder Kumar",
		"Mihir Mansukh Virani",
		"Narayani Shastri",
		"Saffron Anupam Kapadia",
		"Shabbir Ahluwalia",
		"Aniket Mehta",
		"Eva Grover",
		"Aarti Patel",
		"Virani Patel",
		"Resham Tipnis",
		"Saffron Anupam Kapadia",
		"Utkarsha Naik",
		"Pragya  Virani",
		"Govardhan",
		"Naveen Sanghvi",
		"Shilpa Mehta",
		"Deepak Verma",
		"Rahul",
		"Amit Sarin",
		"Sahil Virani",
		"Meenakshi Verma",
		"Prashant Bhatt",
		"Rakesh",
		"Meena Sonavane",
		"Amina",
		"Priyanka Raina",
		"Pushkin",
		"Romanchak Arora",
		"Anand Gandhi",
		"Sudha Chandran",
		"ACP Ragini",
		"Vishal Puri",
		"Raj Bhasin",
		"Gauri Pradhan Tejwani",
		"Nandini Karan Virani",
		"Ashlesha Sawant",
		"Shakti Anand",
		"Hemant Jamnadas Virani",
		"Rakshanda Khan",
		"Tanya Malhotra Virani",
		"Aman Verma",
		"Anupam Kapadia",
		"Pooja Ghai Rawal",
		"Suhasinee Virani",
		"Ravee Gupta",
		"Damini Gautam Virani",
		"Shahab Khan",
		"Achint Kaur",
		"Anup Shukla",
		"Tripathi",
		"Eijaz Khan",
		"Zuber Khan",
		"Sapna Sappu",
		"Sapna",
		"Chinky Jaiswal",
		"Bhoomi Virani",
		"Reshmi Ghosh",
		"Bhoomi Virani",
		"Mouni Roy",
		"Krishna Tulsi",
		"Seemadevi",
		"Sakshi Tanwar",
		"Parvati Om Agarwal",
		"Jhanki Devi",
		"Mehul Kajaria",
		"Harsh Virani",
		"Pulkit Samrat",
		"Laksh Virani",
		"Manav Vij",
		"Joydeep Virani",
		"Jarmanjeetsingh",
		"Rahul",
		"Shubhaavi Choksey",
		"Meera Singhania",
		"Gautami Kapoor",
		"Tulsi Virani",
		"Rahul",
		"Pooja Sharda",
		"Sneha",
		"Tuhina Vohra",
		"Prajakta Chirag Virani",
		"Tia Bajpai",
		"Vaidehi Laksh Virani",
		"Yash Pandit",
		"Laksh Virani",
		"Priya Bathija",
		"Ananya Chadha",
		"VS Prince Ratan",
		"Kratika Sengar",
		"Sugandi",
		"Rushali Arora",
		"Aarti Kiran Virani",
		"Salim Shah",
		"Aditya Gujral",
		"Dinesh Thakur",
		"Govardhan Virani",
		"Mahika Sharma",
		"Mahi",
		"Shweta Tiwari",
		"Prerna",
		"Jeetendra",
		"Mouli Ganguly",
		"Shaina",
		"Suhasini Mulay",
		"Kaushalya Malhotra",
		"Amita Chandekar",
		"Bavri Virani",
		"Mita Vashisht",
		"Trishna Agarwal",
		"Vishal Watwani",
		"Manthan Virani",
		"Prabhakar Tiwari",
		"Ravi",
		"Tanish Mahendru",
		"Ranvijay",
		"Gargi Patel",
		"Mrs. Kapadia",
		"Rio Kapadia",
		"Vikram Ahuja",
		"Amit Tandon",
		"Manthan Virani",
		"Alok Arora",
		"Tarun Virani",
		"Vikram Acharya",
		"Kabir",
		"Masumi Mevawala",
		"Savri Virani",
		"Rocky Verma",
		"Kaushik Ghatak",
		"Ashish Patil",
		"Jasbir Bhaati",
		"Santosh Bhatt",
		"Nishant",
		"Nivedita Basu",
		"Santosh Badal",
		"Supriya Khan",
		"Jatin Ravasia",
		"Bhupesh Kumar",
		"Rrahul Mevawala",
		"Jasbir R Bhati",
		"Ameet Gupta",
		"Rakesh Jaggi",
		"Shyam Maheshwari",
		"Pushpendra Singh",
		"Khwaja Mughal",
		"Ekta Kapoor",
	}
	h2000["shararat"] = []string{
		"Shruti Seth",
		"Jiya",
		"Tiya",
		"Farida Jalal",
		"Sushma",
		"Nani",
		"Karanvir Bohra",
		"Dhruv",
		"Mahesh Thakur",
		"Suraj",
		"Titu",
		"Shoma Anand",
		"Shanti",
		"Harsh Vasishtha",
		"Raja",
		"Aditi Shirwaikar",
		"Meeta",
		"Simple Kaul",
		"Parminder Sohni",
		"Pam",
		"ManminderPoonam Narula",
		"Radha Malhotra",
		"Suhail Jaffer",
		"Jai Malhotra",
		"Rinku Worah",
		"Eena",
		"Menaka Lalwani",
		"Tina",
		"Vaishnavi Sharma",
		"Bebo",
		"Daisy Irani",
		"Rani Devi",
		"Eva Grover",
		"Radha Malhotra",
		"Carran Kapoor",
		"Neel Bajaj",
		"Dhairya Oza",
		"Bittu",
		"Rajesh Gandhi",
		"Khurshed Lawyer",
		"Pinakin Desai",
		"Rajesh Balwani",
		"Krishna Bhatt",
		"Parikshit Sahni",
		"Khushwant Mehra",
		"Sumit Arora",
		"Ashiesh Roy",
		"Hemant Pandey",
		"Pandit",
		"parvaz khan pandey",
		"Millennium Rangaswamy",
		"Kanwarjeet Paintal",
		"Professor Bhulbhulaiya",
		"Kamini Khanna",
		"Girish Oak",
		"Karishma Tanna",
		"Natasha",
		"Teejay Sidhu",
		"Nisha",
		"Stella",
		"Rajesh Kumar",
		"Sheru Janglani",
		"Santa Singh",
		"Banta Singh",
		"Sheru Janglani",
		"Purab Kohli",
		"Dumketu",
		"Rakesh Srivastava",
		"Shammi",
		"Rani Devi",
		"Rajeev Mehta",
		"Anish Kumar",
		"Gopal Govardhan Gaekwad",
		"Pushtii Shakti",
		"Deepshikha Nagpal",
		"Riya",
		"Sanket Jaiswal",
		"Mr. Mittal",
		"Lilliput",
		"Ravi Raj",
		"Vishal Malhotra",
		"Ranjha",
		"Aarati Moorjani",
		"Heer",
		"Kiku Sharda",
		"Mr. ChatPata",
		"Swapnil Joshi",
		"Parmeet",
		"Krishnakant Goswami",
		"Phullu",
		"Amit Varma",
		"Rocky",
		"Gaurav Gera",
		"Sehdev",
		"Salil Acharya",
		"Prince",
		"Kenneth Desai",
		"Teetu Tasty",
		"Neelu Kohli",
		"Kunal Kumar",
		"Bluff Master Jayanti lal",
		"Harsh Khurana",
		"Lakalabu",
		"Kalabu",
		"Lalabu",
		"Bobby Bedi",
		"Ankit Shah",
		"Rohan",
		"Swati Bajpai",
		"Babli",
		"Kitu Gidwani",
		"Marinda",
		"Kavi Kumar Azad",
		"Lucky",
		"Vivek Shauq",
		"Dr. Chaddha",
		"Nirmal Soni",
		"Rajiv Mehra",
		"Sanjeev Jaiswal",
		"Niraj Vikram",
	}
	S := dataset.SearchSystem_{}
	S.Constructor() // important
	S.Include(Hindi2000ShowsKey, EntertainmentKey, ShowsKey, h2000, false, true, false)
	return S
}

func ShowsHindi2005() dataset.SearchSystem_ {
	h2005 := map[string][]string{}
	h2005["hero bhakti ki shakti"] = []string{
		"Shilpa Tulaskar",
		"Sunaina Sehgal",
		"Lavina Tandon",
		"Charlotte",
		"Mayyank Taandon",
		"Avi Sehgal",
		"Kavi Kumar Azad",
		"Dhappi",
		"Rupali Suri",
		"Bablie",
		"Nirmal Soni",
		"Dholu",
		"Vijay Aidasani",
		"Principal Karnal Raghavan",
		"Harshil Mavani",
		"Vicky",
		"Kishan Savjani",
		"Raju Madan Saxena",
		"Sumit Pathak",
		"Joy Sehgal",
		"Sachin Nayak",
		"Umbrella Man",
		"Mandira Bedi",
		"Durga Ma",
		"Rakesh Thareja",
		"Prem Prakash Sharma",
		"Amit K. Sinha",
		"Chumbakchu",
		"Dhairya Oza",
		"Chunky Nayyar",
		"Vijay Ganju",
		"Cactus Cola",
		"Farida Jalal",
		"Bebe",
		"Milind Ashok Dhoke",
		"Karan Arora",
		"Ashu Dhaliwal",
		"Imtiaz Alam",
		"Waseem Sabir",
		"Abhishek Sinha",
		"Rohit Gahlowt",
		"Milind Ashok Dhoke",
	}
	h2005["M.A.D"] = []string{
		"Shilarna Vaze",
		"Chinu",
		"Palak",
		"Abhas",
		"Harun Robert",
		"Rob",
	}
	S := dataset.SearchSystem_{}
	S.Constructor() // important
	S.Include(Hindi2005ShowsKey, EntertainmentKey, ShowsKey, h2005, false, true, false)
	return S
}

func ShowsEnglish2001() dataset.SearchSystem_ {
	e2001 := map[string][]string{}
	e2001["the fairly OddParents"] = []string{
		"Tara Strong",
		"Tara Strong",
		"Timmy Turner",
		"Daran Norris",
		"Cosmo",
		"Susanne Blakeslee",
		"Wanda",
		"Carlos Alazraqui",
		"Mr. Crocker",
		"Mrs. Crocker",
		"Grey DeLisle",
		"Vicky",
		"Principal Waxelplax",
		"Jim Ward",
		"Chet Ubetcha",
		"Doug Dimmadome",
		"Dee Bradley Baker",
		"Sanjay",
		"Elmer",
		"Gary LeRoi Gray",
		"AJ",
		"A.J.",
		"Rob Paulsen",
		"Mark Chang",
		"Bucky McBadbat",
		"Jason Marsden",
		"Chester McBadbat",
		"Chester",
		"Butch Hartman",
		"Dr. Rip Studwell",
		"Dionne Quan",
		"Trixie Tang",
		"Trixie",
		"Faith S. Abrahams",
		"Francis",
		"Maddie Taylor",
		"Sparky",
		"Frankie Muniz",
		"Chester McBadbat",
		"Kevin Michael Richardson",
		"Dark Laser",
		"Eric Bauza",
		"Foop",
		"Gnome Kid",
		"Kari Wahlgren",
		"Chloe Carmichael",
		"Ibrahim Muhammad",
		"Tom Kenny",
		"Cupid",
		"S. Scott Bullock",
		"Eliminator",
		"Jeff Bennett",
		"Catman",
		"Fair Bear",
		"Laraine Newman",
		"Queen Jipjurrulac",
		"Jay Leno",
		"Crimson Chin Doll",
		"Jane Carr",
		"Mama Cosma",
		"Chris Kirkpatrick",
		"Chip Skylark",
		"Skip Sparkypants",
		"Adam West",
		"Guy Moon",
		"Ben Stein",
		"Sanderson",
		"Head Pixie",
		"Chelsea Moon",
		"Cara Newman Ruyle",
		"Nanette Ubetcha",
		"Mick Wingert",
		"Clark Carmichael",
		"Mary Hart",
		"Fairy Hart",
		"Cheri Oteri",
		"Connie Carmichael",
		"Steve Lively",
		"Gilbert Gottfried",
		"Dr. Bender",
		"Wendell Bender",
		"Brian Dunkleman",
		"The April Fool",
		"Gary Anthony Sturgis",
		"Lead Eliminator",
		"Huginator",
		"Charlie Schlatter",
		"Dwight",
		"Garbage Man",
		"Savannah Moon",
		"Brendan Fraser",
		"Turbo Thunder",
		"Robbyn Kirmsse",
		"Singers",
		"Phil LaMarr",
		"Mr. Pfeiffer",
		"Denzel Washington",
		"Bobbi Page",
		"Rick Logan",
		"Tony Sirico",
		"Big Daddy",
		"Carol Huston",
		"Carol Houston",
		"Robert Costanzo",
		"Easter Bunny",
		"Dusty Moon",
		"Steve Marmel",
		"Bowling Pin",
		"Warthog",
		"Patrick Warburton",
		"Rick Fox",
		"Flash Williams",
		"Smooth Daley",
		"Jess Harnell",
		"Billy Blanks",
		"Jackie Mason",
		"Harvey Sandman",
		"Jack C. Thomas",
		"Norm MacDonald",
		"Norm the Genie",
		"Michael Gough",
		"Julie Chen Moonves",
		"Starlet",
		"Carolyn Lawrence",
		"Mrs. Sunshine",
		"Ernie Gilbert",
		"Chippington Skylark III",
		"Debi Derryberry",
		"Jimmy",
		"Robert Cait",
		"Norm the Genie",
		"DJ D-Wrek",
		"Jim J. Bullock",
		"Mr. Buxaplenty",
		"James Arnold Taylor",
		"Sprig Speevak",
		"Crash Nebula",
		"Richard Steven Horvitz",
		"Nika Futterman",
		"Ani",
		"Dana Carvey",
		"Schnozmo",
		"Tom Arnold",
		"Corporate Santa",
		"Justin Berfield",
		"Ving",
		"Bob Goen",
		"Bob Glimmer",
		"Don Newhouse",
		"Pops",
		"Michael Clarke Duncan",
		"Rockwell",
		"Dannah Feinglass Phirman",
		"Missy",
		"Edie Lehmann Boddicker",
		"Paul and Ned",
		"Paul Rugg",
		"Grim Reaper",
		"Hope Levy",
		"Kid Walla",
		"Baby Walla",
		"David Jeremiah",
		"Kenny Kidney",
		"Masseur",
		"Mo Collins",
		"Ma Speevak",
		"Scott Hamilton",
		"Mark Moseley",
		"Jason Bateman",
		"Tommy Turner",
		"Kimberly Brooks",
		"Walla",
		"Pat Fraley",
		"Lance Thruster",
		"Queen Latifah",
		"Pam Dromeda",
		"Patton Oswalt",
		"Crimson Chin Writer",
		"Redman",
		"Rapping Sanderson Pixie",
		"Alec Baldwin",
		"Future Timmy",
		"Method Man",
		"Rapping Head Pixie",
		"Gene Simmons",
		"Gary Le Mel",
		"Fairy Cowlick Jr",
		"Paul Stanley",
		"John Boatly",
		"Diana DeGarmo",
		"Cosmo",
		"Gary Conrad",
		"Ken Bruce",
		"Michelle Bryan",
		"Butch Hartman",
		"Sarah Frost",
		"John McIntyre",
		"Wincat Alcala",
		"Tuck Tucker",
		"Kevin Petrilak",
		"John Fountain",
		"Sherie Pollack",
		"George Elliott",
		"Keith Oliver",
		"Randy Myers",
		"Larry Leichliter",
		"Jaime Diaz",
		"Juli Murphy",
		"Butch Hartman",
		"Kevin Sullivan",
		"Ray DeLaurentis",
		"Steve Marmel",
		"William Schifrin",
		"Jack C. Thomas",
		"Scott Fellows",
		"Bob Colleary",
		"Sindy Boveda-Spackman",
		"Ed Valentine",
		"Alec Schwimmer",
		"Cynthia True",
		"Becky Wangberg",
		"Dave Thomas",
		"Joanna Lewis",
		"Bob Boyle",
		"Mike Bell",
		"Kristine Songco",
		"Spencer Green",
		"Tracy Berna",
		"Andrew Nicholls",
		"Darrell Vickers",
		"Amy Keating Rogers",
		"Tim O'Rourke",
		"Jim Hecht",
		"Karin Gutman",
		"Deirdre Brenner",
		"Thomas Krajewski",
		"Stephen Banks",
		"Jenny Nissenson",
		"Michael Lewis",
		"Lewis Foulke",
		"Joel Zimmer",
		"Greg Fideler",
		"Gene Grillo",
		"Laurie Israel",
		"Christopher J. Prouty",
		"Rachel Ruderman",
		"Gary Conrad",
		"Charlotte Fullerton",
		"Jonathan Butler",
		"Whitney Wetta",
		"Kiley Vorndran",
		"Christine Kolosov",
		"Henry Madden",
		"Nelson Recinos",
		"Robert Shellhorn",
		"George Chialtas",
		"Ken Kessel",
		"Debbie Baber",
		"Dan Yaccarino",
		"Suzanne Collins",
		"Lisa Eve Huberman",
		"Frederick Stroppel",
		"Annie Evans",
		"Susan Kim",
		"Alana Sanko",
		"Kate Long",
		"Gary Apple",
		"Geoff Stevenson",
		"J.P. Chanda",
		"Frederick Groel",
		"Rick Groel",
		"Jeffrey Kindley",
		"Justin Chanda",
	}
	e2001["noddy"] = []string{
		"David Kaye",
		"Noddy",
		"Iro Loupi",
		"Michael Dobson",
		"Big Ears",
		"Pavel Douglas",
		"Mr. Plod",
		"Sage Testini",
		"Skittles",
		"Joanna Ruiz",
		"Martha Monkey",
		"Tessie Bear",
		"Ben Small",
		"Mr. Sparks",
		"Sly",
		"Tabitha St. Germain",
		"Dinah Doll",
		"Miss Pink Cat",
		"Andrea Harris",
		"Hrysoula Papadopoulou",
		"Martin Skews",
		"Regine Candler",
		"Narrator",
		"Kathleen Barr",
		"Clockwork Mouse",
		"Britt McKillip",
		"Tessie Bear",
		"John Telfer",
		"Gobbo",
		"Felix McCabe",
		"Bumpy Dog",
		"Mr. Jumbo",
		"Don Brown",
		"Doug Parker",
		"Edward Chun",
		"Carrie Mullan",
		"Manny Petruzzelli",
		"Master Tubby Bear",
		"Chantal Strand",
		"Skittles",
		"Richard Newman",
		"Mr. Plod",
		"Teryl Rothery",
		"Mrs. Skittle",
		"Naomi Wilkinson",
		"Nic Osborne",
		"Byron Vaughns",
		"Michael Patrick Dobkins",
		"Henry Gilroy",
		"Don Gillies",
		"Enid Blyton",
		"Jymn Magon",
		"Pam Ally",
		"Tracy Berna",
		"Lawrence Braman",
		"Douglas Campbell",
		"D.C. Fontana",
		"Jay Fukuto",
		"Karl Geurs",
		"Kevin Hopps",
		"A.J. Lentini",
		"William Matheny",
		"Lisa Medway",
		"Kent Redeker",
		"Jennifer Rennels",
		"John Ludin",
		"Len Uhley",
		"Robin Kingsland",
	}
	S := dataset.SearchSystem_{}
	S.Constructor() // important
	S.Include(English2001ShowsKey, EntertainmentKey, ShowsKey, e2001, true, false, false)
	return S
}
func ShowsEnglish2005() dataset.SearchSystem_ {
	e2005 := map[string][]string{}
	e2005["ben10 2005-2008"] = []string{
		"Tara Strong",
		"Ben Tennyson",
		"Upgrade",
		"Paul Eiding",
		"Max Tennyson",

		"Meagan Moore",
		"Gwen Tennyson",
		"Pretty Girl",
		"Meric B",
		"Upchuck",
		"Dee Bradley Baker",
		"Wildmutt",
		"Stinkfly",
		"Jim Ward",
		"XLR8",
		"Diamondhead",
		"Steve Blum",
		"Heatblast",
		"Vilgax",
		"Richard McGonagle",
		"Four Arms",
		"Exo-Skull",
		"Fred Tatasciore",
		"Cannonbolt",
		"Ripjaws",
		"Richard Steven Horvitz",
		"Grey Matter",
		"Boy Nerdy Kid #",
		"Richard Doyle",
		"Enoch",
		"Forever King",
		"Dwight Schultz",
		"Dr. Animo",
		"Monitor",
		"Khary Payton",
		"Hex",
		"Automated",
		"Kari Wahlgren",
		"Charmcaster",
		"Toddler Hex",
		"Jennifer Hale",
		"Rojo",
		"Teacher",
		"Charlie Schlatter",
		"Kevin Levin",
		"Devlin Levin",
		"Adam Wylie",
		"JT",
		"Dave Wittenberg",
		"Upchuck",
		"Road Rage",
		"Kim Mai Guest",
		"Pinky",
		"Rob Paulsen",
		"Ditto",
		"Grey DeLisle",
		"Camille Mann",
		"Mrs.Mann",
		"Tom Kane",
		"Ultimos",
		"Arcticguana",
		"Kath Soucie",
		"Little Boy",
		"Tiffany",
		"Vanessa Marshall",
		"Female Cannonbolt",
		"Policewoman",
		"Catherine Cavadini",
		"Cathy Cavadini",
		"Cooper",
		"Nancy Linari",
		"Michael Gough",
		"Lt. Steel",
		"SACT Guy",
		"Billy West",
		"Kraab",
		"Patricia Lentz",
		"Shelby",
		"Mildred",
		"Cree Summer",
		"Frightwig",
		"Jeff Doucette",
		"Thumbskull",
		"Michael Dorn",
		"Vicktor",
		"Benvicktor",
		"John DiMaggio",
		"Baron Highway",
		"Vulkanus",
		"Bill Ratner",
		"Dave Fennoy",
		"Tetrax",
		"Radio Newscaster",
		"Josh Keaton",
		"Hector",
		"Hynden Walch",
		"Melissa Disney",
		"Armin Shimerman",
		"Slix Vigma",
		"Larry Cedar",
		"Howell",
		"Richard Green",
		"Walker Edmiston",
		"Marty",
		"Nolan North",
		"Henchman",
		"Robin Atkin Downes",
		"Jonah Melville",
		"Clancy Brown",
		"Kenko",
		"Neil Ross",
		"Wainwright",
		"Mark Thompson",
		"Vance Vetteroy",
		"Miguel Nájera",
		"Wes Green",
		"Rosalind Chao",
		"Councilwoman Liang",
		"Miriam Flynn",
		"Vera Tennyson",
		"Michael Reisz",
		"Kevin Levin",
		"Jennifer Malenke",
		"Missy",
		"Jess Harnell",
		"Keone Young",
		"Ishyama",
		"Jason Spisak",
		"Gatorboy",
		"Bettina Bush",
		"Kai Green",
		"Robert Picardo",
		"Leader Alien",
		"John Kassir",
		"Zombozo",
		"Mikey Kelley",
		"John Cygan",
		"Abel North",
		"Kangaroo Commando",
		"Rob Pinkston",
		"Todd Maplewood",
		"Robert Patrick",
		"Phil",
		"Rookie",
		"Nicholas Guest",
		"Clancy",
		"Jack Angel",
		"Technorg",
		"James Mathis III",
		"Enforcer Alien",
		"B.J. Ward",
		"Betty Jean Tennyson",
		"Greg Ellis",
		"Synaptak",
		"Scooter Tidwell",
		"Sebastian Montes",
		"Alex Soto",
		"Joe Casey",
		"Joe Kelly",
		"Duncan Rouleau",
		"Steven T. Seagle",
		"Greg Klein",
		"Tom Pugsley",
		"Marty Isenberg",
		"Greg Weisman",
		"Marsha F. Griffin",
		"Kevin Hopps",
		"Eugene Son",
		"Adam Beechen",
		"Jeff Hare",
		"Sean Jara",
		"Michael Jelenic",
		"James Phillips",
		"Amy Wolfram",
		"Steven Darancette",
		"Xandy Sussan",
	}
	e2005["power rangers S.P.D."] = []string{
		"Natalia Rosminati",
		"Sidney",
		"Brandon Jay McLaren",
		"Jack Landors",
		"Chris Violette",
		"Sky Tate",
		"Matt Sadowski",
		"Matt Sadowski",
		"Bridge Carson",
		"Monica May",
		"Monica May",
		"Elizabeth 'Z' Delgado",
		"Aly Purrott-Armstrong",
		"Sydney 'Syd' Drew",
		"John Tui",
		"Commander Anubis 'Doggie' Cruger",
		"Rene Naufahu",
		"Emperor Gruumm",
		"Stevedore",
		"Michelle Langstone",
		"Dr. Katherine 'Kat' Manx",
		"Barnie Duncan",
		"Piggy",
		"Mysticon",
		"Kelson Henderson",
		"Boom",
		"Devastation",
		"Jim McLarty",
		"Broodwing",
		"Josephine Davison",
		"Morgana",
		"Olivia James-Baird",
		"Mora",
		"Derek Judge",
		"James Gaylyn",
		"Orange Head",
		"General Benaag",
		"Brett Stewart",
		"Tandi Wright",
		"Isinia Cruger",
		"Aisynia Cruger",
		"Mark Wright",
		"Rhinix",
		"T-Top",
		"Aaron Murphy",
		"Sam",
		"Jason Hoyte",
		"Valko",
		"Icthior",
		"Paul Norell",
		"Supreme Commander Fowler Birdy",
		"Sarah Thomson",
		"Hydrax",
		"Diane",
		"Paul Barrett",
		"Thresher",
		"Greg Johnson",
		"Stench",
		"Beth Allen",
		"Ally Samuels",
		"Geoff Dolan",
		"Omni",
		"Herock",
		"Siobhan Page",
		"Patrick Wilson",
		"Dragoul",
		"Gabriel Knight",
		"Owen Black",
		"Dr. Felix",
		"Mikey Havoc",
		"Drakel",
		"Gregory Cooper",
		"Nick Kemplen",
		"James Napier Robertson",
		"Conner McKnight",
		"Natacha Hutchison",
		"Sophie",
		"Gina Varela",
		"Charlie",
		"Ray Trickitt",
		"Shorty",
		"Kevin Duhaney",
		"Ethan James",
		"Michael Drew",
		"Mirloc",
		"Jeremy Birchall",
		"Wootox",
		"Slate",
		"Bruce Hopkins",
		"Praxis",
		"Ringbah",
		"Stig Eldred",
		"Professor Cerebros",
		"Kraw",
		"Emma Lahana",
		"Kira Ford",
		"James Coleman",
		"Sinuku",
		"Campbell Cooley",
		"Tomars",
		"Thomas Kiwi",
		"Takaharu Miyazaki",
		"Jacob Graham",
		"Malachi Throne",
		"Matthew Sunderland",
		"Green Eyes",
		"Lori Dungey",
		"Louise Boom",
		"Dwayne Cameron",
		"Dru Harrington",
		"Giganis",
		"Blair Strang",
		"Bork",
		"Paul Willis",
		"Baskin",
		"Emlyn Williams",
		"Patrick Kuhtze",
		"Marjan Shahrinia",
		"Dr. Rheas",
		"Andy Wong",
		"Ross Buckingham",
		"Policeman",
		"Jim Lawrence",
		"Shane Bosher",
		"Gineka",
		"Michael Saccente",
		"Phil Boom",
		"Darren Young",
		"Eliana Saenz",
		"Kiel McNaughton",
		"Jaxin Hall",
		"Tall Cadet",
		"Elliot Lawless",
		"Mark",
		"Stephanie Morelli",
		"Young Z",
		"Jess Peters",
		"Dr. Helen Tyler-Jones",
		"Zahn Buchanan",
		"Craig Parker",
		"Michael Hurst",
		"Silverhead",
		"Cameron Rhodes",
		"Mooney",
		"Andrew Laing",
		"Delex",
		"Mick Innes",
		"Catherine Nola",
		"Ms. Carter",
		"Tom Kane",
		"Monster",
		"Tom Kane",
		"Roswell",
		"Jeffrey Parazzo",
		"Trent Fernandez",
		"Andrew Robertt",
		"Glen Drake",
		"Delapoo",
		"Stephen Brunton",
		"Chiaggo",
		"Antonia Prebble",
		"Jarrod Holt",
		"One-Eye",
		"Robert Pollock",
		"Vine Monster",
		"Alistair Browning",
		"Green Monster",
		"Claire Dougan",
		"Peter Feeney",
		"Spotty Eyed Monster",
		"Robert Mignault",
		"Crabhead",
		"Edwin Wright",
		"Micheala Rooney",
		"Motoko Nagino",
		"Ryûji Sainei",
		"Ancient Sensei",
		"Kevin Dufty",
		"Sam",
		"Taran Howell",
		"David Cassin",
		"John Laing",
		"Paul Grinder",
		"Britta Hawkins",
		"Andrew Merrifield",
		"Greg Aronowitz",
		"Mark Beesley",
		"Charlie Haskell",
		"Shotaro Ishinomori",
		"Saburo Yatsude",
		"Jackie Marchand",
		"Bruce Kalish",
		"John Tellegen",
		"Greg Aronowitz",
		"David Garber",
		"Jessie Horsting",
		"Stan Berkowitz",
		"Matt Hawkins",
		"Mark Hoffmeier",
	}
	S := dataset.SearchSystem_{}
	S.Constructor() // important
	S.Include(English2005ShowsKey, EntertainmentKey, ShowsKey, e2005, true, false, false)
	return S
}

func ShowsEnglish2012() dataset.SearchSystem_ {
	e2012 := map[string][]string{}
	e2012["kick buttowski"] = []string{
		"Charlie Schlatter",
		"Kick Buttowski",
		"Danny Cooksey",
		"Brad Buttowski",
		"Matt Jones",
		"Gunther",
		"John DiMaggio",
		"Mr. Vickle",
		"Brian Stepanek",
		"Harold Buttowski",
		"Kari Wahlgren",
		"Honey Buttowski",
		"Emily Osment",
		"Kendall Perkins",
		"Grey DeLisle",
		"Brianna Buttowski",
		"Maria Bamford",
		"Jackie",
		"Jeff Bennett",
		"Billy Stumps",
		"Greg Cipes",
		"Horace",
		"Eric Christian Olsen",
		"Wade",
		"Mindy Sterling",
		"Ms. Chicarelli",
		"Clancy Brown",
		"Magnus",
		"Carl Faruolo",
		"Papercut Peterson",
		"Howie",
		"Richard Steven Horvitz",
		"Simon Helberg",
		"Ronaldo",
		"Harland Williams",
		"Pantsy",
		"Danny Jacobs",
		"Rowdy Remington",
		"April Winchell",
		"Helga Magnuson",
		"Sandro Corsaro",
		"Michael Anthony DiPazzi",
		"Roz Ryan",
		"Mrs. Fitzpatrick",
		"Tom Kenny",
		"Kyle",
		"Don Zaza",
		"Fred Tatasciore",
		"Jess Harnell",
		"Susanne Blakeslee",
		"Librarian",
		"Grandma Rosie",
		"Dwight Howard",
		"Rock Callahan",
		"Jessica DiCicco",
		"Penelope",
		"Michelle",
		"James Arnold Taylor",
		"Jock Wilder(voice)",
		"Henry Winkler",
		"Doug Brochu",
		"Abbie",
		"Scott O'Brien",
		"Dangler",
		"Eric Bauza",
		"Mr. Huang",
		"Robobot",
		"Carlos Alazraqui",
		"Sanchez",
		"Amigo Grande",
		"Veronica Cartwright",
		"Ms. Dominic",
		"Leigh-Allyn Baker",
		"Sally",
		"Brian Doyle-Murray",
		"Will Forte",
		"Gordie Gibble",
		"Skai Jackson",
		"Madison",
		"Tony Hawk",
		"Hush",
		"Jennifer Hale",
		"Catherine Taber",
		"Kendall Perkins",
		"Chiara Zanni",
		"Tony Kornheiser",
		"Officer Irwin",
		"Kevin Michael Richardson",
		"Rock Calahan",
		"Lars",
		"Alyssa Milano",
		"Scarlett Rosetti",
		"Dee Bradley Baker",
		"Jeffrey Tambor",
		"Brian Van Holt",
		"Boom McCondor",
		"Adam Wylie",
		"Hiromi Dames",
		"Sam",
		"Tiffany Thornton",
		"Teena",
		"Joanna Garcia",
		"Shannon",
		"Emmanuelle Chriqui",
		"Kelly",
		"Jim Cummings",
		"Ed O'Neill",
		"Gary Anthony Williams",
		"Rico Rodriguez",
		"Luigi Vendetta",
		"David DeLuise",
		"Dead Man Dave",
		"Josh Robert Thompson",
		"Masasa Moyo",
		"Lauren Ashley",
		"Andrea Baker",
		"Carl Edwards",
		"Eddie Clutch",
		"Mike Golic",
		"Coach Sternbeck",
		"Jay Harris",
		"Brick Bristol",
		"Nestor Carbonell",
		"Javier",
		"Pamela Adlon",
		"Jim Parsons",
		"Larry Wilder",
		"John Henson",
		"Chuck Glarman",
		"Mark Cuban",
		"Mr. Gibble",
		"Keith Ferguson",
		"Wally Wingert",
		"Michael Wilbon",
		"Dick Vitale",
		"Viking Mayor",
		"Tony Reali",
		"The Dark One",
		"Stacey Ferguson",
		"April",
		"Adam Carolla",
		"One-Eyed Jackson",
		"Debbie Reynolds",
		"Mary Van Der Deth",
		"Lisa Kaplan",
		"Sunil Malhotra",
		"Yogi",
		"Sandro Corsaro",
		"Derek Dressler",
		"Patrick Andrew O'Connor",
		"David Shayne",
		"M.A. Larson",
		"Eric Rivera",
		"Nick Confalone",
		"Scott O'Brien",
		"Mike Yank",
		"David Lewman",
		"Joe Liss",
		"John Derevlany",
		"Mark Drop",
		"Nathan Knetchel",
		"Jonathan M. Howard",
		"Carl Faruolo",
		"Clay Morrow",
		"Jennifer Keene",
		"Adam Beechen",
		"Devin Bunje",
		"Bob Camp",
		"Marty Isenberg",
		"Bart Jennett",
		"Mike Kunkel",
		"Tony Mosher",
		"Chris Savino",
		"Scott Sonneborn",
		"Nick Stanton",
		"Guy Toubes",
		"Dean Batali",
		"Neal Boushell",
		"Brendan Duffy",
		"Mark Fellows",
		"Thomas Krajewski",
		"Kevin Monk",
		"Sam O'Neal",
		"Tabitha Vidaurri",
		"Chris Savio",
		"Clay Morrow",
	}
	e2012["gravity falls"] = []string{
		"Jason Ritter",
		"Dipper Pines",
		"Alex Hirsch",
		"Grunkle Stan",
		"Soos",
		"Kristen Schaal",
		"Mabel Pines",
		"Linda Cardellini",
		"Wendy Corduroy",
		"Kevin Michael Richardson",
		"Sheriff Blubs",
		"Chutzpar",
		"Matt Chapman",
		"Abuelita",
		"Mermando",
		"Kari Wahlgren",
		"Shandra Jimenez",
		"Priscilla Northwest",
		"John DiMaggio",
		"Manly Dan",
		"Manotaur",
		"Jennifer Coolidge",
		"Lazy Susan",
		"Keith Ferguson",
		"Deputy Durland",
		"Hillbilly",
		"Gregg Turkington",
		"Toby Determined",
		"Carl Faruolo",
		"Grenda",
		"Niki Yang",
		"Candy Chiu",
		"Candy",
		"Will Forte",
		"Tyler the Cute Biker",
		"Dee Bradley Baker",
		"Waddles",
		"Ball Game Carnie",
		"T.J. Miller",
		"Robbie Valentino",
		"Robbie",
		"Grey DeLisle",
		"Rosanna",
		"Michael Rianda",
		"Lee",
		"Thompson",
		"Thurop Van Orman",
		"Li'l Gideon",
		"Jackie Buscarino",
		"Pacifica Northwest",
		"Stephen Root",
		"Bud Gleeful",
		"J.K. Simmons",
		"Ford Pines",
		"Jessica DiCicco",
		"Tambry",
		"Queen Elizabeth",
		"Justin Roiland",
		"Blendin Blandin",
		"Bobby Renzobbi",
		"Fred Tatasciore",
		"The Gremloblin",
		"Hank",
		"Kimberly Mooney",
		"Janice Valentino",
		"Nathan Fillion",
		"Preston Northwest",
		"Brad Abrell",
		"Agent Trigger",
		"Brian Bloom",
		"Rumble McSkirmish",
		"Danielle Fishel",
		"Pyronica",
		"Corey Burton",
		"Lawyer",
		"Kevin",
		"Nick Offerman",
		"Agent Powers",
		"Alfred Molina",
		"Multi-Bear",
		"Louis C.K.",
		"The Horrifying Sweaty One-Armed Monstrosity",
		"Kurt Braunohler",
		"Greg Valentino",
		"Greg Cipes",
		"Craz",
		"Andy Merrill",
		"Teeth",
		"Tara Strong",
		"Sue",
		"Eric Bauza",
		"Miner",
		"Jeff Bennett",
		"The Summerween Trickster",
		"John Roberts",
		"Xyler",
		"April Winchell",
		"Dave Wittenberg",
		"Lolph",
		"Time Baby",
		"Cecil Baldwin",
		"Tad Strange",
		"Ken Jenkins",
		"Old Man Ghost",
		"Pa Duskerton",
		"Jillian Bell",
		"Melody",
		"Diedrich Bader",
		"Dundgren",
		"Jorma Taccone",
		"Gabe Bensen",
		"Patrick McHale",
		"Hectorgon",
		"Kyle MacLachlan",
		"Carter Hastings",
		"Library Kids",
		"Charlie",
		"Chris Parnell",
		"Charlie",
		"Preston Northwest",
		"Larry King",
		"Wax Larry King",
		"Horatio Sanz",
		"Window Man",
		"Nicole Mitchell",
		"Emma Sue",
		"Lance Bass",
		"Sev'ral Timez Band Members",
		"Ken Hudson Campbell",
		"Ergman Bratzman",
		"Coolio",
		"Wax Coolio",
		"Will Friedle",
		"Reginald",
		"Mark Hamill",
		"Frank Caliendo",
		"Sergei",
		"Jonathan Banks",
		"Filbrick Pines",
		"Chelsea Peretti",
		"Darlene",
		"John Oliver",
		"Wax Sherlock Holmes",
		"A. Smith Harrison",
		"Deep Voice Dipper",
		"Patton Oswalt",
		"Franz",
		"Paul Scheer",
		"Gary",
		"Neil deGrasse Tyson",
		"Smart Waddles",
		"Jon Stewart",
		"Sam Marin",
		"Celestabellebethabelle",
		"Shady Gnome",
		"Mckenna Grace",
		"Mariah Amundsen",
		"Kimberly Brooks",
		"Sassica",
		"Peter Serafinowicz",
		"Blind Ivan",
		"Jennifer Cody",
		"Donna",
		"Carla",
		"Stuart Allan",
		"Young Stan",
		"Jim Cummings",
		"Pirate Lilliputtian",
		"Declan Krogman",
		"Young Stan",
		"Daryl Sabara",
		"Rich Son",
		"Scott Menville",
		"Smile Dip Dog",
		"Blake Bertrand",
		"'Weird Al' Yankovic",
		"Probabilator",
		"Christian Mardini",
		"Young Ford",
		"Georgia G. Gillespie",
		"Mikey Kelley",
		"Cereal Box Toucan",
		"John O'Hurley",
		"Knight Lilliputtian",
		"Genesis Ochoa",
		"Young Tambry",
		"Nicolas Isler",
		"James Adomian",
		"Wax Groucho Marx",
		"Andrew Pifko",
		"Manotaur",
		"Jacob Shinder",
		"Greg Ellis",
		"Constable",
		"Wax William Shakespeare",
		"Chris Wylde",
		"Ariel Hirsch",
		"Joshua Rush",
		"Amory Watterson",
		"Young Wendy",
		"Peter Browngardt",
		"Ugly Mabel",
		"Joe Pitt",
		"John Aoshima",
		"Matt Braly",
		"Aaron Springer",
		"Stephen Sandoval",
		"Sunil Hall",
		"Rob Renzetti",
		"Alex Hirsch",
		"Mark Rizzo",
		"Matt Chapman",
		"Jeff Rowe",
		"Josh Weinstein",
		"Tim McKeon",
		"Zach Paez",
		"Michael Rianda",
		"Shion Takeuchi",
		"Aury Wallington",
		"Nancy Cohen",
		"M.A. Larson",
		"Tommy Reahard",
		"David Slack",
	}
	S := dataset.SearchSystem_{}
	S.Constructor() // important
	S.Include(English2012ShowsKey, EntertainmentKey, ShowsKey, e2012, true, false, false)
	return S
}
func ShowsMarathi2001() dataset.SearchSystem_ {
	m2001 := map[string][]string{}
	m2001["char divas sasuche"] = []string{
		"Rohini Hattangadi",
		"Ashalata",
		"Kavita Lad",
		"Anuradha",
		"Prajakta Dighe",
		"Nandini",
		"Nikhil Churi",
		"Salgaonkar",
		"Rajesh Gade",
		"Rajesh",
		"Aanand Kale",
		"Ashok Deshmukh",
		"Sunila Karambelkar",
		"Supriya",
		"Khalil Harekar",
		"Abhijeet Padnekar",
		"Anand Mhasvekar",
	}
	m2001["shriyut gangadhar tipre"] = []string{
		"Reshma Naik",
		"Shalaka Shekhar Tipre",
		"Dilip Prabhawalkar",
		"Gangadhar Tipre",
		"Rajan Bhise",
		"Shekhar Tipre",
		"Shubhangi Gokhale",
		"Shyamala Tipre",
		"Vikas Kadam",
		"Shirya Tipre",
		"Mukta Barve",
		"Yogita",
		"Shreyas Talpade",
		"Anil Gawas",
		"Kedar Shinde",
		"Dilip Prabhawalkar",
	}
	S := dataset.SearchSystem_{}
	S.Constructor() // important
	S.Include(Marathi2001ShowsKey, EntertainmentKey, ShowsKey, m2001, false, true, false)
	return S
}

func ShowsMarathi2014() dataset.SearchSystem_ {
	m2014 := map[string][]string{}
	m2014["chala hawa yeu dya"] = []string{
		"Bhau Kadam",
		"Bharat Ganeshpure",
		"Shreya Bugde",
		"Nilesh Sable",
		"Kushal Badrike",
		"Keya Ingle",
		"Tejas Dongre",
		"Akshar Kothari",
		"Aishwarya Sonar",
		"Gaurav Ghatnekar",
		"Nihar Gite",
		"Sharmila Shinde",
		"Umesh Jagtap",
		"Snehal Shidham",
		"Sagar Karande",
		"Nitin Bodhare",
		"Vinit Bonde",
		"Yogesh Shirsat",
		"Ajit Sable",
	}
	m2014["ka re durava"] = []string{
		"Suyash Tilak",
		"Jairam Khanolkar",
		"Suruchi Adarkar",
		"Aditi Dabholkar Khanolkar",
		"Neha Shitole",
		"Prajakta Dighe",
		"Mrs. Dabholkar",
		"Subodh Bhave",
		"Avinash Deo",
		"Neha Joshi",
		"Rajni Deshmukh",
		"Ila Bhate",
		"Mrs. Deo",
		"Sunil Tawde",
		"Vishakha Subhedar",
		"Archana Nipankar",
		"Jui",
		"Rajan Bhise",
		"Mr. Dabholkar",
		"Arun Nalawade",
		"Mr. Ketkar",
		"Omprakash Shinde",
		"Praful Samant",
		"Mr. Khanolkar",
		"Sheetal Kshirsagar",
		"Rajashri Nikam",
		"Manasi Magikar",
		"Jalindar Kumbhar",
	}
	S := dataset.SearchSystem_{}
	S.Constructor() // important
	S.Include(Marathi2014ShowsKey, EntertainmentKey, ShowsKey, m2014, false, true, false)
	return S
}

func BuildShows() ShowsParcel {
	m2001, m2014 := ShowsMarathi2001(), ShowsMarathi2014()
	h2011, h2012 := ShowsHindi2000(), ShowsHindi2005()

	e2010, e2012, e2015 := ShowsEnglish2001(), ShowsEnglish2005(), ShowsEnglish2012()
	me2009, mc2009, mf2009, mb2009, mi2009 := m2001.Manager(Marathi2001ShowsKey)
	me2014, mc2014, mf2014, mb2014, mi2014 := m2014.Manager(Marathi2014ShowsKey)

	he2011, hc2011, hf2011, hb2011, hi2011 := h2011.Manager(Hindi2000ShowsKey)
	he2012, hc2012, hf2012, hb2012, hi2012 := h2012.Manager(Hindi2005ShowsKey)

	ee2010, ec2010, ef2010, eb2010, ei2010 := e2010.Manager(English2001ShowsKey)
	ee2012, ec2012, ef2012, eb2012, ei2012 := e2012.Manager(English2005ShowsKey)
	ee2015, ec2015, ef2015, eb2015, ei2015 := e2015.Manager(English2012ShowsKey)

	parcel1 := EntertainmentParcel{Event: me2009, Category: mc2009, Field: mf2009, Book: mb2009, MappedItems: mi2009}
	parcel2 := EntertainmentParcel{Event: me2014, Category: mc2014, Field: mf2014, Book: mb2014, MappedItems: mi2014}
	parcel3 := EntertainmentParcel{Event: he2011, Category: hc2011, Field: hf2011, Book: hb2011, MappedItems: hi2011}
	parcel4 := EntertainmentParcel{Event: he2012, Category: hc2012, Field: hf2012, Book: hb2012, MappedItems: hi2012}
	parcel5 := EntertainmentParcel{Event: ee2010, Category: ec2010, Field: ef2010, Book: eb2010, MappedItems: ei2010}
	parcel6 := EntertainmentParcel{Event: ee2012, Category: ec2012, Field: ef2012, Book: eb2012, MappedItems: ei2012}
	parcel7 := EntertainmentParcel{Event: ee2015, Category: ec2015, Field: ef2015, Book: eb2015, MappedItems: ei2015}

	ready := []EntertainmentParcel{parcel1, parcel2, parcel3, parcel4, parcel5, parcel6, parcel7}
	pack := ShowsParcel{Pack: ready}
	return pack
}

func ShowsEvents() []string {
	events := []string{}
	openBuild := BuildShows()
	for _, event := range openBuild.Pack {
		events = append(events, event.Event)
	}
	return events
}

func ShowsCategory() string {
	category := []string{}
	token := BuildShows().Pack
	for _, cat := range token {
		category = append(category, cat.Category)
	}
	category = dataset.EraseDuplicate(category)
	cat := category[0]
	fmt.Println(category)
	return cat
}

func ShowsBook() string {
	fi := ""
	token := BuildShows().Pack
	for _, cat := range token {
		fi = cat.Book
	}
	return fi
}

func ShowsLists() []string {
	ma := []string{}
	token := BuildShows().Pack
	for _, t := range token {
		for items := range t.MappedItems {
			ma = append(ma, items)
		}
	}
	return ma
}

func ShowsSheet() map[string][]string {
	sheet := map[string][]string{}
	token := BuildShows().Pack
	for _, t := range token {
		maps.Copy(sheet, t.MappedItems)
	}
	return sheet
}
