package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"app/server/graph/model"
	"context"
	"fmt"
)

// Post is the resolver for the POST field.
func (r *mutationResolver) Post(ctx context.Context, client model.Put) (*model.Reply, error) {
	panic(fmt.Errorf("not implemented: Post - POST"))
}

// Client is the resolver for the client field.
func (r *queryResolver) Client(ctx context.Context, id string) (*model.InitMessage, error) {
	panic(fmt.Errorf("not implemented: Client - client"))
}

// Latest is the resolver for the latest field.
func (r *subscriptionResolver) Latest(ctx context.Context, room string) (<-chan *model.LatestMessage, error) {
	panic(fmt.Errorf("not implemented: Latest - latest"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
